#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# "!" - run commands (via system)

NAME='dbg.dcu+step'
FILE=../../bins/elf/elf-nx
ARGS=-d
BROKEN=
CMDS='e scr.color=0
s 0
db entry0
dc
db-entry0
dr pc
ds
dr pc
dk 9
'
EXPECT='0x080482d0
0x080482d2
'
IGNORE_ERR=1
run_test

