#!/bin/sh

# TODO: This script requires ROOT to be run in OSX
# (or just sign the r2 binary to get debugger priviledges)
# GPL 3+ - Copyright (C) 2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.filedescriptors'
FILE=../../bins/elf/elf-nx
ARGS=-d
BROKEN=1
CMDS='dd~?
dk 9'
EXPECT='3
'
IGNORE_ERR=1
run_test

