#!/bin/sh

# TODO: This script requires ROOT to be run in OSX
# (or just sign the r2 binary to get debugger priviledges)
# GPL 3+ - Copyright (C) 2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.maps'
FILE=../../bins/elf/elf-nx
ARGS=-d
BROKEN=
CMDS='dm~?
dk 9'
EXPECT='7
'
IGNORE_ERR=1
run_test

