#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami 65535sects.exe - open and analyze'
FILE=../../bins/pe/65535sects.exe
ARGS='-A'
CMDS="q!"
IGNORE_ERR=1
run_test

NAME='PE: corkami 65535sects.exe - sections list'
FILE=../../bins/pe/96emptysections.exe
BROKEN=1
ARGS='-n'
CMDS="!rabin2 -pS ${FILE}"
FILTER='grep sections'
EXPECT='65535 sections
'
IGNORE_ERR=1
run_test
