#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami 65535sects.exe - open and analyze'
FILE=../../bins/pe/65535sects.exe
ARGS='-A'
CMDS="q!"
IGNORE_ERR=1
run_test
