#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami appendedsecttbl.exe - open'
FILE=../../bins/pe/appendedsecttbl.exe
ARGS='-A'
CMDS="q!"
EXPECT=''
IGNORE_ERR=1
run_test

IGNORE_ERR=
NAME='PE: corkami appendedsecttbl.exe - entrypoint'
FILE=../../bins/pe/appendedsecttbl.exe
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test
