#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami appendeddata.exe - open'
FILE=../../bins/pe/appendeddata.exe
ARGS='-A'
CMDS="q!"
EXPECT=''
IGNORE_ERR=1
run_test
