#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami apphdrW7.exe - open'
FILE=../../bins/pe/apphdrW7.exe
ARGS=''
CMDS="q!"
EXPECT=''
IGNORE_ERR=1
run_test
