#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami apphdrW7.exe - open'
FILE=../../bins/pe/apphdrW7.exe
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami apphdrW7.exe - entrypoint'
FILE=../../bins/pe/apphdrW7.exe
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test
