#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dll.dll - DYNAMIC_BASE/ASLR disabled'
FILE=../../b/files/pe/dll.dll
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"pic	false\" "
EXPECT_ERR="Warning: Invalid import directory size: 0x0
"
EXPECT='pic	false
'
run_test

NAME='PE: corkami aslr.dll - DYNAMIC_BASE/ASLR enabled'
FILE=../../b/files/pe/aslr.dll
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"pic	true\" "
EXPECT_ERR=""
EXPECT='pic	true
'
run_test