#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami base.exe - open'
FILE=../../bins/pe/base.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='Relocs'
FILE=../../bins/pe/base.exe
ARGS=''
BROKEN=
CMDS='e asm.functions = false
e asm.comments = false
e asm.bytes = false
e asm.offset = false
e asm.calls = false
pd 1 @ 0x0040128d'
EXPECT='           call dword [sym.imp.msvcrt.dll___set_app_type]
'
run_test
