#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami bigsec.exe - open'
FILE=../../bins/pe/bigsec.exe
ARGS=''
CMDS="q!"
EXPECT=''
IGNORE_ERR=1
run_test

NAME='PE: corkami bigsec.exe - entrypoint'
FILE=../../bins/pe/bigsec.exe
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test
