#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami bigSoRD.exe - open'
FILE=../../bins/pe/bigSoRD.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami bigSoRD.exe - entrypoint'
FILE=../../bins/pe/bigSoRD.exe
BROKEN=
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test
