#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: checksum 1'
FILE=../../bins/pe/a.exe
ARGS='-A'
CMDS="iC"
EXPECT='File Checksum: 0x5ee2
Computed Checksum: 0x5ee2'
run_test

NAME='PE: checksum 2'
FILE=../../bins/pe/a2.exe
ARGS='-A'
CMDS="iC"
EXPECT='File Checksum: 0x79a3
Computed Checksum: 0x79a3'
run_test

NAME='PE: checksum 3'
FILE=../../bins/pe/base.exe
ARGS='-A'
CMDS="iC"
EXPECT='File Checksum: 0x3881f
Computed Checksum: 0x3881f'
run_test

