#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami CoST.exe - open and analyze'
FILE=../../bins/pe/CoST.exe
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami CoST.exe - entrypoint VA'
FILE=../../bins/pe/CoST.exe
BROKEN=1
ARGS='-n'
CMDS="!rabin2 -eq ${FILE}"
EXPECT='
'
run_test

NAME='PE: corkami CoST.exe - entrypoint PA'
FILE=../../bins/pe/CoST.exe
BROKEN=1
ARGS='-n'
CMDS="!rabin2 -peq ${FILE}"
EXPECT='
'
run_test

NAME='PE: corkami CoST.exe - sections list'
FILE=../../bins/pe/CoST.exe
ARGS='-n'
CMDS="!rabin2 -S ${FILE}"
EXPECT='[Sections]

0 sections
'
run_test
