#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami ctxt-ld.exe - open'
IGNORE_ERR=1
FILE=../../bins/pe/ctxt-ld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami ctxt-ld.exe - entrypoint'
FILE=../../bins/pe/ctxt-ld.exe
BROKEN=1
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test
