#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=1
NAME='PE: corkami ctxt-ld.exe - open'
IGNORE_ERR=1
FILE=../../b/files/pe/ctxt-ld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
