#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami ctxt.dll - open'
FILE=../../bins/pe/ctxt.dll
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami ctxt.dll - entrypoint'
FILE=../../bins/pe/ctxt.dll
CMDS='
s
'
EXPECT='0x1001000
'
IGNORE_ERR=1
run_test
