#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami d_nonnull-ld.exe - open'
FILE=../../bins/pe/d_nonnull-ld.exe
ARGS=''
CMDS="q!"
EXPECT=''
IGNORE_ERR=1
run_test

NAME='PE: corkami d_nonnull-ld - entrypoint'
FILE=../../bins/pe/d_nonnull-ld.exe
BROKEN=
CMDS='
s
'
EXPECT='0x401000
'
IGNORE_ERR=1
run_test
