#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='PE: corkami dep.exe - dep enabled'
FILE=../../b/files/pe/dep.exe
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"nx	true\" "

EXPECT='nx	true
'
run_test
