#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllbound-redirld.exe - open'
FILE=../../b/files/pe/dllbound-redirld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
