#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=
NAME='PE: corkami dllfakess-ld.dll - open'
FILE=../../b/files/pe/dllfakess-ld.dll
ARGS=''
CMDS="q!"
EXPECT=''
run_test