#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllmaxvals-dynld.exe - open'
FILE=../../b/files/pe/dllmaxvals-dynld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test