#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=1
NAME='PE: corkami dllnegep-ld.exe - open'
FILE=../../b/files/pe/dllnegep-ld.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test