#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllnullep.dll - open'
FILE=../../b/files/pe/dllnullep.dll
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: dllnullEP - entrypoint'
FILE=../../b/files/pe/dllnullep.dll
ARGS='-n'
CMDS="!rabin2 -eq ${FILE} "

EXPECT='0x00000000
'

run_test


