#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dllnegep.dll - open'
IGNORE_ERR=1
FILE=../../b/files/pe/dllnegep.dll
ARGS=''
CMDS="q!"
EXPECT=''
run_test
