#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

fuzz_test() {
NAME="PE fuzz $1"
IGNORE_ERR=1
BROKEN=
FILE=$2
ARGS=
CMDS='q'
EXPECT=''
run_test
}

COUNT=0
for i in ../../bins/pe/pefuzzed/file*; do
		fuzz_test $COUNT $i
done
