#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami hiddenappdata2.exe - open'
FILE=../../b/files/pe/hiddenappdata2.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test