#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami imports_tinyXP.exe - open'
FILE=../../b/files/pe/imports_tinyXP.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
