#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=1
NAME='PE: corkami lfanew_relocXP.exe - open'
FILE=../../b/files/pe/lfanew_relocXP.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
