#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami maxsec_lowaligW7.exe - open'
FILE=../../b/files/pe/maxsec_lowaligW7.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test