#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=
IGNORE_ERR=1
NAME='PE: corkami maxsecXP.exe - open'
FILE=../../b/files/pe/maxsecXP.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
