#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: pic false'
FILE=../../b/files/pe/mitigation_nothing.exe
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"pic	false\" "
EXPECT='pic	false
'
run_test

NAME='PE: pic true'
FILE=../../b/files/pe/mitigation_dynamic.exe
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"pic	true\" "
EXPECT='pic	true
'
run_test
