#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=1
IGNORE_ERR=1
NAME='PE: corkami mscoree.exe - open'
FILE=../../b/files/pe/mscoree.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test
