#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='PE: corkami normal.exe - bits 32'
FILE=../../b/files/pe/normal.exe
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"bits	32\" "
EXPECT_ERR="Warning: Invalid import directory size: 0x0
"
EXPECT='bits	32
'

run_test


NAME='PE: corkami normal.exe - machine i386'
FILE=../../b/files/pe/normal.exe
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"machine	i386\" "
EXPECT_ERR="Warning: Invalid import directory size: 0x0
"
EXPECT='machine	i386
'

run_test


NAME='PE: corkami normal.exe - class PE32'
FILE=../../b/files/pe/normal.exe
ARGS='-n'
CMDS="!rabin2 -I ${FILE} | grep \"class	PE32\" "
EXPECT_ERR="Warning: Invalid import directory size: 0x0
"
EXPECT='class	PE32
'

run_test
