#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami nosectionW7.exe - open'
FILE=../../bins/pe/nosectionW7.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: nosectionW7 - entrypoint'
FILE=../../bins/pe/nosectionW7.exe
ARGS='-n'
CMDS="!rabin2 -S ${FILE} "
EXPECT_ERR=""
EXPECT='[Sections]

0 sections
'

run_test


