#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='PE: nosectionW7 - entrypoint'
FILE=../../b/files/pe/nosectionW7.exe
ARGS='-n'
CMDS="!rabin2 -S ${FILE} "
EXPECT_ERR=""
EXPECT='[Sections]

0 sections
'

run_test


