#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami nullEP.exe - open'
FILE=../../b/files/pe/nullEP.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: nullEP - entrypoint'
FILE=../../b/files/pe/nullEP.exe
ARGS='-n'
CMDS="!rabin2 -eq ${FILE} "

EXPECT='0x00000000
'

run_test


