#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami nullEP.exe - open'
FILE=../../bins/pe/nullEP.exe
IGNORE_ERR=1
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: nullEP - entrypoint'
FILE=../../bins/pe/nullEP.exe
IGNORE_ERR=1
BROKEN=1
ARGS=''
CMDS='!rabin2 -eq ${FILE}
pi 1 @ `?v entry0`
'

EXPECT='0x00400000
dec ebp
'

run_test


