#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
F=../../bins/pe/base.exe

NAME='pe entrypoint'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='ie~addr
'
EXPECT='vaddr=0x00401280 off=0x00000680 baddr=0x00400000 laddr=0x00000000
'
run_test

NAME='pe relocs [r2]'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 1@0x401820~reloc
'
EXPECT='           0x00401820    ff25f0504000 jmp dword [reloc.msvcrt.dll_puts]
'
run_test

NAME='pe relocs [rabin2 a.exe]'
FILE=../../bins/pe/a.exe
ARGS=
CMDS="!rabin2 -R ${FILE}"
EXPECT='[Relocations]
addr=0x000012a0 off=0x000012a0 type=SET_32 KERNEL32.dll_AddAtomA
addr=0x000012a4 off=0x000012a4 type=SET_32 KERNEL32.dll_ExitProcess
addr=0x000012a8 off=0x000012a8 type=SET_32 KERNEL32.dll_FindAtomA
addr=0x000012ac off=0x000012ac type=SET_32 KERNEL32.dll_GetAtomNameA
addr=0x000012b0 off=0x000012b0 type=SET_32 KERNEL32.dll_SetUnhandledExceptionFilter
addr=0x000012bc off=0x000012bc type=SET_32 msvcrt.dll___getmainargs
addr=0x000012c0 off=0x000012c0 type=SET_32 msvcrt.dll___p__environ
addr=0x000012c4 off=0x000012c4 type=SET_32 msvcrt.dll___p__fmode
addr=0x000012c8 off=0x000012c8 type=SET_32 msvcrt.dll___set_app_type
addr=0x000012cc off=0x000012cc type=SET_32 msvcrt.dll__assert
addr=0x000012d0 off=0x000012d0 type=SET_32 msvcrt.dll__cexit
addr=0x000012d4 off=0x000012d4 type=SET_32 msvcrt.dll__iob
addr=0x000012d8 off=0x000012d8 type=SET_32 msvcrt.dll__onexit
addr=0x000012dc off=0x000012dc type=SET_32 msvcrt.dll__setmode
addr=0x000012e0 off=0x000012e0 type=SET_32 msvcrt.dll_abort
addr=0x000012e4 off=0x000012e4 type=SET_32 msvcrt.dll_atexit
addr=0x000012e8 off=0x000012e8 type=SET_32 msvcrt.dll_free
addr=0x000012ec off=0x000012ec type=SET_32 msvcrt.dll_malloc
addr=0x000012f0 off=0x000012f0 type=SET_32 msvcrt.dll_printf
addr=0x000012f4 off=0x000012f4 type=SET_32 msvcrt.dll_signal

20 relocations
'
run_test

NAME='pe relocs va [rabin2 a.exe]'
FILE=../../bins/pe/a.exe
ARGS=
CMDS="!rabin2 -vR ${FILE}"
EXPECT='[Relocations]
addr=0x004050a0 off=0x000012a0 type=SET_32 KERNEL32.dll_AddAtomA
addr=0x004050a4 off=0x000012a4 type=SET_32 KERNEL32.dll_ExitProcess
addr=0x004050a8 off=0x000012a8 type=SET_32 KERNEL32.dll_FindAtomA
addr=0x004050ac off=0x000012ac type=SET_32 KERNEL32.dll_GetAtomNameA
addr=0x004050b0 off=0x000012b0 type=SET_32 KERNEL32.dll_SetUnhandledExceptionFilter
addr=0x004050bc off=0x000012bc type=SET_32 msvcrt.dll___getmainargs
addr=0x004050c0 off=0x000012c0 type=SET_32 msvcrt.dll___p__environ
addr=0x004050c4 off=0x000012c4 type=SET_32 msvcrt.dll___p__fmode
addr=0x004050c8 off=0x000012c8 type=SET_32 msvcrt.dll___set_app_type
addr=0x004050cc off=0x000012cc type=SET_32 msvcrt.dll__assert
addr=0x004050d0 off=0x000012d0 type=SET_32 msvcrt.dll__cexit
addr=0x004050d4 off=0x000012d4 type=SET_32 msvcrt.dll__iob
addr=0x004050d8 off=0x000012d8 type=SET_32 msvcrt.dll__onexit
addr=0x004050dc off=0x000012dc type=SET_32 msvcrt.dll__setmode
addr=0x004050e0 off=0x000012e0 type=SET_32 msvcrt.dll_abort
addr=0x004050e4 off=0x000012e4 type=SET_32 msvcrt.dll_atexit
addr=0x004050e8 off=0x000012e8 type=SET_32 msvcrt.dll_free
addr=0x004050ec off=0x000012ec type=SET_32 msvcrt.dll_malloc
addr=0x004050f0 off=0x000012f0 type=SET_32 msvcrt.dll_printf
addr=0x004050f4 off=0x000012f4 type=SET_32 msvcrt.dll_signal

20 relocations
'
run_test

NAME='pe relocs [rabin2 b.exe]'
FILE=../../bins/pe/b.exe
ARGS=
CMDS="!rabin2 -R ${FILE}"
EXPECT='[Relocations]
addr=0x000012a0 off=0x000012a0 type=SET_32 KERNEL32.dll_AddAtomA
addr=0x000012a4 off=0x000012a4 type=SET_32 KERNEL32.dll_ExitProcess
addr=0x000012a8 off=0x000012a8 type=SET_32 KERNEL32.dll_FindAtomA
addr=0x000012ac off=0x000012ac type=SET_32 KERNEL32.dll_GetAtomNameA
addr=0x000012b0 off=0x000012b0 type=SET_32 KERNEL32.dll_SetUnhandledExceptionFilter
addr=0x000012bc off=0x000012bc type=SET_32 msvcrt.dll___getmainargs
addr=0x000012c0 off=0x000012c0 type=SET_32 msvcrt.dll___p__environ
addr=0x000012c4 off=0x000012c4 type=SET_32 msvcrt.dll___p__fmode
addr=0x000012c8 off=0x000012c8 type=SET_32 msvcrt.dll___set_app_type
addr=0x000012cc off=0x000012cc type=SET_32 msvcrt.dll__assert
addr=0x000012d0 off=0x000012d0 type=SET_32 msvcrt.dll__cexit
addr=0x000012d4 off=0x000012d4 type=SET_32 msvcrt.dll__iob
addr=0x000012d8 off=0x000012d8 type=SET_32 msvcrt.dll__onexit
addr=0x000012dc off=0x000012dc type=SET_32 msvcrt.dll__setmode
addr=0x000012e0 off=0x000012e0 type=SET_32 msvcrt.dll_abort
addr=0x000012e4 off=0x000012e4 type=SET_32 msvcrt.dll_atexit
addr=0x000012e8 off=0x000012e8 type=SET_32 msvcrt.dll_free
addr=0x000012ec off=0x000012ec type=SET_32 msvcrt.dll_malloc
addr=0x000012f0 off=0x000012f0 type=SET_32 msvcrt.dll_printf
addr=0x000012f4 off=0x000012f4 type=SET_32 msvcrt.dll_signal

20 relocations
'
run_test

NAME='pe string'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 1@0x0040131a~str.Hello
'
EXPECT='           0x0040131a    c7042400304. mov dword [esp], str.Hello_n ;  0x00403000 
'
run_test

