#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
F=../../b/files/base.exe

NAME='pe entrypoint'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='ie~addr
'
EXPECT='addr=0x00001280 off=0x00000680 baddr=0x00000000
'
run_test

NAME='pe relocs'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 1@0x401820~reloc
'
EXPECT='           0x00401820    ff25f0504000 jmp dword [reloc.msvcrt.dll_puts]
'
run_test

NAME='pe string'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 1@0x0040131a~str.Hello
'

EXPECT='           0x0040131a    c7042400304. mov dword [esp], str.Hello ; "0@" ;  0x00403000 
'
run_test
