#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami resource_string.exe - open'
FILE=../../b/files/pe/resource_string.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test