#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami tinydrivXP.sys - open'
IGNORE_ERR=1
FILE=../../b/files/pe/tinydrivXP.sys
ARGS=''
CMDS="q!"
EXPECT=''
run_test
