#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami tinyW7_3264.exe - open'
FILE=../../b/files/pe/tinyW7_3264.exe
IGNORE_ERR=1
ARGS=''
CMDS="q!"
EXPECT=''
run_test
