#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami tinygui.exe - open'
FILE=../../b/files/pe/tinygui.exe
IGNORE_ERR=1
ARGS=''
CMDS="q!"
EXPECT=''
run_test
