#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami tinydll-ld.exe - open'
FILE=../../bins/pe/tinydll-ld.exe
ARGS=''
CMDS="q!"
EXPECT=''
INGORE_ERR=1
run_test
