#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami tls_noEP.exe - open'
FILE=../../bins/pe/tls_noEP.exe
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='PE: tls_noEP - entrypoint'
FILE=../../bins/pe/tls_noEP.exe
ARGS='-n'
CMDS="!rabin2 -eq ${FILE} "

EXPECT='0xffc00000
'

run_test


