#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=1
NAME='PE: corkami tls_aoiOSDET.exe - open'
FILE=../../bins/pe/tls_aoiOSDET.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test