#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

BROKEN=1
NAME='PE: corkami virtrelocXP.exe - open'
FILE=../../b/files/pe/virtrelocXP.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test