#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami weirdsord.exe - open'
FILE=../../bins/pe/weirdsord.exe
ARGS=''
CMDS="q!"
IGNORE_ERR=1
EXPECT=''
run_test
