#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: zzufed 1 - open'
FILE=../../bins/pe/zzufed/file1
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='PE: zzufed 2 - open'
FILE=../../bins/pe/zzufed/file2
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='PE: zzufed 3 - open'
FILE=../../bins/pe/zzufed/file3
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test