#!/bin/sh
# GPL 3+ - Copyright (C) 2016  pancake, jduck

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# "!" - run commands (via system)

NAME='dbg.dc.loop.swstep'
FILE=../../bins/elf/x64-loop
ARGS=-d
BROKEN=
CMDS='e scr.color=0
e dbg.swstep=true
db sym.called_in_loop
dc
dr PC
dc
dr PC
dc
dr PC
dk 9
'
EXPECT='0x004004ed
0x004004ed
0x004004ed
'
IGNORE_ERR=1
run_test

NAME='dbg.dc.loop.hwstep'
FILE=../../bins/elf/x64-loop
ARGS=-d
BROKEN=
CMDS='e scr.color=0
e dbg.swstep=false
db sym.called_in_loop
dc
dr PC
dc
dr PC
dc
dr PC
dk 9
'
EXPECT='0x004004ed
0x004004ed
0x004004ed
'
IGNORE_ERR=1
run_test
