#!/bin/sh
# GPL 3+ - Copyright (C) 2017 maijin
[ -e tests.sh ] && . ./tests.sh || . ../../tests.sh

NAME='arm relsub >256'
FILE=-
ARGS=
BROKEN=
CMDS='wx 0d039fe5
e asm.arch=arm
e asm.bits=32
e asm.comments=false
e asm.bytes=false
e asm.offset=false
f sym.callback=0x315
pd 1'
EXPECT='                 ldr r0, [sym.callback]
'
run_test

NAME='arm relsub <256'
FILE=-
ARGS=
BROKEN=
CMDS='wx 0c009fe5
e asm.arch=arm
e asm.bits=32
e asm.comments=false
e asm.bytes=false
e asm.offset=false
f sym.callback=0x14
pd 1'
EXPECT='                 ldr r0, [0x00000014]
'
run_test
