#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="ELF ARM: function arg"
BROKEN=
FILE=../../bins/elf/armcall
CMDS='
afr@main
pdf@sym.call
'
EXPECT='            ;-- $a_10:
/ (fcn) sym.call 44
|           ; arg int arg_8h @ fp+0x8
|           ; CALL XREF from 0x00010468 (sym.main)
|           0x00010420      00482de9       push {fp, lr}
|           0x00010424      04b08de2       add fp, sp, 4
|           0x00010428      08d04de2       sub sp, sp, 8
|           0x0001042c      08000be5       str r0, [fp - arg_8h]
|           0x00010430      14009fe5       ldr r0, [pc, 0x14]          ; [0x1044c:4]=0x104f0 loc._d_14 LEA loc._d_15 ; loc._d_15
|           0x00010434      08101be5       ldr r1, [fp - arg_8h]
|           0x00010438      a2ffffeb       bl sym.imp.printf
|           0x0001043c      0030a0e3       mov r3, 0
|           0x00010440      0300a0e1       mov r0, r3
|           0x00010444      04d04be2       sub sp, fp, 4
\           0x00010448      0088bde8       pop {fp, pc}
'
run_test


NAME="ELF ARM: function args"
BROKEN=
FILE=../../bins/elf/armcall
CMDS='
af@main
pdf@main
'
EXPECT='            ;-- main:
            ;-- $a_11:
/ (fcn) sym.main 44
|           ; arg int arg_8h @ fp+0x8
|           ; arg int arg_ch @ fp+0xc
|           0x00010450      00482de9       push {fp, lr}
|           0x00010454      04b08de2       add fp, sp, 4
|           0x00010458      08d04de2       sub sp, sp, 8
|           0x0001045c      08000be5       str r0, [fp - arg_8h]
|           0x00010460      0c100be5       str r1, [fp - arg_ch]
|           0x00010464      08001be5       ldr r0, [fp - arg_8h]
|           0x00010468      ecffffeb       bl sym.call
|           0x0001046c      0030a0e1       mov r3, r0
|           0x00010470      0300a0e1       mov r0, r3
|           0x00010474      04d04be2       sub sp, fp, 4
\           0x00010478      0088bde8       pop {fp, pc}
'
run_test


NAME="ELF ARM: aav"
BROKEN=
FILE=../../bins/elf/armcall
CMDS='
aav
pd 3 @ 0x00010328
'
EXPECT='            ;-- $d_2:
            ; UNKNOWN XREF from 0x00010988 (unk)
            0x00010328 .dword 0x000104e0 ; sym.__libc_csu_fini
            0x0001032c .dword 0x00010450 ; sym.main
            ; UNKNOWN XREF from 0x000102c4 (unk)
            0x00010330 .dword 0x0001047c ; sym.__libc_csu_init
'
run_test

NAME="ELF ARM: vars"
BROKEN=
FILE=../../bins/elf/arm-ls
CMDS='
s main
af
pd 1~local?
'
EXPECT='43
'
run_test
