#!/bin/sh

R2RDIR="@R2RDIR@"

if [ "${R2RDIR}" != "@""R2RDIR@" ]; then
	cd "${R2RDIR}"
else
	while [ ! -x r2r ]; do
		cd ..
		if [ "`pwd`" = / ]; then
			echo "Cannot find radare2-regressions/"
			exit 1
		fi
	done
fi

KW="$1"
KX="$2"

control_c() {
	echo "^C"
	exit 1
}

trap control_c 2

usage() {
	echo "Usage: r2r [-s] [keyword]"
}

case "$KW" in
-h)
	usage
	exit 0
	;;
-s)
	if [ -n "$KX" ]; then
		find t* | grep "$KX"
		exit 0
	else
		usage
		exit 1
	fi
	;;
esac

export VERBOSE=1

if [ -n "$KW" ]; then
	if [ -n "$KX" ]; then
		TESTS=`find t* | grep "$KW" | grep "$KX" | grep -v '/\.'`
	else
		TESTS=`find t* | grep "$KW" | grep -v '/\.'`
	fi
	echo
	echo "$TESTS"
	echo
	DIRS=""
	for a in ${TESTS} ; do
		SKIP=0
		if [ -d "$a" ]; then
			DIRS="${DIRS} $a"
		else
			for b in ${DIRS} ; do
				if [ -n "`echo $a | grep ^$b`" ]; then
					echo "Skip $a"
					SKIP=1
					break
				fi
			done
		fi
		[ "${SKIP}" = 0 ] && sh run_tests.sh "$a"
	done
else
	usage
	exit 1
fi
