#!/bin/sh

# GPL 3+ - Copyright (C) 2016 pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='anal fcn names with symbols'
BROKEN=1
FILE=../../bins/mach0/libr_bp.dylib
ARGS=-A
CMDS='afl~00760
'
EXPECT='0x00000760  379  7  sym._r_bp_new
'
run_test

