#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

fuzz_test() {
	NAME="MACH0: fuzzed $1"
	FILE=$2
	BROKEN=$3
	ARGS=
	CMDS="q"
	EXPECT=''
	run_test
}

COUNT=0
for i in ../../bins/mach0/machfuzzed/mach*; do
	fuzz_test $COUNT $i
done

fuzz_test RsFuzz ../../bins/mach0/rsfuzz-3b3a5a268 1
