#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='mach0 entrypoint'
BROKEN=1
FILE=../../bins/mach0/hello-osx-i386
ARGS=
CMDS='ie~addr
'
EXPECT='vaddr=0x00001f14 off=0x00000f14 baddr=0x00001000 laddr=0x00000000
'
run_test

NAME='mach0 entry0 data'
BROKEN=
FILE=../../bins/mach0/hello-osx-i386
ARGS=
CMDS='p8 10 @ entry0
'
EXPECT='6a0089e583e4f083ec10
'
run_test

NAME='osx mach0 entrypoint'
BROKEN=
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
CMDS='ie~addr
'
EXPECT='vaddr=0x1000010f8 paddr=0x000010f8 baddr=0x100000000 laddr=0x00000000
'
run_test

NAME='osx mach0 ik'
BROKEN=
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
IGNORE_ERR=1
CMDS='ik~uuid
'
EXPECT='uuid.0=ff4d6c2e1dc0369d98d0d3040a8049e8
'
run_test
