#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='MACH0: zzufed 1 - open'
FILE=../../bins/mach0/zzufed/file1
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 2 - open'
FILE=../../bins/mach0/zzufed/file2
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 3 - open'
FILE=../../bins/mach0/zzufed/file3
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 4 - open'
FILE=../../bins/mach0/zzufed/file4
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 5 - open'
FILE=../../bins/mach0/zzufed/file5
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 6 - open'
FILE=../../bins/mach0/zzufed/file6
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 7 - open'
FILE=../../bins/mach0/zzufed/file7
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 8 - open'
FILE=../../bins/mach0/zzufed/file8
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 9 - open'
FILE=../../bins/mach0/zzufed/file9
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 10 - open'
FILE=../../bins/mach0/zzufed/file10
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 11 - open'
FILE=../../bins/mach0/zzufed/file11
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='MACH0: zzufed 12 - open'
FILE=../../bins/mach0/zzufed/file12
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test