#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='mz fuzz 1'
IGNORE_ERR=1
FILE=../../bins/mz/96e515d6ded1aaa475c3a03dcec7dc99
ARGS=
CMDS='q'
EXPECT=''
run_test

NAME='mz fuzz 2'
IGNORE_ERR=1
FILE=../../bins/mz/fb46896fb3d9127acedbde681d274111
ARGS=
CMDS='q'
EXPECT=''
run_test

