#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

fuzz_test() {
NAME="java fuzz $1"
IGNORE_ERR=1
BROKEN=
FILE=$2
ARGS=
CMDS='q'
EXPECT=''
run_test
}

fuzz_test 1 ../../bins/java/fuzz-jox01
fuzz_test 2 ../../bins/java/fuzz-jox02
fuzz_test 3 ../../bins/java/fuzz-jox03
