#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='avr entrypoint'
BROKEN=1
FILE=../../b/files/elf/bugurtos-avr.elf
ARGS=
CMDS='ie~addr
'
EXPECT='addr=0x00000000 off=0x00000074 baddr=0x00000000
'
run_test


