#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: dis entry0 hello-android-arm'
FILE=../../bins/elf/hello-android-arm
ARGS=''
CMDS="pid 6@entry0"
EXPECT='0x00008300          0d00a0e1  mov r0, sp
0x00008304          0010a0e3  mov r1, 0
0x00008308          04208fe2  add r2, pc, 4
0x0000830c          04308fe2  add r3, pc, 4
0x00008310          f6ffffea  b 0x000082f0
0x00008314          050000ea  b 0x00008330
'
run_test
