#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dummy_secnames.elf - open'
FILE=../../bins/elf/dummy_secnames.elf
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test