#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dummy_shnum.elf - open'
IGNORE_ERR=1
FILE=../../bins/elf/dummy_shnum.elf
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test
