#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami dummy_secvals.elf - open'
FILE=../../b/files/elf/dummy_secvals.elf
ARGS=''
CMDS="q!"
EXPECT=''
run_test