#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami elf-nx - open'
FILE=../../b/files/elf/elf-nx
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami elf-nx - nx enabled'
FILE=../../b/files/elf/elf-nx
ARGS=''
CMDS="iI | grep \"nx	true\" "

EXPECT='nx	true
'
run_test