#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami elf-relro - open'
FILE=../../b/files/elf/elf-relro
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami elf-relro - relro enabled'
FILE=../../b/files/elf/elf-relro
ARGS=''
CMDS="ik~elf.relro=true"

EXPECT='elf.relro=true
'
run_test