#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami elf-xnorelro - open'
FILE=../../bins/elf/elf-xnorelro
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami elf-xnorelro - relro disabled'
FILE=../../bins/elf/elf-xnorelro
ARGS=''
CMDS="ik~elf.relro=false"

EXPECT='elf.relro=false
'
run_test


NAME='PE: corkami elf-nx -  nx disabled'
FILE=../../bins/elf/elf-xnorelro
ARGS=''
CMDS="iI~^nx"

EXPECT='nx	false
'

run_test
