#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami elf-xnorelro - open'
FILE=../../b/files/elf/elf-xnorelro
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami elf-xnorelro - relro disabled'
FILE=../../b/files/elf/elf-xnorelro
ARGS=''
CMDS="ik~elf.relro=false"

EXPECT='elf.relro=false
'
run_test


NAME='PE: corkami elf-nx -  nx disabled'
FILE=../../b/files/elf/elf-xnorelro
ARGS=''
CMDS="iI | grep \"nx	false\" "

EXPECT='nx	false
'

run_test