#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: corkami elf-relro - sections'
FILE=../../bins/elf/arm-relocs
ARGS=''
CMDS="ir*~?
ir*~!1"
EXPECT='11
fs relocs
f reloc.r0_52 @ 0x08000034
f reloc.r2_60 @ 0x0800003c
f reloc.r3_64 @ 0x08000040
f reloc.r4_68 @ 0x08000044
f reloc.r0_76 @ 0x0800004c
f reloc.r2_84 @ 0x08000054
f reloc.r3_88 @ 0x08000058
f reloc.r4_92 @ 0x0800005c
'
run_test
