#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: main'
FILE=../../bins/elf/main
ARGS=''
CMDS="?v main"
EXPECT='0x400506
'
run_test

NAME='ELF: main rebased'
FILE=../../bins/elf/pie-main
ARGS='-B 0x200000'
CMDS="?v main"
EXPECT='0x203bd0
'
run_test

NAME='ELF: main rebased'
FILE=../../bins/elf/pie-main
ARGS='-B 0x100000'
CMDS="?v main"
EXPECT='0x103bd0
'
run_test

NAME='ELF: main rebased'
FILE=../../bins/elf/main
ARGS='-B 0x200000'
CMDS="?v main"
EXPECT='0x200506
'
run_test

NAME='ELF: main rebased'
FILE=-
ARGS='-B 0x200000'
CMDS="!rabin2 -qMB 0x200000 ../../bins/elf/main"
EXPECT='2098438'
run_test

NAME='ELF: sym.main'
FILE=../../bins/elf/main
ARGS=''
CMDS="?v sym.main"
EXPECT='0x400506
'
run_test

NAME='ELF: pie main'
FILE=../../bins/elf/pie-main
ARGS=''
CMDS="?v main"
EXPECT='0x3bd0
'
run_test

NAME='MIPS: main'
FILE=../../bins/elf/mips-main
ARGS=''
CMDS="?v main"
EXPECT='0x4006f0
'
run_test
