#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: main'
FILE=../../bins/elf/main
ARGS=''
CMDS="?v main"
EXPECT='0x400506
'
run_test

NAME='ELF: sym.main'
FILE=../../bins/elf/main
ARGS=''
CMDS="?v sym.main"
EXPECT='0x400506
'
run_test

NAME='ELF: pie main'
FILE=../../bins/elf/pie-main
ARGS=''
CMDS="?v main"
EXPECT='0x3bd0
'
run_test
