#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

IGNORE_ERR=1
NAME='PE: corkami no_sechdr.elf - open'
FILE=../../bins/elf/no_sechdr.elf
ARGS=''
CMDS="q!"
EXPECT=''
run_test
