#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

IGNORE_ERR=1
NAME='ELF: no_sections.elf - open'
FILE=../../bins/elf/no_sections.elf
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test
