#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='PE: corkami standard.elf - open'
FILE=../../bins/elf/standard.elf
IGNORE_ERR=1
ARGS=''
CMDS="q!"
EXPECT=''
run_test
