#!/bin/sh

# GPL 3+ - Copyright (C) 2013-2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='thumb entry0'
FILE=../../bins/elf/thumb
ARGS=
CMDS='?v entry0
'
EXPECT='0x82f0
'
run_test

NAME='thumb main'
FILE=../../bins/elf/thumb
ARGS=
CMDS='?v sym.main
'
EXPECT='0x8424
'
run_test

NAME='thumb sym'
FILE=../../bins/elf/thumb
ARGS=
CMDS='is~=main[1]
is~=main[3]
'
EXPECT='0x00008424
0x00000424
'
run_test

NAME='thumb disasm'
FILE=../../bins/elf/thumb
ARGS=
CMDS='pi 1@ sym.main
'
EXPECT='push {r7, lr}
'
run_test

NAME='arm disasm entry0'
FILE=../../bins/elf/thumb
ARGS=
CMDS='pi 1@ sym.main
'
EXPECT='push {r7, lr}
'
run_test

NAME='thumb anal expand'
FILE=../../bins/elf/thumb
ARGS=
BROKEN=1
IGNORE_ERR=1
CMDS='pi 2@sym.main
af@sym.main
pi 2 @sym.main
'
EXPECT='push {r7, lr}
andhs sl, sl, r0, lsl 30
push {r7, lr}
add r7, sp, 0
'
run_test

