#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: no version info'
FILE=../../bins/elf/x64-simple
CMDS='iV'
EXPECT=''
run_test

NAME='ELF: versioninfo 1'
FILE=../../bins/elf/serial
CMDS='iV'
EXPECT="Version symbols section '.gnu.version' contains 11 entries:
 Addr: 0x00400442  Offset: 0x00000442  Link: 5 (.dynsym)
  000: 0 (*local*) (GLIBC_2.2.5) (GLIBC_2.2.5) (GLIBC_2.2.5) 
  004: (GLIBC_2.2.5) (GLIBC_2.2.5) (GLIBC_2.4) (GLIBC_2.2.5) 
  008: (GLIBC_2.2.5) (GLIBC_2.2.5) 0 (*local*) 


Version need section '.gnu.version_r' contains 1 entries:
 Addr: 0x400458  Offset: 0x458  Link to section: 6 (.dynstr)
  000000: Version: 1  File: libc.so.6  Cnt: 2
  0x0010:   Name: GLIBC_2.4  Flags: none Version: 3
  0x0020:   Name: GLIBC_2.2.5  Flags: none Version: 2
"
run_test

NAME='ELF: versioninfo 2'
FILE=../../bins/elf/hello-linux-x86_64
CMDS='iV'
EXPECT="Version symbols section '.gnu.version' contains 4 entries:
 Addr: 0x0040031e  Offset: 0x0000031e  Link: 5 (.dynsym)
  000: 0 (*local*) (GLIBC_2.2.5) (GLIBC_2.2.5) 0 (*local*) 


Version need section '.gnu.version_r' contains 1 entries:
 Addr: 0x400328  Offset: 0x328  Link to section: 6 (.dynstr)
  000000: Version: 1  File: libc.so.6  Cnt: 1
  0x0010:   Name: GLIBC_2.2.5  Flags: none Version: 2
"
run_test
