#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='ELF: zzufed 1 - open'
FILE=../../bins/elf/zzufed/file1
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 2 - open'
FILE=../../bins/elf/zzufed/file2
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 3 - open'
FILE=../../bins/elf/zzufed/file3
ARGS='-qA'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 4 - open'
FILE=../../bins/elf/zzufed/file4
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 5 - open'
FILE=../../bins/elf/zzufed/file5
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 6 - open'
FILE=../../bins/elf/zzufed/file6
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 7 - open'
FILE=../../bins/elf/zzufed/file7
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 8 - open'
FILE=../../bins/elf/zzufed/file8
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test

NAME='ELF: zzufed 9 - open'
FILE=../../bins/elf/zzufed/file9
ARGS='-A'
CMDS="q!"
EXPECT=''
run_test
