#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh; done

test_vector() {
NAME="${1}: [${2}]"
FILE=malloc://32
if [ "${4}" = "br" ]; then
	BROKEN=1
fi
CMDS='
e asm.arch='${1}'
e asm.bits=32
e cfg.bigendian=true
wx '${3}'
pi 1
'
EXPECT="$(echo ${2} | tr '[:upper:]' '[:lower:]')
"
run_test
}

PLUGIN=dalvik

test_vector "${PLUGIN}" "nop" 0000
test_vector "${PLUGIN}" "move v0, v1" 0110
test_vector "${PLUGIN}" "move/from16 v0, v25" 02001900
test_vector "${PLUGIN}" "move/16 v0, v0" 03000000
test_vector "${PLUGIN}" "move-wide v0, v0" 04000000
test_vector "${PLUGIN}" "move-wide/from16 v22, v0" 05160000
test_vector "${PLUGIN}" "move-wide/16 v0, v0" 06000000
test_vector "${PLUGIN}" "move-object v1, v8" 0781
test_vector "${PLUGIN}" "move-object/from16 v1, v21" 08011500
test_vector "${PLUGIN}" "move-object/16 v0, v0" 0900
test_vector "${PLUGIN}" "move-result v0" 0A00
test_vector "${PLUGIN}" "move-result-wide v2" 0B02
test_vector "${PLUGIN}" "move-result-object v0" 0C00
test_vector "${PLUGIN}" "move-exception v25" 0D19
test_vector "${PLUGIN}" "return-void" 0E00
test_vector "${PLUGIN}" "return v0" 0F00
test_vector "${PLUGIN}" "return-wide v0" 1000
test_vector "${PLUGIN}" "return-object v0" 1100
test_vector "${PLUGIN}" "const/4 v1, 0x2" 1221
test_vector "${PLUGIN}" "const/16 v0, 0x0a" 13000A00 #const/16 v0, #int 10
test_vector "${PLUGIN}" "const v0, 0x00bc614e" 14004E61BC00 br #const v0, #12345678 // #00BC614E
test_vector "${PLUGIN}" "const/high16 v0, 0x41200000" 15002041 br # const/high16 v0, #float 10.0 // #41200000
test_vector "${PLUGIN}" "const-wide/16 v0, 0000" 16000000
test_vector "${PLUGIN}" "const-wide/32 v2, 0x00bc614e" 17024e61bc00 br
test_vector "${PLUGIN}" "const-wide v2, 0x002bdc545d6b4b87" 1802874b6b5d54dc2b00 br
test_vector "${PLUGIN}" "const-wide/high16 v0, 0x41200000" 19002440 br
test_vector "${PLUGIN}" "const-string v8, string+0" 1A080000
test_vector "${PLUGIN}" "const-string/jumbo v8, string+0" 1B080000
test_vector "${PLUGIN}" "const-class v0, class+1" 1C000100
test_vector "${PLUGIN}" "monitor-enter v3" 1D030000
test_vector "${PLUGIN}" "monitor-exit v3" 1E030000
test_vector "${PLUGIN}" "check-cast v4, class+1" 1F040100
test_vector "${PLUGIN}" "instance-of v0, v4, class+1" 20400100
test_vector "${PLUGIN}" "array-length v1, v1" 21110000
test_vector "${PLUGIN}" "new-instance v0, class+1" 22000100
test_vector "${PLUGIN}" "new-array v2, v1, class+1" 23120100
test_vector "${PLUGIN}" "filled-new-array {v0, v0}, class+1" 242001000000
test_vector "${PLUGIN}" "filled-new-array/range {v19..v21}, class+6" 250306001300
test_vector "${PLUGIN}" "fill-array-data v6, 0x00000025" 260625000000
test_vector "${PLUGIN}" "throw v0" 2700
test_vector "${PLUGIN}" "check-cast v4, class+1" 28F0 br # goto 0005 // -0010
test_vector "${PLUGIN}" "check-cast v4, class+1" 29000FFE br # goto/16 002f // -01f1
test_vector "${PLUGIN}" "check-cast v4, class+1" 2A000FFE br # goto/32 002f // -01f1
test_vector "${PLUGIN}" "packed-switch v2, 0x0000000c" 2B020C000000
test_vector "${PLUGIN}" "sparse-switch v2, 0x0000000c" 2C020c000000
test_vector "${PLUGIN}" "cmpl-float v0, v6, v7" 2D000607
test_vector "${PLUGIN}" "cmpg-float v0, v6, v7" 2E000607
test_vector "${PLUGIN}" "cmpl-double v25, v6, v8" 2F190608
test_vector "${PLUGIN}" "cmpg-double v0, v8, v10" 3000080A
test_vector "${PLUGIN}" "cmp-long v0, v2, v4" 31000204
test_vector "${PLUGIN}" "if-eq v3, v11, 0x0" 32b30000
test_vector "${PLUGIN}" "if-ne v3, v10, 0x0" 33A30000
test_vector "${PLUGIN}" "if-lt v2, v3, 0x0" 34320000
test_vector "${PLUGIN}" "if-ge v0, v1, 0x0" 35100000
test_vector "${PLUGIN}" "if-gt v0, v1, 0x0" 36100000
test_vector "${PLUGIN}" "if-le v6, v5, 0x0" 37560000
test_vector "${PLUGIN}" "if-eqz v2, 0x0" 38020000 br
test_vector "${PLUGIN}" "if-nez v2, 0x0" 39020000 br
test_vector "${PLUGIN}" "if-ltz v0, 0x0" 3A000000 br
test_vector "${PLUGIN}" "if-gez v0, 0x0" 3B000000 br
test_vector "${PLUGIN}" "if-gtz v0, 0x0" 3C000000 br
test_vector "${PLUGIN}" "if-lez v0, 0x0" 3D000000 br
test_vector "${PLUGIN}" "aget v7, v3, v6" 44070306
test_vector "${PLUGIN}" "aget-wide v5, v1, v4" 45050104
test_vector "${PLUGIN}" "aget-object v2, v2, v0" 46020200
test_vector "${PLUGIN}" "aget-boolean v0, v0, v1" 47000001
test_vector "${PLUGIN}" "aget-byte v0, v0, v1" 48000001
test_vector "${PLUGIN}" "aget-char v5, v0, v3" 49050003
test_vector "${PLUGIN}" "aget-short v0, v0, v1" 4A000001
test_vector "${PLUGIN}" "aput v0, v3, v5" 4B000305
test_vector "${PLUGIN}" "aput-wide v5, v1, v4" 4C050104
test_vector "${PLUGIN}" "aput-object v2, v1, v0" 4D020100
test_vector "${PLUGIN}" "aput-boolean v1, v0, v2" 4E010002
test_vector "${PLUGIN}" "aput-byte v2, v0, v1" 4F020001
test_vector "${PLUGIN}" "aput-char v3, v0, v1" 50030001
test_vector "${PLUGIN}" "aput-short v2, v0, v1" 51020001
test_vector "${PLUGIN}" "iget v0, v1, field+3" 52100300
test_vector "${PLUGIN}" "iget-wide v0, v2, field+4" 53200400
test_vector "${PLUGIN}" "iget-object v0, v2, field+4" 54200400
test_vector "${PLUGIN}" "iget-boolean v12, v15, field+0" 55FC0000
test_vector "${PLUGIN}" "iget-byte v2, v3, field+1" 56320100
test_vector "${PLUGIN}" "iget-char v0, v2, field+3" 57200300
test_vector "${PLUGIN}" "iget-short v0, v3, field+8" 58300800
test_vector "${PLUGIN}" "iput v0, v2, field+2" 59200200
test_vector "${PLUGIN}" "iput-wide v0, v2, field+0" 5A200000
test_vector "${PLUGIN}" "iput-object v0, v2, field+0" 5B200000
test_vector "${PLUGIN}" "iput-boolean v0, v3, field+0" 5C300000
test_vector "${PLUGIN}" "iput-byte v0, v2, field+1" 5D200100
test_vector "${PLUGIN}" "iput-char v0, v2, field+3" 5E200300
test_vector "${PLUGIN}" "iput-short v1, v2, field+8" 5F210800
