#!/bin/sh
# LGPL - Copyright (C) 2015 pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
NAME="dwarf crash"
BROKEN=
FILE=../../bins/fuzzed/03ff966ecc14f670bafc7b4e560e7c05
#IGNORE_ERR=1
ARGS=
CMDS='?e ok'
EXPECT='ok
'
run_test


