#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

HELLO=../../bins/dex/Hello.dex
HELLOWORLD=../../bins/dex/HelloWorld.dex
HELLOSLACK=../../bins/dex/HelloSlack.dex

NAME='DEX Hello.dex classes'
FILE=${HELLO}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="ic"
EXPECT='0x000001a4 - 0x000001e8 (sz 68) class 0 LHello
0x000001a4 method 0 LHello.method.<init>(Ljava/lang/String;)V
0x000001c0 method 1 LHello.method.main([Ljava/lang/String;)V
0x000001e8 method 2 LHello.method.say()V
'
run_test

NAME='DEX Hello.dex classes quiet'
FILE=${HELLO}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="icq"
EXPECT='0x000001a4 - 0x000001e8 LHello
'
run_test

NAME='DEX HelloWorld.dex symbols, fields and statics'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="isq"
EXPECT='0x00000168 0 LHello.sfield_localVar2:I
0x00000160 0 LHello.ifield_localVar:I
0x00000238 20 LHello.method.<init>()V
0x0000025c 34 LHello.method.main([Ljava/lang/String;)V
0x00000290 0 LHello.method.foo(I)V
0x00000170 0 LWorld.ifield_worldVar:I
0x00000178 0 LWorld.ifield_worldVar2:I
0x000002f4 20 LWorld.method.<init>()V
0x00000318 0 LWorld.method.foo(I)V
0x000000b9 0 imp.Ljava/io/PrintStream.method.println(Ljava/lang/String;)V
0x000000c1 0 imp.Ljava/lang/Integer.method.<init>(I)V
0x000000c9 0 imp.Ljava/lang/Integer.method.toString()Ljava/lang/String;
0x000000d1 0 imp.Ljava/lang/Object.method.<init>()V
0x000000d9 0 imp.Ljava/lang/StringBuilder.method.<init>()V
0x000000e1 0 imp.Ljava/lang/StringBuilder.method.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
0x000000e9 0 imp.Ljava/lang/StringBuilder.method.toString()Ljava/lang/String;
'
run_test

NAME='DEX HelloWorld.dex flags'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="f"
EXPECT='0x00000372 6 str._init_
0x0000037a 6 str.Findus
0x00000382 10 str.Hello.java
0x00000394 7 str.LHello_
0x0000039d 2 str.LL
0x000003a1 7 str.LWorld_
0x000003aa 21 str.Ljava_io_PrintStream_
0x000003c1 19 str.Ljava_lang_Integer_
0x000003d6 18 str.Ljava_lang_Object_
0x000003ea 18 str.Ljava_lang_String_
0x000003fe 25 str.Ljava_lang_StringBuilder_
0x00000419 18 str.Ljava_lang_System_
0x00000430 2 str.VI
0x00000434 2 str.VL
0x00000438 10 str.World.java
0x00000444 19 str._Ljava_lang_String_
0x00000459 6 str.append
0x00000461 3 str.foo
0x00000466 6 str.foo___
0x0000046e 8 str.localVar
0x00000478 9 str.localVar2
0x00000483 4 str.main
0x00000489 3 str.out
0x0000048e 7 str.println
0x00000497 8 str.toString
0x000004a1 8 str.world___
0x000004ab 8 str.worldVar
0x000004b5 9 str.worldVar2
0x0000025c 1 entry0
0x00000000 112 section.header
0x00000070 0 section_end.header
0x00000070 456 section.constpool
0x00000238 0 section_end.constpool
0x00000238 224 section.code
0x00000318 0 section_end.code
0x000003d1 483 section.data
0x000005b4 0 section_end.data
0x00000168 0 sym.LHello.sfield_localVar2:I
0x00000160 0 sym.LHello.ifield_localVar:I
0x00000238 20 sym.LHello.method._init___V
0x0000025c 34 sym.LHello.method.main__Ljava_lang_String__V
0x00000290 0 sym.LHello.method.foo_I_V
0x00000170 0 sym.LWorld.ifield_worldVar:I
0x00000178 0 sym.LWorld.ifield_worldVar2:I
0x000002f4 20 sym.LWorld.method._init___V
0x00000318 0 sym.LWorld.method.foo_I_V
0x000000b9 0 sym.imp.Ljava_io_PrintStream.method.println_Ljava_lang_String__V
0x000000c1 0 sym.imp.Ljava_lang_Integer.method._init__I_V
0x000000c9 0 sym.imp.Ljava_lang_Integer.method.toString__Ljava_lang_String_
0x000000d1 0 sym.imp.Ljava_lang_Object.method._init___V
0x000000d9 0 sym.imp.Ljava_lang_StringBuilder.method._init___V
0x000000e1 0 sym.imp.Ljava_lang_StringBuilder.method.append_Ljava_lang_String__Ljava_lang_StringBuilder_
0x000000e9 0 sym.imp.Ljava_lang_StringBuilder.method.toString__Ljava_lang_String_
0x000001e8 1 class.LHello
0x00000208 1 class.LWorld
'
run_test

NAME='DEX HelloWorld.dex imports'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="ii"
EXPECT='[Imports]
ordinal=000 plt=0x000000b9 bind=NONE type=FUNC name=Ljava/io/PrintStream.method.println(Ljava/lang/String;)V
ordinal=001 plt=0x000000c1 bind=NONE type=FUNC name=Ljava/lang/Integer.method.<init>(I)V
ordinal=002 plt=0x000000c9 bind=NONE type=FUNC name=Ljava/lang/Integer.method.toString()Ljava/lang/String;
ordinal=003 plt=0x000000d1 bind=NONE type=FUNC name=Ljava/lang/Object.method.<init>()V
ordinal=004 plt=0x000000d9 bind=NONE type=FUNC name=Ljava/lang/StringBuilder.method.<init>()V
ordinal=005 plt=0x000000e1 bind=NONE type=FUNC name=Ljava/lang/StringBuilder.method.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
ordinal=006 plt=0x000000e9 bind=NONE type=FUNC name=Ljava/lang/StringBuilder.method.toString()Ljava/lang/String;

7 imports
'
run_test

NAME='DEX HelloWorld.dex exports'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="iE"
EXPECT='[Exports]
vaddr=0x00000238 paddr=0x00000238 ord=002 fwd= sz=20 bind=GLOBAL type=FUNC name=LHello.method.<init>()V
vaddr=0x0000025c paddr=0x0000025c ord=003 fwd= sz=34 bind=GLOBAL type=FUNC name=LHello.method.main([Ljava/lang/String;)V
vaddr=0x00000290 paddr=0x00000290 ord=004 fwd= sz=0 bind=GLOBAL type=METH name=LHello.method.foo(I)V
vaddr=0x000002f4 paddr=0x000002f4 ord=007 fwd= sz=20 bind=GLOBAL type=FUNC name=LWorld.method.<init>()V
vaddr=0x00000318 paddr=0x00000318 ord=008 fwd= sz=0 bind=GLOBAL type=METH name=LWorld.method.foo(I)V

5 exports
'
run_test

NAME='DEX HelloWorld.dex pi command'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="pi 1 @0x25c; pi 1 @0x026a; pi 1 @0x0294"
EXPECT='sget-object v0, Ljava/lang/System;
new-instance v0, LHello;
new-instance v1, Ljava/lang/StringBuilder;
'
run_test

NAME='DEX HelloWorld.dex debug info'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="pd 1 @0x00000290|grep Hello.java; pd 1 @0x000002f4|grep World.java; pd 1 @0x00000318|grep World.java;"
EXPECT='            0x00000290      62000400       sget-object v0, Ljava/lang/System; ; Hello.java:9
            0x000002f4      701008000100   invoke-direct {v1}, Ljava/lang/Object.<init>()V ; 0x8 ; World.java:5
            0x00000318      62000400       sget-object v0, Ljava/lang/System; ; World.java:11
'
run_test

NAME='DEX HelloWorld.dex debug info CL'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=
IGNORE_ERR=1
CMDS="CL @0x00000290; CL @0x000002f4; CL @0x00000318;"
EXPECT='file Hello.java
line 9
file World.java
line 5
file World.java
line 11
'
run_test