#!/bin/sh

# GPL 3+ - Copyright (C) 2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

fuzz_test() {
NAME="DEX fuzz $1"
IGNORE_ERR=1
BROKEN=
FILE=$2
ARGS=
CMDS='Aq'
EXPECT=''
run_test
}

fuzz_test 1 ../../bins/dalvik/fuzz-dex-jox01
fuzz_test 2 ../../bins/dalvik/fuzz-loaduleb.dex
fuzz_test 3 ../../bins/dalvik/fuzz-oobuleb.dex
fuzz_test 4 ../../bins/dalvik/fuzz-rbufneg.dex
fuzz_test 5 ../../bins/dalvik/fuzz-uninitstr.dex
fuzz_test 6 ../../bins/dalvik/fuzz-method.dex

