#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

HELLOWORLD=../../bins/dex/HelloWorld.dex

NAME='DEX HelloWorld.dex dexdump'
FILE=${HELLOWORLD}
ARGS=''
BROKEN=1
IGNORE_ERR=1
CMDS="iHH"
EXPECT="DEX file header:
magic               : 'dex\n035\0'
checksum            : 190ab819
signature           : 86db...7869
file_size           : 1460
header_size         : 112
link_size           : 0
link_off            : 0 (0x000000)
string_ids_size     : 31
string_ids_off      : 112 (0x000070)
type_ids_size       : 11
type_ids_off        : 236 (0x0000ec)
proto_ids_size       : 6
proto_ids_off        : 280 (0x000118)
field_ids_size      : 5
field_ids_off       : 352 (0x000160)
method_ids_size     : 12
method_ids_off      : 392 (0x000188)
class_defs_size     : 2
class_defs_off      : 488 (0x0001e8)
data_size           : 908
data_off            : 552 (0x000228)

Class #0            -
  Class descriptor  : 'LHello;'
  Access flags      : 0x0001 (PUBLIC)
  Superclass        : 'Ljava/lang/Object;'
  Interfaces        -
  Static fields     -
    #0              : (in LHello;)
      name          : 'localVar2'
      type          : 'I'
      access        : 0x0008 (STATIC)
  Instance fields   -
    #0              : (in LHello;)
      name          : 'localVar'
      type          : 'I'
      access        : 0x0000 ()
  Direct methods    -
    #0              : (in LHello;)
      name          : '<init>'
      type          : '()V'
      access        : 0x10001 (PUBLIC CONSTRUCTOR)
      code          -
      registers     : 2
      ins           : 1
      outs          : 1
      insns size    : 10 16-bit code units
      catches       : (none)
      positions     :
        0x0000 line=4
        0x0003 line=5
        0x0006 line=6
        0x0009 line=7
      locals        :
        0x0000 - 0x000a reg=1 this LHello;
    #1              : (in LHello;)
      name          : 'main'
      type          : '([Ljava/lang/String;)V'
      access        : 0x0009 (PUBLIC STATIC)
      code          -
      registers     : 3
      ins           : 1
      outs          : 2
      insns size    : 17 16-bit code units
      catches       : (none)
      positions     :
        0x0000 line=14
        0x0007 line=15
        0x000c line=16
        0x0010 line=17
      locals        :
  Virtual methods   -
    #0              : (in LHello;)
      name          : 'foo'
      type          : '(I)V'
      access        : 0x0001 (PUBLIC)
      code          -
      registers     : 5
      ins           : 2
      outs          : 2
      insns size    : 42 16-bit code units
      catches       : (none)
      positions     :
        0x0000 line=9
        0x0021 line=10
        0x0029 line=11
      locals        :
        0x0000 - 0x002a reg=3 this LHello;
  source_file_idx   : 2 (Hello.java)

Class #1            -
  Class descriptor  : 'LWorld;'
  Access flags      : 0x0001 (PUBLIC)
  Superclass        : 'Ljava/lang/Object;'
  Interfaces        -
  Static fields     -
  Instance fields   -
    #0              : (in LWorld;)
      name          : 'worldVar'
      type          : 'I'
      access        : 0x0000 ()
    #1              : (in LWorld;)
      name          : 'worldVar2'
      type          : 'I'
      access        : 0x0000 ()
  Direct methods    -
    #0              : (in LWorld;)
      name          : '<init>'
      type          : '()V'
      access        : 0x10001 (PUBLIC CONSTRUCTOR)
      code          -
      registers     : 2
      ins           : 1
      outs          : 1
      insns size    : 10 16-bit code units
      catches       : (none)
      positions     :
        0x0000 line=5
        0x0003 line=6
        0x0006 line=7
        0x0009 line=8
      locals        :
        0x0000 - 0x000a reg=1 this LWorld;
  Virtual methods   -
    #0              : (in LWorld;)
      name          : 'foo'
      type          : '(I)V'
      access        : 0x0001 (PUBLIC)
      code          -
      registers     : 5
      ins           : 2
      outs          : 2
      insns size    : 34 16-bit code units
      catches       : (none)
      positions     :
        0x0000 line=11
        0x0021 line=12
      locals        :
        0x0000 - 0x0022 reg=3 this LWorld;
  source_file_idx   : 17 (World.java)
"
run_test