#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='af jmp after ret'
BROKEN=
FILE=../../bins/elf/hello.raw
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=32
e asm.os=linux
e asm.emu=true
e asm.bytes=0
e asm.cmtcol=20
e asm.lines=false
pd 20~write,exit
'
EXPECT='Hello, world!
 0x00000018   int 0x80; 4 = write (1, "Hello, world!..", 14)
 0x00000020   int 0x80; 1 = exit (1)
'
run_test

