#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../bins/pe/test.exe
CMDS='e anal.followdatarefs=true
s 0x401820
af
s 0x401880
fd

'
EXPECT='fcn.00401880
'
run_test
