#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="x86 ref issue"
CMDS='
e asm.bits=64
e asm.arch=x86
wx c7052a44000050000000
ao~^ptr[1]
'
EXPECT='0x00004434
'
run_test
