#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='reference to like mov [0x400000], 0x1234'
BROKEN=
FILE=../../bins/elf/analysis/reference.out
ARGS=
CMDS='
aaa
axt@0x0804a01c
'
EXPECT='data 0x80483ee mov dword [obj.a], 0x1337 in sym.main
'
run_test
