#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../bins/pe/standard.exe
CMDS='aaa
afi @ sub.kernel32.dll_ExitProcess_b2d ~ name

'
EXPECT=' name: sub.kernel32.dll_ExitProcess_b2d
'
run_test
