#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='xbe: corrupted section data'
FILE=../../b/files/xbe/default.xbe
ARGS=''
CMDS="p8 16"
EXPECT='81ec08040000535556576a01e88f0100
'
run_test
