#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='xbe: entrypoint decoding'
BROKEN=
FILE=../../b/files/xbe/default.xbe
ARGS=''
CMDS='ie~addr'
EXPECT='addr=0x00011000 off=0x00001000 baddr=0x00010000
'
run_test


