#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='loading an xbe file'
FILE=../../b/files/xbe/default.xbe
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=
FILE=../../b/files/xbe/default.xbe
ARGS=''
BROKEN=
CMDS='ie~addr'
EXPECT='addr=0x00011000 off=0x00001000 baddr=0x00010000
'
run_test

NAME='corrupted section data'
FILE=../../b/files/xbe/default.xbe
ARGS=''
BROKEN=1
CMDS="p8 16"
EXPECT='81ec08040000535556576a01e88f0100
'
run_test

NAME='section header decoding'
BROKEN=
FILE=../../b/files/xbe/default.xbe
ARGS=''
CMDS='iS~idx'
EXPECT='idx=00 addr=0x00011000 off=0x00001000 sz=1728 vsz=1728 perm=-r-x name=
idx=01 addr=0x000116c0 off=0x00002000 sz=24 vsz=24 perm=-r-- name=
idx=02 addr=0x000116e0 off=0x00003000 sz=28280 vsz=1257188 perm=-rw- name=_
idx=03 addr=0x000145e0 off=0x0000a000 sz=60 vsz=64 perm=-rwx name=_
idx=04 addr=0x00014620 off=0x0000b000 sz=164 vsz=1188 perm=-r-- name=_
'
run_test
