#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


fuzz_test() {
        NAME="MACH0: fuzzed $1"
        FILE=$2
        BROKEN=
        ARGS=
        CMDS="q"
        EXPECT=''
        run_test
}

COUNT=0
for i in ../../bins/xbe/xbe-fuzzed/*; do
                fuzz_test $COUNT $i
done
