#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=malloc://1024
NAME="add comment"
CMDS='
CCa 0x123 hello
C*~?
C*~[3]
'
EXPECT='1
0x00000123
'
run_test
FILE=malloc://1024
NAME="add comment"
CMDS='
CC hello
C*~?
'
EXPECT='1
'
run_test

FILE=malloc://1024
NAME="add comment at"
CMDS='
CCa 8 hello
C*~?
CC*
'
EXPECT='1
"CCu hello" @ 0x00000008
'
run_test
FILE=malloc://1024
NAME="del comment"
CMDS='
CC hello
CC-hello
C*~?
'
EXPECT='0
'
run_test

FILE=malloc://1024
NAME="add two comment"
CMDS='
CC hello @ 0x200
CC world @ 0x400
C*~?
'
EXPECT='2
'
run_test

FILE=malloc://1024
NAME="del comment at address"
CMDS='
CC hello @ 0x200
CC world @ 0x400
CC-@0x400
C*~?
'
EXPECT='1
'
run_test

FILE=malloc://1024
NAME="multiline comment"
CMDS='
CC hello @ 0x200
CC world @ 0x200
C*~?
e asm.profile=simple
e scr.color=false
pd 2 @ 0x200
'
EXPECT='2
   ;      hello
   ;      world
           0x00000200    0000         add [eax], al
           0x00000202    0000         add [eax], al
'
run_test
