#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=malloc://1024
NAME="Cs : convert to string"
CMDS='
w hello
Cs 6
pd 1
'
EXPECT='           0x00000000     .string "hello" ; len=6
'
run_test

FILE=malloc://1024
NAME="Cs : concatenated strings bug"
BROKEN=
CMDS='
w hello\x00world
Cs 6
Cs 6@6
pd 2
'
EXPECT='           0x00000000     .string "hello" ; len=6
           0x00000006     .string "world" ; len=6
'
run_test


FILE=malloc://1024
NAME="Cs : concatenated strings bug"
BROKEN=
CMDS='
w hello\x00world
Cs 6
Cs 6@6
pd 2
'
EXPECT='           0x00000000     .string "hello" ; len=6
           0x00000006     .string "world" ; len=6
'
run_test

FILE=malloc://128
NAME="Cs : string count bug"
CMDS='
w hello
Cs 6
C*~?
'
EXPECT='1
'
run_test

FILE=malloc://128
NAME="Ch : hide bytes in pd"
CMDS='
e scr.color=false
wx 554889e54883c768
Ch 2
pd 2
Ch-
'
EXPECT='           0x00000000 (2 bytes hidden)
           0x00000002    89e5           mov ebp, esp
'
run_test

FILE=malloc://1024
NAME="Ch : add/del hide bytes"
CMDS='
e scr.color=false
wx 554889e54883c768
Ch 2@0x100
C*~?
Ch-@0x100
C*~?
'
EXPECT='1
0
'
run_test
