#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=malloc://1024
NAME="Cs : convert to string"
CMDS='
w hello
Cs 6
pd 1
'
EXPECT='           0x00000000     .string "hello" ; len=6
'
run_test

FILE=malloc://1024
NAME="Cs : concatenated strings bug"
BROKEN=1
CMDS='
w hello\x00world
Cs 6
Cs 6@6
pd 2
'
EXPECT='            0x00000000     .string "hello" ; len=6
          0x00000007     .string "world" ; len=6
'
run_test


FILE=malloc://1024
NAME="Cs : concatenated strings bug"
BROKEN=1
CMDS='
w hello\x00world
Cs 6
Cs 6@6
pd 2
'
EXPECT='            0x00000000     .string "hello" ; len=6
          0x00000007     .string "world" ; len=6
'
run_test

FILE=malloc://128
NAME="Cs : string count bug"
BROKEN=1
CMDS='
w hello
Cs 6
C*~?
'
EXPECT='1
'
run_test


