#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='loading a BIOS file [64k]'
FILE=../../bins/firmware/bios_64k.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_64k.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_64k.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test

NAME='loading a BIOS file [128k]'
FILE=../../bins/firmware/bios_128k.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_128k.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_128k.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test

NAME='loading a BIOS file [256k]'
FILE=../../bins/firmware/bios_256k.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_256k.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_256k.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test

NAME='loading a BIOS file [512k]'
FILE=../../bins/firmware/bios_512k.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_512k.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_512k.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test

NAME='loading a BIOS file [1M]'
FILE=../../bins/firmware/bios_1M.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_1M.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_1M.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test

NAME='loading a BIOS file [2M]'
FILE=../../bins/firmware/bios_2M.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_2M.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_2M.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test

NAME='loading a BIOS file [4M]'
FILE=../../bins/firmware/bios_4M.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_4M.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_4M.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test

NAME='loading a BIOS file [8M]'
FILE=../../bins/firmware/bios_8M.bin
ARGS=''
BROKEN=
CMDS="q!"
EXPECT=''
run_test

NAME='entrypoint decoding'
BROKEN=1
FILE=../../bins/firmware/bios_8M.bin
ARGS=''
CMDS='ie~addr'
EXPECT='vaddr=0x000ffff0 paddr=0x000ffff0 baddr=0x00000000 laddr=0x00000000
'
run_test

NAME='corrupted section data'
FILE=../../bins/firmware/bios_8M.bin
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='ljmp 0xf000:0xffaa
'
run_test


