#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='radiff2 -c'
CMDS='!radiff2 -c ../../bins/other/radiff2/radiff2_c_1 ../../bins/other/radiff2/radiff2_c_2'
BROKEN=
EXPECT='1
'
run_test

NAME='radiff2 -a -O x86'
CMDS='!radiff2 -a x86 -O ../../bins/other/radiff2/radiff2_c_1 ../../bins/other/radiff2/radiff2_c_2'
BROKEN=
EXPECT='0x00000000 91 => 90 0x00000000
'
run_test

#TODO use internal grep ~
NAME='radiff2 -g'
CMDS='!radiff2 -g main ../../bins/other/radiff2/false ../../bins/other/radiff2/true | grep digrap'
BROKEN=
EXPECT='digraph code {
'
run_test

NAME='radiff2 -v~commit?"'
CMDS='!!radiff2 -v~commit?'
BROKEN=1
EXPECT='1
'
run_test

NAME='radiff2 -h~Usage?"'
CMDS='!!radiff2 -h~Usage?'
BROKEN=1
EXPECT='1
'
run_test

