#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='anal vars crash'
FILE=-
ARGS=
CMDS='af
afv-*
afv-*
'
EXPECT=""
run_test

NAME='anal vars crash 2'
FILE=-
ARGS=
CMDS='wx 554889e5534881ec3810000048830c24004881c42010000064488b042528000000488945e831c04885ff4889fb909090909090c3 @ 10
af @ 10
afvn old_1 new_1
'
EXPECT=""
run_test


NAME='afa & afan'
FILE=../bins/efi/bootia32.efi
ARGS=
CMDS='af
afan arg_2 ImageHandle
afan arg_3 SystemTable
afa~?ImageHandle
afa~?SystemTable
'
EXPECT="1
1
"
run_test

NAME='afa* & afan'
FILE=../bins/efi/bootia32.efi
ARGS=
CMDS='af
afan arg_2 ImageHandle
afan arg_3 SystemTable
afa*~?ImageHandle
afa*~?SystemTable
'
EXPECT="1
1
"
run_test

NAME='afa idx... & afan'
FILE=../bins/efi/bootia32.efi
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afa*~ImageHandle
'
EXPECT="afa 8 ImageHandle blah @ 0x10002d8d
"
run_test


NAME='afa-*'
FILE=../bins/efi/bootia32.efi
ARGS=
BROKEN=1
CMDS='af
afa-*
afv-*
afa~?
afv~?
'
EXPECT="0
0
"
run_test
