#!/bin/sh

# GPL 3+ - Copyright (C) 2016 - pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='iphone-arm-esil tests'
FILE=../bins/mach0/FileDP
CMDS='s main
aeim
e asm.emu=true
e asm.emustr=false
pd 4~!--
'
EXPECT='            0x000028ec      b0402de9       push {r4, r5, r7, lr}      ; sp=0x177ff0 
            0x000028f0      08708de2       add r7, sp, 8              ; r7=0x177ff0 
            0x000028f4      05dd4de2       sub sp, sp, 0x140          ; sp=0x177eb0 
            0x000028f8      07d0cde3       bic sp, sp, 7              ; sp=0x177eb0 
'

run_test

NAME='iphone-arm-esil pdsf'
FILE=../bins/mach0/FileDP
BROKEN=
CMDS='s main
e io.sectonly=true
e asm.emu=true
e asm.emustr=true
af
pdsf
'
EXPECT='0x0000290c sym._main
0x00002920 "alloc"
0x00002928 sym.imp.objc_msgSend
0x0000293c "init"
0x00002940 sym.imp.objc_msgSend
0x0000294c "X..."
0x0000294c sym._main
0x0000295c sym.imp.objc_msgSend
0x00002970 sym.imp.objc_msgSend
0x0000299c sym.imp.puts
0x00002988 sym._main
0x000029c8 sym.imp.strcmp
0x000029e0 sym._main
0x000029ec sym._main
0x00002a1c sym.imp.objc_msgSend
0x00002a30 sym._main
0x00002a38 sym.imp.objc_msgSend
0x00002a64 sym.imp.objc_msgSend
0x00002a90 sym.imp.objc_msgSend
0x00002aa4 sym.imp.NSLog
0x00002aa8 sym._main+0x1d0
0x00002ab0 str.File_Not_Found
0x00002ab4 sym.imp.puts
0x000029d8 sym._main
0x00002ac4 sym._main
0x00002ad0 sym._main
0x00002b00 sym.imp.objc_msgSend
0x00002b10 sym._main
0x00002b1c sym.imp.objc_msgSend
0x00002b48 sym.imp.objc_msgSend
0x00002b18 sym._main
0x00002b5c sym._main
0x00002b64 sym.imp.objc_msgSend
0x00002ba4 sym.imp.objc_msgSend
0x00002c00 sym.imp.objc_msgSend
0x00002c54 sym.imp.objc_enumerationMutation;
0x00002ca0 sym.imp.objc_msgSend
0x00002cc0 sym.imp.objc_msgSend
0x00002cec sym.imp.objc_msgSend
0x00002d04 sym.imp.NSLog
0x00002d50 sym.imp.objc_msgSend
0x00002d7c sym._main+0x4a4;
0x00002d84 "/.."
0x00002d88 sym.imp.puts
0x00002abc sym._main
0x00002da0 sym._main
0x00002dac sym.imp.objc_msgSend
0x000029ac sym._main
'
run_test

NAME='sectonly esil stack'
FILE=../bins/mach0/FileDP
CMDS='s main
aeim
e asm.emu=true
e asm.emustr=true
e io.sectonly=false
.ar*
pxW 4 @ sp
e io.sectonly=true
pxW 4 @ sp
S 0x100000 0x100000 983040 983040 stack
pxW 4 @ sp
'
EXPECT='0x00178000 0x00000000 sb
0x00178000 0x00000000 sb
0x00178000 0x00000000 sb
'

run_test

NAME='thumb emulation arm issue'
FILE=../bins/mach0/FileDP
CMDS='e asm.bits=16
aes
e asm.bits'
EXPECT='16
'

run_test
