#!/bin/sh

# GPL 3+ - Copyright (C) 2016 - pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='iphone-arm-esil tests'
FILE=../bins/mach0/FileDP
BROKEN=1
CMDS='s main
aeim
e asm.emu=true
e asm.emustr=false
pd 4~!--
'
EXPECT='            0x000028ec      b0402de9       push {r4, r5, r7, lr}      ; sp=0x177ff0
            0x000028f0      08708de2       add r7, sp, 8              ; r7=0x177ff8
            0x000028f4      05dd4de2       sub sp, sp, 0x140          ; sp=0x177eb0
            0x000028f8      07d0cde3       bic sp, sp, 7              ; sp=0x177eb0
'

run_test

NAME='iphone-arm-esil tests'
FILE=../bins/mach0/FileDP
BROKEN=1
CMDS='s main
e asm.emu=true
e asm.emustr=true
pds
'
EXPECT=''
run_test

NAME='iphone-arm-esil tests'
FILE=../bins/mach0/FileDP
BROKEN=1
CMDS='s main
aeim
e asm.emu=true
e asm.emustr=true
pds
'
EXPECT=''

run_test
