#!/bin/sh

# GPL 3+ - Copyright (C) 2015  ninjahacker

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='cmp neq unchanged zf'
FILE=-
ARGS=
CMDS='
e esil.debug=true
e asm.arch=arm
e asm.bits=16
aei
aeim
aer sp=0x00108000
.aer*
"wa cmp r1, #0x10"
aes
aer?cpsr
'
EXPECT='0x00000000
'
run_test

NAME='cmp neq changed zf'
BROKEN=1
FILE=-
ARGS=
CMDS='
e esil.debug=true
e asm.arch=arm
e asm.bits=16
aei
aeim
aer sp=0x00108000
aer cpsr=0xffffffff
.aer*
"wa cmp r1, #0x10"
aes
aer?cpsr
'
EXPECT='0xbfffffff
'
run_test

NAME='cmp eq unchanged zf'
FILE=-
ARGS=
CMDS='
e esil.debug=true
e asm.arch=arm
e asm.bits=16
aei
aeim
aer sp=0x00108000
aer r1=0x10
aer cpsr=0x80000000
.aer*
"wa cmp r1, #0x10"
aes
aer?cpsr
'
EXPECT='0x80000000
'
run_test

NAME='cmp eq changed zf'
BROKEN=1
FILE=-
ARGS=
CMDS='
e esil.debug=true
e asm.arch=arm
e asm.bits=16
aei
aeim
aer sp=0x00108000
aer r1=0x10
aer cpsr=0x00000000
.aer*
"wa cmp r1, #0x10"
aes
aer?cpsr
'
EXPECT='0x80000000
'
run_test

# load cases

NAME="ldr.w r0, [r0, r1, lsl 2]"
FILE=malloc://0x200
CMDS='
e asm.arch=arm
e asm.bits=16
ar > /dev/null
ar r0=4
ar r1=2
wx 50f82100
wx aaaaaaaabbbbbbbb44332211@4
aes
ar r0
'
EXPECT='0x11223344
'
run_test

# bit fields

NAME="ubfx r2, r0, 8, 8"
FILE=malloc://0x200
CMDS='
e asm.arch=arm
e asm.bits=16
ar > /dev/null
ar r0=0x11223344
wx c0f30722
aes
ar r2
'
EXPECT='0x00000033
'
run_test

