#!/bin/sh

# GPL 3+ - Copyright (C) 2013-2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='udis pae 0xed31'
FILE=-
CMDS='
e asm.arch = x86.udis
pae 0xed31
'
EXPECT='ebp,ebp,^=
'

run_test


NAME='capstone pae 0xed31'
FILE=-
BROKEN=
CMDS='
pae 0xed31
'
EXPECT='ebp,ebp,^=,%z,zf,=,%p,pf,=,0,cf,=,0,of,=,%s,sf,=
'

run_test
