#!/bin/sh

# GPL 3+ - Copyright (C) 2013-2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='add'
FILE=-
ARGS=
CMDS='ae 3,3,+
ae 3,3,-
'
EXPECT='0x6
0x0
'
run_test

NAME='neg'
FILE=-
ARGS=
CMDS='ae 3,3,+,!
ae 3,3,-,!
'
EXPECT='0x0
0x1
'
run_test

NAME='condition'
FILE=-
ARGS=
CMDS='ae 3,?{,0x80,}
'
EXPECT='0x80
'
run_test
