#!/bin/sh

# GPL 3+ - Copyright (C) 2013-2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='add'
FILE=-
ARGS=
CMDS='ae 3,3,+
ae 3,3,-
'
EXPECT='0x6
0x0
'
run_test

NAME='inc/dec'
FILE=-
ARGS=
CMDS='
ae 0xffffffffffffffff,++
ae 3,++
ae 3,--
ae 0,--
'
EXPECT='0x0
0x4
0x2
0xffffffffffffffff
'
run_test

NAME='sub'
FILE=-
ARGS=
CMDS='ae 1,3,-
'
EXPECT='0x2
'
run_test

NAME='subeq'
FILE=-
ARGS=
CMDS='e asm.bits=32
e asm.arch=x86
aei
ae 3,eax,=,1,eax,-=,eax,0,+
'
EXPECT='0x2
'
run_test

NAME='shift-left'
FILE=-
ARGS=
CMDS='"ae 3,1,<<"
"ae 1,3,<<"
'
EXPECT='0x8
0x6
'
run_test

NAME='shift-right'
FILE=-
ARGS=
CMDS='"ae 1,8,>>"
"ae 8,1,>>"
'
EXPECT='0x4
0x0
'
run_test

NAME='sub'
FILE=-
ARGS=
CMDS='ae 3,1,-
'
EXPECT='0xfffffffffffffffe
'
run_test


NAME='neg'
FILE=-
ARGS=
CMDS='ae 3,3,+,!
ae 3,3,-,!
'
EXPECT='0x0
0x1
'
run_test

NAME='condition'
FILE=-
ARGS=
CMDS='ae 3,?{,0x80,}
'
EXPECT='0x80
'
run_test
