#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="add zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 20000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="add a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 20280200
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="add a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 20284300
aes
ar a1
'
EXPECT='0x00000000
'
run_test

NAME="addi zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 05000020
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="addi a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 05000520
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="addi a1, zero, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx fbff0520
aes
ar a1
'
EXPECT='0xfffffffb
'
run_test

NAME="addi a1, 6, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=6
wx fbff4520
aes
ar a1
'
EXPECT='0x00000000
'
run_test

NAME="addu zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 21000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="addu a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 21280200
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="addu a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 21284300
aes
ar a1
'
EXPECT='0x00000004
'
run_test

NAME="addiu zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 05000024
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="addiu a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 05000524
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="addiu a1, zero, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx fbff0524
aes
ar a1
'
EXPECT='0xfffffffb
'
run_test

NAME="addiu a1, 6, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=6
wx fbff4524
aes
ar a1
'
EXPECT='0x00000001
'
run_test

NAME="sub zero, 5, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
ar v1=1
wx 22004300
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="sub a1, 1, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=1
ar v1=5
wx 22284300
aes
ar a1
'
EXPECT='0x00000000
'
run_test

NAME="sub a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 22284300
aes
ar a1
'
EXPECT='0x00000006
'
run_test

NAME="subu a1, 1, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=1
ar v1=5
wx 23284300
aes
ar a1
'
EXPECT='0xfffffffc
'
run_test

NAME="subu a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 23284300
aes
ar a1
'
EXPECT='0xfffffffa
'
run_test

NAME="and a1, 0xFFFFFFFF, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
ar v1=0x10101010
wx 24284300
aes
ar a1
'
EXPECT='0x10101010
'
run_test

NAME="andi a1, 0xFFFFFFFF, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
wx ffff4530
aes
ar a1
'
EXPECT='0x0000ffff
'
run_test

NAME="andi a1, 0xFFFFFFFF, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
wx 01004530
aes
ar a1
'
EXPECT='0x00000001
'
run_test

NAME="or zero, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 25000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="or a1, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 25280200
aes
ar a1
'
EXPECT='0x10101010
'
run_test

NAME="or a1, 0x01010111, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v1=0x01010111
ar v0=0x10101010
wx 25284300
aes
ar a1
'
EXPECT='0x11111111
'
run_test

NAME="ori zero, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0034
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="ori a1, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0534
aes
ar a1
'
EXPECT='0x0000ffff
'
run_test

NAME="ori a1, 0xFFFF0000, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffff0000
wx 01004534
aes
ar a1
'
EXPECT='0xffff0001
'
run_test

NAME="xor zero, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 26000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="xor a1, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 26280200
aes
ar a1
'
EXPECT='0x10101010
'
run_test

NAME="xor a1, 0x01010111, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x01010111
ar v1=0x10101010
wx 26284300
aes
ar a1
'
EXPECT='0x11111101
'
run_test

NAME="xori zero, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0038
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="xori a1, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0538
aes
ar a1
'
EXPECT='0x0000ffff
'
run_test

NAME="xori a1, 0xFFFF0000, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffff0000
wx 01004538
aes
ar a1
'
EXPECT='0xffff0001
'
run_test

NAME="xori a1, 0xFFFF00FF, 0xF1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffff00ff
wx f1004538
aes
ar a1
'
EXPECT='0xffff000e
'
run_test

NAME="nor zero, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 27000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="nor a1, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 27280200
aes
ar a1
'
EXPECT='0xefefefef
'
run_test

NAME="nor a1, 0x10101010, 0xFFFF0000"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
ar v1=0xffff0000
wx 27284300
aes
ar a1
'
EXPECT='0x0000efef
'
run_test

NAME="lh v1, (v0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000000
wx aabbccdd00004384
s 4
aes
ar v1
'
EXPECT='0x0000bbaa
'
run_test

NAME="lh v1, -2(v0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000002
wx aabbccddfeff4384
s 4
aes
ar v1
'
EXPECT='0x0000bbaa
'
run_test

NAME="lh v1, 2(v0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000000
wx aabbccdd02004384
s 4
aes
ar v1
'
EXPECT='0x0000ddcc
'
run_test

NAME="lw v1, (v0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000000
wx aabbccdd112233440000438c
s 8
aes
ar v1
'
EXPECT='0xddccbbaa
'
run_test

NAME="lw v1, -4(v0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000004
wx aabbccdd11223344fcff438c
s 8
aes
ar v1
'
EXPECT='0xddccbbaa
'
run_test

NAME="lw v1, 4(v0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000000
wx aabbccdd112233440400438c
s 8
aes
ar v1
'
EXPECT='0x44332211
'
run_test

NAME="sw v0, 0(v1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x11aa22bb
ar v1=0
s 4
wx 000062ac
aes
p8 4 @ 0
'
EXPECT='bb22aa11
'
run_test

NAME="sw v0, -4(v1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x11aa22bb
ar v1=4
s 4
wx fcff62ac
aes
p8 4 @ 0
'
EXPECT='bb22aa11
'
run_test

NAME="sh v0, 0(v1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x11aa22bb
ar v1=0
wx 00000000000062a4
s 4
aes
p8 4 @ 0
'
EXPECT='bb220000
'
run_test

NAME="sh v0, 2(v1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x11aa22bb
ar v1=0
wx 00000000020062a4
s 4
aes
p8 5 @ 0
'
EXPECT='0000bb2202
'
run_test

NAME="sb v0, 0(v1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x11aa22bb
ar v1=0
wx 00000000000062a0
s 4
aes
p8 4 @ 0
'
EXPECT='bb000000
'
run_test

NAME="sb v0, 3(v1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x11aa22bb
ar v1=0
wx 00000000030062a0
s 4
aes
p8 5 @ 0
'
EXPECT='000000bb03
'
run_test

NAME="sll v0, v0, 16"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x0001ffff
wx 00140200
aes
ar v0
'
EXPECT='0xffff0000
'
run_test

NAME="sllv v0, v0, v1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x0001ffff
ar v1=16
wx 04106200
aes
ar v0
'
EXPECT='0xffff0000
'
run_test

NAME="mult v0, v1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar v1=0x44556677
wx 18004300
aes
ar hi
ar lo
'
EXPECT='0x000492cc
0xffffffffc28637b5
'
run_test

NAME="mult v1, v0"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar v1=0x44556677
wx 18004300
aes
ar hi
ar lo
'
EXPECT='0x000492cc
0xffffffffc28637b5
'
run_test

NAME="mflo v0"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar lo=0xffffffff12345678
wx 12100000
aes
ar v0
'
EXPECT='0x12345678
'
run_test

NAME="mfhi v0"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar hi=0xffffffff12345678
wx 10100000
aes
ar v0
'
EXPECT='0x12345678
'
run_test

NAME="mflo zero"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar lo=0xffffffff12345678
wx 12100000
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="mfhi zero"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar hi=0xffffffff12345678
wx 10100000
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="mtlo v0"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar lo=0xffffffff12345678
wx 13004000
aes
ar lo
'
EXPECT='0x00112233
'
run_test

NAME="mthi v0"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar hi=0xffffffff12345678
wx 11004000
aes
ar hi
'
EXPECT='0x00112233
'
run_test

NAME="mthi v0 (negative)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
ar hi=0xffffffff12345678
wx 11004000
aes
ar hi
'
EXPECT='0xffffffffffffffff
'
run_test

NAME="bne v0, v1, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar v1=0x00112233
wx 0e004314
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="bne v0, v1, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00222233
ar v1=0x00112233
wx 0e004314
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="beq v0, v1, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00222233
ar v1=0x00112233
wx 0e004310
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="beq v0, v1, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00112233
ar v1=0x00112233
wx 0e004310
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="bnez s4, 0xc (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar s4=0x00000000
wx 02008016
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="bnez s4, 0xc (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar s4=0x00112233
wx 02008016
aes
ar pc
'
EXPECT='0x0000000c
'
run_test

NAME="blez v0, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000001
wx 0e004018
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="blez v0, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xfffffffc
wx 0e004018
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="blez zero, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 0e000018
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="bgez v0, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000001
wx 0e004104
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="bgez v0, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xfffffffc
wx 0e004104
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="bgez zero, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 0e000104
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="bltz v0, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000001
wx 0e004004
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="bltz v0, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xfffffffc
wx 0e004004
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="bltz zero, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 0e000004
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="bgtz v0, 0x3c (taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x00000001
wx 0e00401c
aes
ar pc
'
EXPECT='0x0000003c
'
run_test

NAME="bgtz v0, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xfffffffc
wx 0e00401c
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="bgtz zero, 0x3c (not taken)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 0e00001c
aes
ar pc
'
EXPECT='0x00000004
'
run_test

NAME="jal 16"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 0400000c
aes
ar pc
ar ra
'
EXPECT='0x00000010
0x00000008
'
run_test

NAME="jalr t9"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar t9=16
wx 09f82003
aes
ar pc
ar ra
'
EXPECT='0x00000010
0x00000008
'
run_test

NAME="jalr t4, t9"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar t9=16
wx 09602003
aes
ar pc
ar t4
'
EXPECT='0x00000010
0x00000008
'
run_test

NAME="slt s0, v0, v1 (1<2=1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=1
ar v1=2
wx 2a804300
aes
ar s0
'
EXPECT='0x00000001
'
run_test

NAME="slt s0, v0, v1 (0<0=0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0
ar v1=0
wx 2a804300
aes
ar s0
'
EXPECT='0x00000000
'
run_test

NAME="slt s0, v0, v1 (2<1=0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=2
ar v1=1
wx 2a804300
aes
ar s0
'
EXPECT='0x00000000
'
run_test

NAME="slt s0, v0, v1 (-1<1=1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=-1
ar v1=1
wx 2a804300
aes
ar s0
'
EXPECT='0x00000001
'
run_test

NAME="sltu s0, v0, v1 (0xffffffff<1=0)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
ar v1=1
wx 2b804300
aes
ar s0
'
EXPECT='0x00000000
'
run_test

NAME="sltu s0, v0, v1 (0<0xffffffff=1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0
ar v1=0xffffffff
wx 2b804300
aes
ar s0
'
EXPECT='0x00000001
'
run_test

NAME="negu v1, v0 (neg -1 = 1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v1=0
ar v0=-1
wx 23180200
aes
ar v1
'
EXPECT='0x00000001
'
run_test

NAME="negu v1, v0 (neg 1 = -1)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v1=0
ar v0=1
wx 23180200
aes
ar v1
'
EXPECT='0xffffffff
'
run_test

NAME="negu v1, v0 (neg 3497 = -3497)"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v1=0
ar v0=3497
wx 23180200
aes
ar v1
'
EXPECT='0xfffff257
'
run_test