#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="add zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 20000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="add a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 20280200
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="add a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 20284300
aes
ar a1
'
EXPECT='0x00000000
'
run_test

NAME="addi zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 05000020
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="addi a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 05000520
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="addi a1, zero, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx fbff0520
aes
ar a1
'
EXPECT='0xfffffffb
'
run_test

NAME="addi a1, 6, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=6
wx fbff4520
aes
ar a1
'
EXPECT='0x00000000
'
run_test

NAME="addu zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 21000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="addu a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 21280200
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="addu a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 21284300
aes
ar a1
'
EXPECT='0x00000004
'
run_test

NAME="addiu zero, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx 05000024
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="addiu a1, zero, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx 05000524
aes
ar a1
'
EXPECT='0x00000005
'
run_test

NAME="addiu a1, zero, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
wx fbff0524
aes
ar a1
'
EXPECT='0xfffffffb
'
run_test

NAME="addiu a1, 6, -5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=6
wx fbff4524
aes
ar a1
'
EXPECT='0x00000001
'
run_test

NAME="sub zero, 5, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=5
ar v1=1
wx 22004300
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="sub a1, 1, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=1
ar v1=5
wx 22284300
aes
ar a1
'
EXPECT='0x00000000
'
run_test

NAME="sub a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 22284300
aes
ar a1
'
EXPECT='0x00000006
'
run_test

NAME="subu a1, 1, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=1
ar v1=5
wx 23284300
aes
ar a1
'
EXPECT='0xfffffffc
'
run_test

NAME="subu a1, 0xFFFFFFFF, 5"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xFFFFFFFF
ar v1=0x5
wx 23284300
aes
ar a1
'
EXPECT='0xfffffffa
'
run_test

NAME="and a1, 0xFFFFFFFF, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
ar v1=0x10101010
wx 24284300
aes
ar a1
'
EXPECT='0x10101010
'
run_test

NAME="andi a1, 0xFFFFFFFF, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
wx ffff4530
aes
ar a1
'
EXPECT='0x0000ffff
'
run_test

NAME="andi a1, 0xFFFFFFFF, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffffffff
wx 01004530
aes
ar a1
'
EXPECT='0x00000001
'
run_test

NAME="or zero, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 25000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="or a1, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 25280200
aes
ar a1
'
EXPECT='0x10101010
'
run_test

NAME="or a1, 0x01010111, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v1=0x01010111
ar v0=0x10101010
wx 25284300
aes
ar a1
'
EXPECT='0x11111111
'
run_test

NAME="ori zero, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0034
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="ori a1, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0534
aes
ar a1
'
EXPECT='0x0000ffff
'
run_test

NAME="ori a1, 0xFFFF0000, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffff0000
wx 01004534
aes
ar a1
'
EXPECT='0xffff0001
'
run_test

NAME="xor zero, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 26000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="xor a1, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 26280200
aes
ar a1
'
EXPECT='0x10101010
'
run_test

NAME="xor a1, 0x01010111, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x01010111
ar v1=0x10101010
wx 26284300
aes
ar a1
'
EXPECT='0x11111101
'
run_test

NAME="xori zero, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0038
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="xori a1, zero, 0xFFFF"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
wx ffff0538
aes
ar a1
'
EXPECT='0x0000ffff
'
run_test

NAME="xori a1, 0xFFFF0000, 1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffff0000
wx 01004538
aes
ar a1
'
EXPECT='0xffff0001
'
run_test

NAME="xori a1, 0xFFFF00FF, 0xF1"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0xffff00ff
wx f1004538
aes
ar a1
'
EXPECT='0xffff000e
'
run_test

NAME="nor zero, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 27000200
aes
ar zero
'
EXPECT='0x00000000
'
run_test

NAME="nor a1, zero, 0x10101010"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
wx 27280200
aes
ar a1
'
EXPECT='0xefefefef
'
run_test

NAME="nor a1, 0x10101010, 0xFFFF0000"
FILE=malloc://0x200
CMDS='
e asm.arch=mips
e asm.bits=32
ar > /dev/null
ar v0=0x10101010
ar v1=0xffff0000
wx 27284300
aes
ar a1
'
EXPECT='0x0000efef
'
run_test

