#!/bin/sh

# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='reg size bitmask'
FILE=-
ARGS=
CMDS='
e esil.debug=true
e asm.arch=x86
e asm.bits=64
aei
aeim
aer rsp=0x00108000
.dr*
aer rdi=0xFFFFFFFFFFFFFFFF
ae rdi,rsp,=[8]
?v [rsp]
?v [rsp+4]
?v [rsp+8]
'
EXPECT='0xffffffff
0xffffffff
0x0
'
run_test

NAME='2step push x86-32'
FILE=-
ARGS=
CMDS='
e esil.debug=true
e asm.arch=x86
e asm.bits=32
aei
aeim
aer esp=0x00108000
.aer*
"wa mov eax, 0x1234;push eax"
2aes
.aer*
aer?esp
?v [esp]
'
EXPECT='0x00107ffc
0x1234
'
run_test

NAME='dh esil'
BROKEN=1
FILE=-
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=32
dh esil
aei
aeim
dr esp=0x00108000
.dr*
"wa mov eax, 0x1234;push eax"
ds 2
.dr*
dr?esp
?v [esp]
'
EXPECT='0x00107ffc
0x1234
'
run_test

