#!/bin/sh

# GPL 3+ - Copyright (C) 2015 pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='aecs'
FILE=-
ARGS='-ax86 -b32'
IGNORE_ERR=0
CMDS='
"wa mov eax,33;int 0x80"
aecs
'
EXPECT_ERR='syscall at 0x00000005
'
run_test

