#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="esil x86-64"
CMDS='
?e
e asm.arch=x86
e asm.bits=64
wx 488d7768
ao~opcode,esil
'
EXPECT='
opcode: lea rsi, [rdi + 0x68]
esil: 0x68,rdi,+,rsi,=
'
run_test

NAME="esil x86-64"
CMDS='
?e
e asm.arch=x86
e asm.bits=64
wx 488dbdc0fbffff
ao~opcode,esil
'
EXPECT='
opcode: lea rdi, [rbp - 0x440]
esil: 0x440,rbp,-,rdi,=
'

run_test

NAME="esil x86-64"
CMDS='
?e
e asm.arch=x86
e asm.bits=64
wx c705dd40000001000000
ao~opcode,esil
'
EXPECT='
opcode: mov dword [rip + 0x40dd], 1
esil: 1,0x40e1,rip,+,=[4]
'

NAME="eax/rax"
BROKEN=
CMDS='e asm.bits=64
wa mov eax, 4
e asm.esil=true
pd 1
'
EXPECT='           0x00000000    b804000000     4,rax,=
'

run_test
