#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='endian tests: wv'
FILE=-
BROKEN=1
CMDS="e cfg.bigendian=false
e asm.bits=32
wv4 3
p8 4
e cfg.bigendian=true
wv4 3
p8 4
"
EXPECT="03000000
00000003
"
run_test

