#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

fuzz_test() {
NAME="Other Fuzz $1"
IGNORE_ERR=1
BROKEN=
FILE=$1
ARGS=
CMDS='aa ; q'
EXPECT=''
run_test
}

for fuzzed_file in ../../bins/fuzzed/*
do
  fuzz_test "$fuzzed_file"
done
