#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='SEGA Master System fuzzed ROM'
FILE=../../bins/sms/0d27cc08febd29907df68ad6c6d5418f
ARGS=''
CMDS="q!"
EXPECT=''
IGNORE_ERR=1
run_test
