#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
NAME='afA + pdf'
FILE=../../bins/elf/fast
ARGS=
BROKEN=1
CMDS='s sym.fastcaslled
af+ 0x804841b 0x3b sym.fastcaslled
afC fastcall
afA 0 var_a int
afA 1 var_b int
afA 0x8 var_c int
afA 0xc var_d int
pd 1
s 0x0804843b
pd 1
'
EXPECT="/ (fcn) sym.fastcaslled 59
|           ; arg int var_a @ ecx
|           ; arg int var_b @ edx
|           ; arg int var_c @ ebp+0x8
|           ; arg int var_d @ ebp+0xc
|           0x0804841b      55             push ebp
|           0x0804843b      ff7508         push dword [ebp + var_c]
"
run_test

NAME='anal  vars afA,afA*,afAj'
FILE=../../bins/elf/fast
ARGS=
CMDS='s sym.fastcaslled
af+ 0x804841b 0x3b sym.fastcaslled
afA 0 a int
afA 1 b int
afA 0x8 c int
afA 0xc d int
afA
afA*
afAj
'
EXPECT='arg int a @ ecx
arg int b @ edx
arg int c @ ebp+0x8
arg int d @ ebp+0xc
afA 0 a int @ 0x804841b
afA 1 b int @ 0x804841b
afA 8 c int @ 0x804841b
afA 12 d int @ 0x804841b
[{"name":"a","kind":"arg","type":"int","ref":"ecx"},{"name":"b","kind":"arg","type":"int","ref":"edx"},{"name":"c","kind":"arg","type":"int","ref":"ebp+0x8"},{"name":"d","kind":"arg","type":"int","ref":"ebp+0xc"}]
'
run_test

NAME='anal vars crash'
FILE=-
ARGS=
CMDS='af
afv-*
afv-*
'
EXPECT=""
run_test

NAME='anal vars crash 2'
FILE=-
ARGS=
CMDS='wx 554889e5534881ec3810000048830c24004881c42010000064488b042528000000488945e831c04885ff4889fb909090909090c3 @ 10
af @ 10
afvn old_1 new_1
'
EXPECT=""
run_test


NAME='afa & afan'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afan arg_8h ImageHandle
afan arg_ch SystemTable
afa~?ImageHandle
afa~?SystemTable
'
EXPECT="1
1
"
run_test

NAME='afa* & afan'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afan arg_8h ImageHandle
afan arg_ch SystemTable
afa*~?ImageHandle
afa*~?SystemTable
'
EXPECT="1
1
"
run_test

NAME='afa idx... & afan'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afa*~ImageHandle
'
EXPECT="afa 8 ImageHandle blah @ 0x10002d8d
"
run_test

NAME='afaj'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afaj~?ImageHandle
'
EXPECT="1
"
run_test

NAME='afa-ArgName'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afa-ImageHandle
afa~?ImageHandle
'
EXPECT="0
"
run_test

NAME='afa-IDX'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afa-0x8
afa~?ImageHandle
'
EXPECT="0
"
run_test

NAME='afv & afvn'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afvn local_0 blah
afv~?blah
'
EXPECT="1
"
run_test

NAME='afv & afvn'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afvn local_0 blah
afvj~?blah
'
EXPECT="1
"
run_test

NAME='afv idx & afv*'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afv 0 blah typeR @ 0x10002d8d
afv*~?blah
afv*~?typeR
'
EXPECT="1
1
"
run_test

NAME='afv-name'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afv 0 blah typeR @ 0x10002d8d
afv-blah
afv~?blah
'
EXPECT="0
"
run_test

NAME='afv-idx'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afv 0 blah typeR @ 0x10002d8d
afv-0
afv~?blah
'
EXPECT="0
"
run_test

NAME='afa-* afv-*'
FILE=../../bins/efi/bootia32.efi
ARGS=
BROKEN=
CMDS='af
afa-*
afv-*
afa~?
afv~?
'
EXPECT="0
0
"
run_test

#TODO AFAG AFAS AFVG AFVS

NAME='anal vars count'
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
CMDS='af
afv~?
'
EXPECT="14
"
run_test

NAME='anal vars retype'
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
CMDS='af
afvt local_30h char
afv~l_30h
'
EXPECT="var char local_30h @ rbp-0x30
"
run_test

NAME='anal vars rename'
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
CMDS='af
afvn local_30h newname
afv~newname
'
EXPECT="var int newname @ rbp-0x30
"
run_test
