#!/bin/sh
# GPL 3+ - Copyright (C) 2015  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
NAME='afCa for fastcall with no esp vars'
FILE=../../bins/elf/fast
ARGS=
CMDS='aa
s sym.fastcaslled
afC fastcall
afC
afCa
pdf
'
EXPECT='fastcall
/ (fcn) sym.fastcaslled 59
|           ; arg int arg_ecx @ ecx
|           ; arg int arg_edx @ edx
|           ; arg int arg_8h @ ebp+0x8
|           ; arg int arg_ch @ ebp+0xc
|           ; var int local_ch @ ebp-0xc
|           ; var int local_10h @ ebp-0x10
|           ; var int local_1ch @ ebp-0x1c
|           ; var int local_20h @ ebp-0x20
|           ; CALL XREF from 0x080484c7 (sym.main)
|           0x0804841b      55             push ebp
|           0x0804841c      89e5           mov ebp, esp
|           0x0804841e      83ec28         sub esp, 0x28
|           0x08048421      894de4         mov dword [ebp - local_1ch], ecx
|           0x08048424      8955e0         mov dword [ebp - local_20h], edx
|           0x08048427      8b55e4         mov edx, dword [ebp - local_1ch]
|           0x0804842a      8b45e0         mov eax, dword [ebp - local_20h]
|           0x0804842d      01d0           add eax, edx
|           0x0804842f      8945f4         mov dword [ebp - local_ch], eax
|           0x08048432      8b45e0         mov eax, dword [ebp - local_20h]
|           0x08048435      2b450c         sub eax, dword [ebp + arg_ch]
|           0x08048438      8945f0         mov dword [ebp - local_10h], eax
|           0x0804843b      ff7508         push dword [ebp + arg_8h]
|           0x0804843e      ff75f0         push dword [ebp - local_10h]
|           0x08048441      ff75f4         push dword [ebp - local_ch]
|           0x08048444      6874850408     push str._i__i__i_n ; str._i__i__i_n ; "%i %i %i." @ 0x8048574
|           0x08048449      e8a2feffff     call sym.imp.printf
|           0x0804844e      83c410         add esp, 0x10
|           0x08048451      90             nop
|           0x08048452      c9             leave
\           0x08048453      c20800         ret 8
'
run_test
NAME='afCa for cdecl/stdcall with no esp vars'
FILE=../../bins/elf/fast
ARGS=
CMDS='aa
s sym.nonfastcaslled
afC
afCa
pdf
'
EXPECT='cdecl
/ (fcn) sym.nonfastcaslled 51
|           ; arg int arg_8h @ ebp+0x8
|           ; arg int arg_ch @ ebp+0xc
|           ; arg int arg_10h @ ebp+0x10
|           ; arg int arg_14h @ ebp+0x14
|           ; var int local_ch @ ebp-0xc
|           ; var int local_10h @ ebp-0x10
|           ; CALL XREF from 0x080484db (sym.main)
|           0x08048456      55             push ebp
|           0x08048457      89e5           mov ebp, esp
|           0x08048459      83ec18         sub esp, 0x18
|           0x0804845c      8b5508         mov edx, dword [ebp + arg_8h] ; [0x8:4]=0
|           0x0804845f      8b450c         mov eax, dword [ebp + arg_ch] ; [0xc:4]=0
|           0x08048462      01d0           add eax, edx
|           0x08048464      8945f4         mov dword [ebp - local_ch], eax
|           0x08048467      8b450c         mov eax, dword [ebp + arg_ch] ; [0xc:4]=0
|           0x0804846a      2b4514         sub eax, dword [ebp + arg_14h]
|           0x0804846d      8945f0         mov dword [ebp - local_10h], eax
|           0x08048470      ff7510         push dword [ebp + arg_10h]
|           0x08048473      ff75f0         push dword [ebp - local_10h]
|           0x08048476      ff75f4         push dword [ebp - local_ch]
|           0x08048479      6874850408     push str._i__i__i_n ; str._i__i__i_n ; "%i %i %i." @ 0x8048574
|           0x0804847e      e86dfeffff     call sym.imp.printf
|           0x08048483      83c410         add esp, 0x10
|           0x08048486      90             nop
|           0x08048487      c9             leave
\           0x08048488      c3             ret
'
run_test
NAME='afA + pdf'
FILE=../../bins/elf/fast
ARGS=
CMDS='s sym.fastcaslled
af+ 0x804841b 0x3b sym.fastcaslled
afC fastcall
afA 0 var_a int
afA 1 var_b int
afA 0x8 var_c int
afA 0xc var_d int
pd 1
'
EXPECT="/ (fcn) sym.fastcaslled 59
|           ; arg int var_a @ ecx
|           ; arg int var_b @ edx
|           ; arg int var_c @ ebp+0x8
|           ; arg int var_d @ ebp+0xc
|           0x0804841b      55             push ebp
"
run_test

NAME='anal  vars afA,afA*,afAj'
FILE=../../bins/elf/fast
ARGS=
CMDS='s sym.fastcaslled
af+ 0x804841b 0x3b sym.fastcaslled
afA 0 a int
afA 1 b int
afA 0x8 c int
afA 0xc d int
afA
afA*
afAj
'
EXPECT='arg int a @ ecx
arg int b @ edx
arg int c @ ebp+0x8
arg int d @ ebp+0xc
afA 0 a int @ 0x804841b
afA 1 b int @ 0x804841b
afA 8 c int @ 0x804841b
afA 12 d int @ 0x804841b
[{"name":"a","kind":"arg","type":"int","ref":"ecx"},{"name":"b","kind":"arg","type":"int","ref":"edx"},{"name":"c","kind":"arg","type":"int","ref":"ebp+0x8"},{"name":"d","kind":"arg","type":"int","ref":"ebp+0xc"}]
'
run_test

NAME='anal vars crash'
FILE=-
ARGS=
CMDS='af
afv-*
afv-*
'
EXPECT=""
run_test

NAME='anal vars crash 2'
FILE=-
ARGS=
CMDS='wx 554889e5534881ec3810000048830c24004881c42010000064488b042528000000488945e831c04885ff4889fb909090909090c3 @ 10
af @ 10
afvn old_1 new_1
'
EXPECT=""
run_test


NAME='afa & afan'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afan arg_8h ImageHandle
afan arg_ch SystemTable
afa~?ImageHandle
afa~?SystemTable
'
EXPECT="1
1
"
run_test

NAME='afa* & afan'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afan arg_8h ImageHandle
afan arg_ch SystemTable
afa*~?ImageHandle
afa*~?SystemTable
'
EXPECT="1
1
"
run_test

NAME='afa idx... & afan'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afa*~ImageHandle
'
EXPECT="afa 8 ImageHandle blah @ 0x10002d8d
"
run_test

NAME='afaj'
FILE=../../bins/efi/bootia32.efi
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afaj~?ImageHandle
'
EXPECT="1
"
run_test

NAME='afa-ArgName'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afa-ImageHandle
afa~?ImageHandle
'
EXPECT="0
"
run_test

NAME='afa-IDX'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afa 8 ImageHandle blah @ 0x10002d8d
afa-0x8
afa~?ImageHandle
'
EXPECT="0
"
run_test

NAME='afv & afvn'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afvn local_0 blah
afv~?blah
'
EXPECT="1
"
run_test

NAME='afv & afvn'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afvn local_0 blah
afvj~?blah
'
EXPECT="1
"
run_test

NAME='afv idx & afv*'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afv 0 blah typeR @ 0x10002d8d
afv*~?blah
afv*~?typeR
'
EXPECT="1
1
"
run_test

NAME='afv-name'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afv 0 blah typeR @ 0x10002d8d
afv-blah
afv~?blah
'
EXPECT="0
"
run_test

NAME='afv-idx'
FILE=../../bins/efi/bootia32.efi
BROKEN=
ARGS=
CMDS='af
afv 0 blah typeR @ 0x10002d8d
afv-0
afv~?blah
'
EXPECT="0
"
run_test

NAME='afa-* afv-*'
FILE=../../bins/efi/bootia32.efi
ARGS=
BROKEN=
CMDS='af
afa-*
afv-*
afa~?
afv~?
'
EXPECT="0
0
"
run_test

#TODO AFAG AFAS AFVG AFVS

NAME='anal vars count'
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
CMDS='af
afv~?
'
EXPECT="14
"
run_test

NAME='anal vars retype'
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
CMDS='af
afvt local_30h char
afv~l_30h
'
EXPECT="var char local_30h @ rbp-0x30
"
run_test

NAME='anal vars rename'
FILE=../../bins/mach0/ls-osx-x86_64
ARGS=
CMDS='af
afvn local_30h newname
afv~newname
'
EXPECT="var int newname @ rbp-0x30
"
run_test
