#!/bin/sh
# LGPL - Copyright (C) 2014-2015 Maijin, pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="axt udis86"
BROKEN=
FILE=../../bins/elf/main
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86.udis
e anal.arch = x86.udis
e scr.color = false
e scr.wheel = false
aa
axt @ str.Hello_World'
EXPECT='data 0x40050a mov edi, str.Hello_World in sym.main
'
run_test

NAME="axt capstone x86"
BROKEN=
FILE=../../bins/elf/main
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86
e anal.arch = x86
e scr.color=false
e scr.wheel = false
aa
axt @ str.Hello_World'
EXPECT='data 0x40050a mov edi, str.Hello_World in sym.main
'
run_test


NAME="axt capstone x86: IOLI0"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x00
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86
e anal.arch = x86
e scr.color=false
e scr.wheel = false
aa
axt @ str.Password:'
EXPECT='data 0x804843c mov dword [esp], str.Password: in sym.main
'
run_test

NAME="axt capstone x86: IOLI7 aa"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x07
IGNORE_ERR=1
ARGS=
CMDS='
aaa
axt @ sym.imp.exit'
EXPECT='call 0x804853d call sym.imp.exit in sub.printf_524
call 0x80485ab call sym.imp.exit in sub.sscanf_542
call 0x804866f call sym.imp.exit in sub.strlen_5b9
'
run_test

NAME="axt capstone x86: IOLI7 aa"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x07
IGNORE_ERR=1
ARGS=
CMDS='
aaaa
axt @ sym.imp.exit'
EXPECT='call 0x804853d call sym.imp.exit in sub.printf_524
call 0x80485ab call sym.imp.exit in sub.sscanf_542
call 0x804866f call sym.imp.exit in sub.strlen_5b9
'
run_test

NAME="axt respect relsub"
BROKEN=1
FILE=../../bins/pe/ibknoreloc64.exe
IGNORE_ERR=1
ARGS=
CMDS='aaa
e asm.relsub=false
axt @ sym.imp.msvcrt.dll_printf
e asm.relsub=true
axt @ sym.imp.msvcrt.dll_printf
'
EXPECT='call 0xffffffffffff100a call qword [rip + 0xd8] in entry0
call 0xffffffffffff100a call qword [sym.imp.msvcrt.dll_printf] in entry0
'
run_test

NAME="axt udis86: IOLI0"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x00
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86.udis
e anal.arch = x86.udis
e scr.color=false
e scr.wheel = false
aa
axt @ str.Password:'
EXPECT='data 0x804843c mov dword [esp], str.Password: in sym.main
'
run_test

NAME="ax-"
BROKEN=
FILE=-
IGNORE_ERR=1
ARGS=
CMDS='ax 10 20
ax
ax-10 20
ax
'
EXPECT='types=code.jmp,code.call,data.mem,data.string
ref.unk.0x14=0xa
xref.unk.0xa=0x14
types=code.jmp,code.call,data.mem,data.string
'
run_test

NAME="ax-@"
BROKEN=
FILE=-
IGNORE_ERR=1
ARGS=
CMDS='s 20
ax 10
ax
ax-10
ax
'
EXPECT='types=code.jmp,code.call,data.mem,data.string
ref.unk.0x14=0xa
xref.unk.0xa=0x14
types=code.jmp,code.call,data.mem,data.string
'
run_test

NAME="ax-*"
BROKEN=
FILE=-
IGNORE_ERR=1
ARGS=
CMDS='ax 10
ax
ax-*
ax
'
EXPECT='types=code.jmp,code.call,data.mem,data.string
ref.unk.0x0=0xa
xref.unk.0xa=0
types=code.jmp,code.call,data.mem,data.string
'

NAME="axt unknown function"
BROKEN=
FILE=../../bins/pe/lab11.malware
IGNORE_ERR=1
ARGS=
CMDS='aaa
axt fcn.00401270
'
EXPECT='call 0x401a1d call fcn.00401270 in unknown function
'



run_test
