#!/bin/sh
# LGPL - Copyright (C) 2014-2015 Maijin, pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="axt udis86"
BROKEN=
FILE=../../bins/elf/main
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86.udis
e anal.arch = x86.udis
e scr.color = false
e scr.wheel = false
aa
axt @ str.Hello_World'
EXPECT='d 0x40050a mov edi, str.Hello_World
'
run_test

NAME="axt capstone x86"
BROKEN=
FILE=../../bins/elf/main
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86
e anal.arch = x86
e scr.color=false
e scr.wheel = false
aa
axt @ str.Hello_World'
EXPECT='d 0x40050a mov edi, str.Hello_World
'
run_test


NAME="axt capstone x86: IOLI0"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x00
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86
e anal.arch = x86
e scr.color=false
e scr.wheel = false
aa
axt @ str.Password:'
EXPECT='d 0x804843c mov dword [esp], str.Password:
'
run_test

NAME="axt udis86: IOLI0"
BROKEN=
FILE=../../bins/elf/ioli/crackme0x00
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch = x86.udis
e anal.arch = x86.udis
e scr.color=false
e scr.wheel = false
aa
axt @ str.Password:'
EXPECT='d 0x804843c mov dword [esp], str.Password:
'
run_test
