#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="mips invalid asm"
BROKEN=1
CMDS='
e asm.arch=mips
e asm.bits=32
wa addiu a0, a1, a2
pi 1 
wa addiu a1, a2, 8
pi 1
'
EXPECT='nop
addiu a1, a2, 8
'

run_test
