#!/bin/bash
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

test_msp430() {
NAME="msp430:${2}"
FILE=malloc://8
ARGS="-w -a msp430"
CMDS='wx'${1}'
pi 1
'
EXPECT="${2}
"
run_test
}

BROKEN=1

test_msp430 3041 "ret"

test_msp430 fb903b000000 "cmp.b #0x3b, 0x0(r11)"
