#!/bin/sh

# GPL 3+ - Copyright (C) 2014  pancake

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='cmp data'
BROKEN=
FILE=-
ARGS=
CMDS='b 16
wx 41
e scr.null=1
cx 41 2>/dev/null
e scr.null=0
?? ?e thats fine
e scr.null=1
cx 11 2>/dev/null
e scr.null=0
?? ?e thats wrong
'
EXPECT='thats fine
'
run_test

