#!/bin/sh
# GPL 3+ - Copyright (C) 2014  Maijin
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='rabin -k file'
BROKEN=
FILE=../../bins/elf/hello-linux-x86_64
ARGS=
CMDS='!rabin2 -k ${FILE}'
EXPECT=''
EXPECT_ERR="r_core: Cannot open file
"
run_test

