#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

set_test_params() {
NAME="${1}: [${2}]"
FILE=malloc://32
BROKEN=${5}
CMDS='
e asm.arch='${1}'
e asm.bits=32
wx '${3}'
pi 1
'
EXPECT="${4}
"
}

for ARCH in arm arm.cs arm.winedbg; do

set_test_params "${ARCH}" "ADDEQ r1, r1, r0" 00108100 "addeq r1, r1, r0"
run_test

set_test_params "${ARCH}" "ADDEQ r1, r1, r2, lsl 2" 02118100 "addeq r1, r1, r2, lsl 2"
run_test

set_test_params "${ARCH}" "ADDNE r1, r1, ip" 0c108110 "addne r1, r1, ip"
run_test

set_test_params "${ARCH}" "ADDNE r1, r1, r0, lsl 2" 00118110 "addne r1, r1, r0, lsl 2"
run_test

set_test_params "${ARCH}" "ANDEQ r0, r0, 1" 01000002 "andeq r0, r0, 1"
run_test

set_test_params "${ARCH}" "ANDEQ r3, r5 -2147483648" 02310502 "andeq r3, r5, -2147483648"
run_test

set_test_params "${ARCH}" "ANDNE r3, r3, r2" 02300310 "andne r3, r3, r2"
run_test

set_test_params "${ARCH}" "ANDNE ip, ip, r7" 07c00c10 "andne ip, ip, r7"
run_test

set_test_params "${ARCH}" "ASREQ r0, ip, 31" cc0fa001 "asreq r0, ip, 31"
run_test

set_test_params "${ARCH}" "ASRNE r0, r4, 31" c40fa011 "asrne r0, r4, 31"
run_test

set_test_params "${ARCH}" "BEQ 8" 0000000a "beq 0x00000008"
run_test

set_test_params "${ARCH}" "BICEQ r3, r3, 7" 0730c303 "biceq r3, r3, 7"
run_test

set_test_params "${ARCH}" "BXEQ lr" 1eff2f01 "bxeq lr"
run_test

set_test_params "${ARCH}" "BXNE lr" 1eff2f11 "bxne lr"
run_test

set_test_params "${ARCH}" "CLZNE r5, sl" 1a5f6f11 "clzne r5, sl"
run_test

set_test_params "${ARCH}" "CMPEQ sl, r4" 40005a01 "cmpeq sl, r4"
run_test

set_test_params "${ARCH}" "CMPNE r7, r6" 06005711 "cmpne r7, r6"
run_test

set_test_params "${ARCH}" "EOREQ r2, r2, 1" 01202202 "eoreq r2, r2, 1"
run_test

set_test_params "${ARCH}" "EORNE r0, r0, r3" 03002010 "eorne r0, r0, r3"
run_test

set_test_params "${ARCH}" "EORNE r0, r0, r3, lsr 24" 230c2010 "eorne r0, r0, r3, lsr 24"
run_test

set_test_params "${ARCH}" "LDMDBEQ r2, {r0, r1}" 03001209 "ldmdbeq r2, {r0, r1}"
run_test

set_test_params "${ARCH}" "LDMEQ r3, {r0, r1, r2, r3}" 0f009308 "ldmeq r3, {r0, r1, r2, r3}"
run_test

set_test_params "${ARCH}" "LDMEQ r5, {r0, r1, r2}" 07009508 "ldmeq r5, {r0, r1, r2}"
run_test

set_test_params "${ARCH}" "LDMEQ r6, {r0, r1}" 03009608 "ldmeq r6, {r0, r1}"
run_test

set_test_params "${ARCH}" "LDRBEQ r5, [r7, -1]" 01505705 "ldrbeq r5, [r7, -1]"
run_test

set_test_params "${ARCH}" "ldrdne r2, [r3, ip]" dc208311 "ldrdne r2, [r3, ip]"
run_test

set_test_params "${ARCH}" "LDREQ r0, [fp, -180]" b4001b05 "ldreq r0, [fp, -180]"
run_test

set_test_params "${ARCH}" "LDRHEQ r0, [r3, r0]" b0009301 "ldrheq r0, [r3, r0]"
run_test

set_test_params "${ARCH}" "LSLNE r1, r1, 2" 0111a011 "lslne r1, r1, 2"
run_test

set_test_params "${ARCH}" "LSREQ r0, r0, 16" 2008a001 "lsreq r0, r0, 16"
run_test

set_test_params "${ARCH}" "LSRNE r0, r0, 9" a004a011 "lsrne r0, r0, 9"
run_test

set_test_params "${ARCH}" "MLAEQ r7, r5, r7, r0" 95072700 "mlaeq r7, r5, r7, r0"
run_test

set_test_params "${ARCH}" "MLANE r3, r1, r3, r2" 91232310 "mlane r3, r1, r3, r2"
run_test

set_test_params "${ARCH}" "MOVEQ r0, sl" 0a00a001 "moveq r0, sl"
run_test

set_test_params "${ARCH}" "MOVNE r0, r9" 0900a011 "movne r0, r9"
run_test

set_test_params "${ARCH}" "MULNE r3, r3, r0" 93000310 "mulne r3, r3, r0"
run_test

set_test_params "${ARCH}" "MVNEQ r0, 21" 1500e003 "mvneq r0, 21"
run_test

set_test_params "${ARCH}" "MVNEQ r0, -2147483648" 0201e003 "mvneq r0, -2147483648"
run_test

set_test_params "${ARCH}" "ORREQ r5, r5, r3" 03508501 "orreq r5, r5, r3"
run_test

set_test_params "${ARCH}" "ORREQ r6, r6, r2, lsr 1" a2608601 "orreq r6, r6, r2, lsr 1"
run_test

set_test_params "${ARCH}" "ORREQ r3, r3, -2147483648" 02318303 "orreq r3, r3, -2147483648"
run_test

set_test_params "${ARCH}" "ORRNE r0, r0, r1, lsl ip" 110c8011 "orrne r0, r0, r1, lsl ip"
run_test

set_test_params "${ARCH}" "ORRNE r1, r1, r3" 03108111 "orrne r1, r1, r3"
run_test

set_test_params "${ARCH}" "POPEQ {pc} ; (LDREQQ pc, [sp], 4)" 04f09d04 "popeq {pc}  ; (ldreq pc, [sp], 4)"
run_test

set_test_params "${ARCH}" "POPEQ {r4, pc}" 1080bd08 "popeq {r4, pc}"
run_test

set_test_params "${ARCH}" "POPEQ {r4, r5, pc}" 3080bd08 "popeq {r4, r5, pc}"
run_test

set_test_params "${ARCH}" "POPEQ {r3, r4, r5, pc}" 3880bd08 "popeq {r3, r4, r5, pc}"
run_test

set_test_params "${ARCH}" "POPEQ {r4, r5, r6, r7, pc}" f080bd08 "popeq {r4, r5, r6, r7, pc}"
run_test

set_test_params "${ARCH}" "POPEQ {r3, r4, r5, r6, r7, pc}" f880bd08 "popeq {r3, r4, r5, r6, r7, pc}"
run_test

set_test_params "${ARCH}" "POPEQ {r3, r4, r5, r6, r7, r8, sl, pc}" f885bd08 "popeq {r3, r4, r5, r6, r7, r8, sl, pc}"
run_test

set_test_params "${ARCH}" "POPEQ {r3, r4, r5, r6, r7, r8, r9, sl, fp, pc}" f88fbd08 "popeq {r3, r4, r5, r6, r7, r8, r9, sl, fp, pc}"
run_test

set_test_params "${ARCH}" "REVEQ r3, r3" 333fbf06 "reveq r3, r3"
run_test

set_test_params "${ARCH}" "RSBEQ ip, r1, r7" 07c06100 "rsbeq ip, r1, r7"
run_test

set_test_params "${ARCH}" "RSBNE r6, r0, r6" 06606010 "rsbne r6, r0, r6"
run_test

set_test_params "${ARCH}" "STMEQ r0, {r2, r3}" 0c008008 "stmeq r0, {r2, r3}"
run_test

set_test_params "${ARCH}" "STMEQ ip, {r0, r1, r2}" 07008c08 "stmeq ip, {r0, r1, r2}"
run_test

set_test_params "${ARCH}" "STMEQ ip, {r0, r1, r2, r3}" 0f008c08 "stmeq ip, {r0, r1, r2, r3}"
run_test

set_test_params "${ARCH}" "STRBEQ ip, [r2, -1]" 01c04205 "strbeq ip, [r2, -1]"
run_test

set_test_params "${ARCH}" "STRBEQ r3, [r5]" 0030c505 "strbeq r3, [r5]"
run_test

set_test_params "${ARCH}" "STRDEQ r2, [r4]" f020c401 "strdeq r2, [r4]"
run_test

set_test_params "${ARCH}" "STRDEQ r4, [r8, 80]" f045c801 "strdeq r4, [r8, 80]"
run_test

set_test_params "${ARCH}" "STREQ r3, [r5, -4]" 04300505 "streq r3, [r5, -4]"
run_test

set_test_params "${ARCH}" "STREQ r1, [fp, -304]" 30110b05 "streq r1, [fp, -304]"
run_test

set_test_params "${ARCH}" "STRHNE r3, [fp, -50]" b2334b11 "strhne r3, [fp, -50]"
run_test

set_test_params "${ARCH}" "STRHEQ r3, [fp, -56]" b8334b01 "strheq r3, [fp, -56]"
run_test

set_test_params "${ARCH}" "STRHEQ r1, [r0]" b010c001 "strheq r1, [r0]"
run_test

set_test_params "${ARCH}" "STRHNE r1, [r2,r3]" b3108211 "strhne r1, [r2, r3]"
run_test

set_test_params "${ARCH}" "SUBEQ ip, r0, 32" 20c04002 "subeq ip, r0, 32"
run_test

set_test_params "${ARCH}" "SUBNE r6, r3, r6, asr 1" c6604310 "subne r6, r3, r6, asr 1"
run_test

set_test_params "${ARCH}" "SUBNE r5, r5, r3" 03504510 "subne r5, r5, r3"
run_test

set_test_params "${ARCH}" "SVCEQ 0x00000000" 0000000f "svceq 0x00000000"
run_test

set_test_params "${ARCH}" "UMLALNE r4, r5, r3, r7" 9347a510 "umlalne r4, r5, r3, r7"
run_test

set_test_params "${ARCH}" "UXTBEQ r1, r0" 7010ef06 "uxtbeq r1, r0"
run_test

set_test_params "${ARCH}" "UXTHEQ r0, r0" 7000ff06 "uxtheq r0, r0"
run_test

set_test_params "${ARCH}" "VSTREQ d0, [r0]" 000b800d "vstreq d0, [r0]"
run_test

done
