#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../../tests.sh

NAME='pid asm.midflags=false'
FILE=malloc://1024
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=32
e asm.midflags=false
f mid.flag = 4
wx 31ed4989d15e4889e2
pid 3
'
EXPECT="0x00000000              31ed  xor ebp, ebp
0x00000002                49  dec ecx
0x00000003              89d1  mov ecx, edx
"
run_test

NAME='pid asm.midflags=true'
FILE=malloc://1024
ARGS=
BROKEN=1
CMDS='
e asm.arch=x86
e asm.bits=32
e asm.midflags=true
f mid.flag = 4
wx 31ed4989d15e4889e2
pid 3
'
EXPECT="0x00000000              31ed  xor ebp, ebp
0x00000002                49  dec ecx
0x00000003              89d1  mov ecx, edx
0x00000004 mid.flag:
0x00000004              89d1  mov ecx, edx
"
run_test

NAME='pd asm.midflags=false'
FILE=malloc://1024
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=32
e asm.midflags=false
e asm.lines=false
f mid.flag = 4
wx 31ed4989d15e4889e2
pd 4
'
EXPECT=" 0x00000000    31ed           xor ebp, ebp
 0x00000002    49             dec ecx
 0x00000003    89d1           mov ecx, edx
 0x00000005    5e             pop esi
"
run_test

NAME='pd asm.midflags=true'
FILE=malloc://1024
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=32
e asm.lines=false
e asm.midflags=true
f mid.flag = 5
wx 31ed4989d15e4889e2
pd 4
'
EXPECT=" 0x00000000    31ed           xor ebp, ebp
 0x00000002    49             dec ecx
 0x00000003    89d1           mov ecx, edx
  ;-- mid.flag:
 0x00000005    5e             pop esi
"
run_test

NAME='pd asm.midflags=true'
FILE=malloc://1024
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=32
e asm.lines=false
e asm.midflags=true
f mid.flag = 4
wx 31ed4989d15e4889e2
pd 4
'
EXPECT=" 0x00000000    31ed           xor ebp, ebp
 0x00000002    49             dec ecx
 0x00000003    89d1           mov ecx, edx
  ;-- mid.flag:
 0x00000004    d15e48         rcr dword [esi + 0x48], 1
"
run_test

