#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh; done

set_test_params() {
NAME="${1}: [${2}]"
FILE=malloc://32
BROKEN=${5}
CMDS='
e asm.arch='${1}'
e asm.bits=32
wx '${3}'
pi 1
'
EXPECT="${4}
"
}


for ARCH in x86 x86.olly x86.cs; do

set_test_params "${ARCH}" "CWDE" 98 "cwde"
run_test

set_test_params "${ARCH}" "CBW" 6698 "cbw"
run_test

set_test_params "${ARCH}" "CDQ" 99 "cdq"
run_test

set_test_params "${ARCH}" "CWD" 6699 "cwd"
run_test

set_test_params "${ARCH}" "CMC" F5 "cmc"
run_test

set_test_params "${ARCH}" "STC" F9 "stc"
run_test

set_test_params "${ARCH}" "CLC" F8 "clc"
run_test

set_test_params "${ARCH}" "CLI" FA "cli"
run_test

set_test_params "${ARCH}" "STI" FB "sti"
run_test

set_test_params "${ARCH}" "CLD" FC "cld"
run_test

set_test_params "${ARCH}" "STD" FD "std"
run_test

set_test_params "${ARCH}" "SALC" D6 "salc"
run_test

set_test_params "${ARCH}" "XLATB" D7 "xlatb"
run_test

set_test_params "${ARCH}" "LEAVE" C9 "leave"
run_test

set_test_params "${ARCH}" "INT1" F1 "int1"
run_test

set_test_params "${ARCH}" "INT 1" CD01 "int 0x1"
run_test

set_test_params "${ARCH}" "INT3" CC "int3"
run_test

set_test_params "${ARCH}" "INT 3" CD03 "int 0x3"
run_test

set_test_params "${ARCH}" "INTO" CE "into"
run_test

set_test_params "${ARCH}" "IRETD" CF "iretd"
run_test

set_test_params "${ARCH}" "IRETW" 66CF "iretw"
run_test

set_test_params "${ARCH}" "RET" C3 "ret"
run_test

set_test_params "${ARCH}" "RETF 0x0" CA00 "retf 0x0"
run_test

set_test_params "${ARCH}" "RETF" CB "retf"
run_test

set_test_params "${ARCH}" "HLT" F4 "hlt"
run_test

set_test_params "${ARCH}" "LAHF" 9F "lahf"
run_test

set_test_params "${ARCH}" "SAHF" 9E "sahf"
run_test

set_test_params "${ARCH}" "PUSHFD" 9C "pushfd"
run_test

set_test_params "${ARCH}" "POPFD" 9D "popfd"
run_test

set_test_params "${ARCH}" "PUSHAD" 60 "pushad"
run_test

set_test_params "${ARCH}" "POPAD" 61 "popad"
run_test

set_test_params "${ARCH}" "POPA" 6661 "popa"
run_test

set_test_params "${ARCH}" "DAA" 27 "daa"
run_test

set_test_params "${ARCH}" "AAA" 37 "aaa"
run_test

set_test_params "${ARCH}" "DAS" 2F "das"
run_test

set_test_params "${ARCH}" "AAS" 3F "aas"
run_test

set_test_params "${ARCH}" "PUSH EAX" 50 "push eax"
run_test

set_test_params "${ARCH}" "PUSH ECX" 51 "push ecx"
run_test

set_test_params "${ARCH}" "PUSH EDX" 52 "push edx"
run_test

set_test_params "${ARCH}" "PUSH EBX" 53 "push ebx"
run_test

set_test_params "${ARCH}" "PUSH ESP" 54 "push esp"
run_test

set_test_params "${ARCH}" "PUSH EBP" 55 "push ebp"
run_test

set_test_params "${ARCH}" "PUSH ESI" 56 "push esi"
run_test

set_test_params "${ARCH}" "PUSH EDI" 57 "push edi"
run_test

set_test_params "${ARCH}" "POP EAX" 58 "pop eax"
run_test

set_test_params "${ARCH}" "POP ECX" 59 "pop ecx"
run_test

set_test_params "${ARCH}" "POP EDX" 5A "pop edx"
run_test

set_test_params "${ARCH}" "POP EBX" 5B "pop ebx"
run_test

set_test_params "${ARCH}" "POP ESP" 5C "pop esp"
run_test

set_test_params "${ARCH}" "POP EBP" 5D "pop ebp"
run_test

set_test_params "${ARCH}" "POP ESI" 5E "pop esi"
run_test

set_test_params "${ARCH}" "POP EDI" 5F "pop edi"
run_test

set_test_params "${ARCH}" "PUSH DWORD [EAX]" ff30 "push dword [eax]"
run_test

set_test_params "${ARCH}" "POP DWORD [EAX]" 8f00 "pop dword [eax]"
run_test

set_test_params "${ARCH}" "PUSH ES" 06 "push es"
run_test

set_test_params "${ARCH}" "PUSH CS" 0E "push cs"
run_test

set_test_params "${ARCH}" "PUSH SS" 16 "push ss"
run_test

set_test_params "${ARCH}" "PUSH DS" 1E "push ds"
run_test

set_test_params "${ARCH}" "POP ES" 07 "pop es"
run_test

set_test_params "${ARCH}" "POP SS" 17 "pop ss"
run_test

set_test_params "${ARCH}" "POP DS" 1F "pop ds"
run_test

set_test_params "${ARCH}" "PUSH 0" 6a00 "push 0x0"
run_test

set_test_params "${ARCH}" "PUSH FS" 0fa0 "push fs"
run_test

set_test_params "${ARCH}" "POP FS" 0fa1 "pop fs"
run_test

set_test_params "${ARCH}" "PUSH GS" 0fa8 "push gs"
run_test

set_test_params "${ARCH}" "POP GS" 0fa9 "pop gs"
run_test

set_test_params "${ARCH}" "INC EAX" 40 "inc eax"
run_test

set_test_params "${ARCH}" "INC ECX" 41 "inc ecx"
run_test

set_test_params "${ARCH}" "INC EDX" 42 "inc edx"
run_test

set_test_params "${ARCH}" "INC EBX" 43 "inc ebx"
run_test

set_test_params "${ARCH}" "INC ESP" 44 "inc esp"
run_test

set_test_params "${ARCH}" "INC EBP" 45 "inc ebp"
run_test

set_test_params "${ARCH}" "INC ESI" 46 "inc esi"
run_test

set_test_params "${ARCH}" "INC EDI" 47 "inc edi"
run_test

set_test_params "${ARCH}" "DEC EAX" 48 "dec eax"
run_test

set_test_params "${ARCH}" "DEC ECX" 49 "dec ecx"
run_test

set_test_params "${ARCH}" "DEC EDX" 4a "dec edx"
run_test

set_test_params "${ARCH}" "DEC EBX" 4b "dec ebx"
run_test

set_test_params "${ARCH}" "DEC ESP" 4c "dec esp"
run_test

set_test_params "${ARCH}" "DEC EBP" 4d "dec ebp"
run_test

set_test_params "${ARCH}" "DEC ESI" 4e "dec esi"
run_test

set_test_params "${ARCH}" "DEC EDI" 4f "dec edi"
run_test

set_test_params "${ARCH}" "INC BYTE [EAX]" fe00 "inc byte [eax]"
run_test

set_test_params "${ARCH}" "INC DWORD [EAX]" ff00 "inc dword [eax]"
run_test

set_test_params "${ARCH}" "DEC BYTE [EAX]" fe08 "dec byte [eax]"
run_test

set_test_params "${ARCH}" "DEC DWORD [EAX]" ff08 "dec dword [eax]"
run_test


set_test_params "${ARCH}" "SLDT [EAX]" 0f0000 "sldt word [eax]"
run_test

set_test_params "${ARCH}" "STR [EAX]" 0f0008 "str word [eax]"
run_test

set_test_params "${ARCH}" "LLDT [EAX]" 0f0010 "lldt word [eax]"
run_test

set_test_params "${ARCH}" "LLDT AX" 0f00d0 "lldt ax"
run_test

set_test_params "${ARCH}" "LTR [EAX]" 0f0018 "ltr word [eax]"
run_test

set_test_params "${ARCH}" "LTR AX" 0f00d8 "ltr ax"
run_test

set_test_params "${ARCH}" "VERR [EAX]" 0f0020 "verr word [eax]"
run_test

set_test_params "${ARCH}" "VERR AX" 0f00e0 "verr ax"
run_test

set_test_params "${ARCH}" "VERW [EAX]" 0f0028 "verw word [eax]"
run_test

set_test_params "${ARCH}" "VERW AX" 0f00e8 "verw ax"
run_test

set_test_params "${ARCH}" "SGDT [EAX]" 0f0100 "sgdt [eax]"
run_test

set_test_params "${ARCH}" "SIDT [EAX]" 0f0108 "sidt [eax]"
run_test

set_test_params "${ARCH}" "LGDT [EAX]" 0f0110 "lgdt [eax]"
run_test

set_test_params "${ARCH}" "LIDT [EAX]" 0f0118 "lidt [eax]"
run_test

set_test_params "${ARCH}" "SMSW [EAX]" 0f0120 "smsw word [eax]"
run_test

set_test_params "${ARCH}" "LMSW [EAX]" 0f0130 "lmsw word [eax]"
run_test

set_test_params "${ARCH}" "INVLPG [EAX]" 0f0138 "invlpg [eax]"
run_test

set_test_params "${ARCH}" "MOV AL,0" B000 "mov al, 0x0"
run_test

set_test_params "${ARCH}" "MOV CL,0" B100 "mov cl, 0x0"
run_test

set_test_params "${ARCH}" "MOV DL,0" B200 "mov dl, 0x0"
run_test

set_test_params "${ARCH}" "MOV BL,0" B300 "mov bl, 0x0"
run_test

set_test_params "${ARCH}" "MOV AH,0" B400 "mov ah, 0x0"
run_test

set_test_params "${ARCH}" "MOV CH,0" B500 "mov ch, 0x0"
run_test

set_test_params "${ARCH}" "MOV DH,0" B600 "mov dh, 0x0"
run_test

set_test_params "${ARCH}" "MOV BH,0" B700 "mov bh, 0x0"
run_test

set_test_params "${ARCH}" "TEST AL,0" A8 "test al, 0x0"
run_test

set_test_params "${ARCH}" "IN AL,0" E4 "in al, 0x0"
run_test

set_test_params "${ARCH}" "IN EAX,0" E5 "in eax, 0x0"
run_test

set_test_params "${ARCH}" "IN AL,DX" ec "in al, dx"
run_test

set_test_params "${ARCH}" "IN EAX,DX" ed "in eax, dx"
run_test

set_test_params "${ARCH}" "OUT 0X0, AL" E600 "out 0x0, al"
run_test

set_test_params "${ARCH}" "OUT 0X0, EAX" E700 "out 0x0, eax"
run_test

set_test_params "${ARCH}" "OUT DX, AL" ee "out dx, al"
run_test

set_test_params "${ARCH}" "OUT DX, EAX" ef "out dx, eax"
run_test

set_test_params "${ARCH}" "CPUID" 0fa2 "cpuid"
run_test

set_test_params "${ARCH}" "PUSHFS" 0fa0 "push fs"
run_test

set_test_params "${ARCH}" "POP FS" 0fa1 "pop fs"
run_test

set_test_params "${ARCH}" "PUSH GS" 0fa8 "push gs"
run_test

set_test_params "${ARCH}" "POP GS" 0fa9 "pop gs"
run_test

set_test_params "${ARCH}" "INVD" 0f08 "invd"
run_test

set_test_params "${ARCH}" "WBINVD" 0f09 "wbinvd"
run_test

set_test_params "${ARCH}" "VMCALL" 0f01c1 "vmcall" 1
run_test

set_test_params "${ARCH}" "VMLAUNCH" 0f01c2 "vmlaunch" 1
run_test

set_test_params "${ARCH}" "VMRESUME" 0f01c3 "vmresume" 1
run_test

set_test_params "${ARCH}" "VMXOFF" 0f01c4 "vmxoff" 1
run_test

set_test_params "${ARCH}" "MONITOR" 0f01c8 "monitor"
run_test

set_test_params "${ARCH}" "MWAIT" 0f01c9 "mwait"
run_test

set_test_params "${ARCH}" "XGETBV" 0f01d0 "xgetbv"
run_test

set_test_params "${ARCH}" "XSETBV" 0f01d1 "xsetbv"
run_test

set_test_params "${ARCH}" "VMRUN" 0f01d8 "vmrun"
run_test

set_test_params "${ARCH}" "VMMCALL" 0f01d9 "vmmcall"
run_test

set_test_params "${ARCH}" "VMLOAD" 0f01da "vmload"
run_test

set_test_params "${ARCH}" "VMSAVE" 0f01db "vmsave"
run_test

set_test_params "${ARCH}" "STGI" 0f01dc "stgi"
run_test

set_test_params "${ARCH}" "CLGI" 0f01dd "clgi"
run_test

set_test_params "${ARCH}" "SKINIT" 0f01de "skinit"
run_test

set_test_params "${ARCH}" "INVLPGA" 0f01df "invlpga"
run_test

set_test_params "${ARCH}" "PAUSE" f390 "pause"
run_test

set_test_params "${ARCH}" "RDTSCP" 0f01f9 "rdtscp"
run_test

set_test_params "${ARCH}" "LAR EAX, [EAX]" 0f02 "lar eax, word [eax]"
run_test

set_test_params "${ARCH}" "LSL EAX, [EAX]" 0f03 "lsl eax, word [eax]"
run_test

set_test_params "${ARCH}" "CLTS" 0f06 "clts"
run_test

set_test_params "${ARCH}" "SYSRET" 0f07 "sysret"
run_test

set_test_params "${ARCH}" "EMMS" 0f77 "emms"
run_test

set_test_params "${ARCH}" "FEMMS" 0f0e "femms"
run_test

set_test_params "${ARCH}" "CPUID" 0fa2 "cpuid"
run_test

set_test_params "${ARCH}" "RSM" 0faa "rsm"
run_test

set_test_params "${ARCH}" "UD2" 0f0b "ud2"
run_test

set_test_params "${ARCH}" "GETSEC" 0f37h "getsec"
run_test

set_test_params "${ARCH}" "MOV EAX, CR0" 0f20 "mov eax, cr0" 1
run_test

set_test_params "${ARCH}" "MOV EAX, DR0" 0f21 "mov eax, dr0" 1
run_test

set_test_params "${ARCH}" "MOV CR0, EAX" 0f22 "mov cr0, eax" 1
run_test

set_test_params "${ARCH}" "MOV DR0, EAX" 0f23 "mov dr0, eax" 1
run_test

set_test_params "${ARCH}" "JO 0x2" 7000 "jo 0x2"
run_test

set_test_params "${ARCH}" "JNO 0x2" 7100 "jno 0x2"
run_test

set_test_params "${ARCH}" "JB 0x2" 7200 "jb 0x2"
run_test

set_test_params "${ARCH}" "JAE 0x2" 7300 "jae 0x2"
run_test

set_test_params "${ARCH}" "JE 0x2" 7400 "je 0x2"
run_test

set_test_params "${ARCH}" "JNZ 0x2" 7500 "jne 0x2"
run_test

set_test_params "${ARCH}" "JBE 0x2" 7600 "jbe 0x2"
run_test

set_test_params "${ARCH}" "JA 0x2" 7700 "ja 0x2"
run_test

set_test_params "${ARCH}" "JS 0x2" 7800 "js 0x2"
run_test

set_test_params "${ARCH}" "JNS 0x2" 7900 "jns 0x2"
run_test

set_test_params "${ARCH}" "JP 0x2" 7a00 "jp 0x2"
run_test

set_test_params "${ARCH}" "JNP 0x2" 7b00 "jnp 0x2"
run_test

set_test_params "${ARCH}" "JL 0x2" 7c00 "jl 0x2"
run_test

set_test_params "${ARCH}" "JGE 0x2" 7d00 "jge 0x2"
run_test

set_test_params "${ARCH}" "JLE 0x2" 7e00 "jle 0x2"
run_test

set_test_params "${ARCH}" "JG 0x2" 7f00 "jg 0x2"
run_test

set_test_params "${ARCH}" "JO 0x6" 0f8000000000 "jo 0x6"
run_test

set_test_params "${ARCH}" "JNO 0x6" 0f8100000000 "jno 0x6"
run_test

set_test_params "${ARCH}" "JB 0x6" 0f8200000000 "jb 0x6"
run_test

set_test_params "${ARCH}" "JAE 0x6" 0f8300000000 "jae 0x6"
run_test

set_test_params "${ARCH}" "JE 0x6" 0f8400000000 "je 0x6"
run_test

set_test_params "${ARCH}" "JNE 0x6" 0f8500000000 "jne 0x6"
run_test

set_test_params "${ARCH}" "JBE 0x6" 0f8600000000 "jbe 0x6"
run_test

set_test_params "${ARCH}" "JA 0x6" 0f8700000000 "ja 0x6"
run_test

set_test_params "${ARCH}" "JS 0x6" 0f8800000000 "js 0x6"
run_test

set_test_params "${ARCH}" "JNS 0x6" 0f8900000000 "jns 0x6"
run_test

set_test_params "${ARCH}" "JP 0x6" 0f8a00000000 "jp 0x6"
run_test

set_test_params "${ARCH}" "JNP 0x6" 0f8b00000000 "jnp 0x6"
run_test

set_test_params "${ARCH}" "JL 0x6" 0f8c00000000 "jl 0x6"
run_test

set_test_params "${ARCH}" "JGE 0x6" 0f8d00000000 "jge 0x6"
run_test

set_test_params "${ARCH}" "JLE 0x6" 0f8e00000000 "jle 0x6"
run_test

set_test_params "${ARCH}" "JG 0x6" 0f8f00000000 "jg 0x6"
run_test

set_test_params "${ARCH}" "SETO [EAX]" 660f9000 "o16 seto byte [eax]"
run_test

set_test_params "${ARCH}" "SETNO [EAX]" 660f9100 "o16 setno byte [eax]"
run_test

set_test_params "${ARCH}" "SETB [EAX]" 660f9200 "o16 setb byte [eax]"
run_test

set_test_params "${ARCH}" "SETAE [EAX]" 660f9300 "o16 setae byte [eax]"
run_test

set_test_params "${ARCH}" "SETE [EAX]" 660f9400 "o16 sete byte [eax]"
run_test

set_test_params "${ARCH}" "SETNE [EAX]" 660f9500 "o16 setne byte [eax]"
run_test

set_test_params "${ARCH}" "SETBE [EAX]" 660f9600 "o16 setbe byte [eax]"
run_test

set_test_params "${ARCH}" "SETA [EAX]" 660f9700 "o16 seta byte [eax]"
run_test

set_test_params "${ARCH}" "SETS [EAX]" 660f9800 "o16 sets byte [eax]"
run_test

set_test_params "${ARCH}" "SETNS [EAX]" 660f9900 "o16 setns byte [eax]"
run_test

set_test_params "${ARCH}" "SETP [EAX]" 660f9a00 "o16 setp byte [eax]"
run_test

set_test_params "${ARCH}" "SETNP [EAX]" 660f9b00 "o16 setnp byte [eax]"
run_test

set_test_params "${ARCH}" "SETL [EAX]" 660f9c00 "o16 setl byte [eax]"
run_test

set_test_params "${ARCH}" "SETGE [EAX]" 660f9d00 "o16 setge byte [eax]"
run_test

set_test_params "${ARCH}" "SETLE [EAX]" 660f9e00 "o16 setle byte [eax]"
run_test

set_test_params "${ARCH}" "SETG [EAX]" 660f9f00 "o16 setg byte [eax]"
run_test

set_test_params "${ARCH}" "CMOVO EAX, [EAX]" 0f4000 "cmovo eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVNO EAX, [EAX]" 0f4100 "cmovno eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVB EAX, [EAX]" 0f4200 "cmovb eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVAE EAX, [EAX]" 0f4300 "cmovae eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVE EAX, [EAX]" 0f4400 "cmove eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVNE EAX, [EAX]" 0f4500 "cmovne eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVBE EAX, [EAX]" 0f4600 "cmovbe eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVA EAX, [EAX]" 0f4700 "cmova eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVS EAX, [EAX]" 0f4800 "cmovs eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVNS EAX, [EAX]" 0f4900 "cmovns eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVP EAX, [EAX]" 0f4a00 "cmovp eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVNP EAX, [EAX]" 0f4b00 "cmovnp eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVL EAX, [EAX]" 0f4c00 "cmovl eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVGE EAX, [EAX]" 0f4d00 "cmovge eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVLE EAX, [EAX]" 0f4e00 "cmovle eax, [eax]"
run_test

set_test_params "${ARCH}" "CMOVG EAX, [EAX]" 0f4f00 "cmovg eax, [eax]"
run_test

set_test_params "${ARCH}" "MOV AL, [EAX]" 8a00 "mov al, [eax]"
run_test

set_test_params "${ARCH}" "MOV EAX, [EAX]" 8b00 "mov eax, [eax]"
run_test

set_test_params "${ARCH}" "MOV [EAX], ES" 8c00 "mov [eax], es"
run_test

set_test_params "${ARCH}" "MOV ES, [EAX]" 8e00 "mov es, [eax]"
run_test

set_test_params "${ARCH}" "LEA EAX, [EAX]" 8d00 "lea eax, [eax]"
run_test

set_test_params "${ARCH}" "POP DWORD [EAX]" 8f00 "pop dword [eax]"
run_test

set_test_params "${ARCH}" "NOP" 90 "nop"
run_test

set_test_params "${ARCH}" "XCHG ECX, EAX" 91 "xchg ecx, eax"
run_test

set_test_params "${ARCH}" "XCHG EDX, EAX" 92 "xchg edx, eax"
run_test

set_test_params "${ARCH}" "XCHG EBX, EAX" 93 "xchg ebx, eax"
run_test

set_test_params "${ARCH}" "XCHG ESP, EAX" 94 "xchg esp, eax"
run_test

set_test_params "${ARCH}" "XCHG EBP, EAX" 95 "xchg ebp, eax"
run_test

set_test_params "${ARCH}" "XCHG ESI, EAX" 96 "xchg esi, eax"
run_test

set_test_params "${ARCH}" "XCHG EDI, EAX" 97 "xchg edi, eax"
run_test

set_test_params "${ARCH}" "MOVSB" a4 "movsb"
run_test

set_test_params "${ARCH}" "MOVSD" a5 "movsd"
run_test

set_test_params "${ARCH}" "CMPSB" a6 "cmpsb"
run_test

set_test_params "${ARCH}" "CMPSD" a7 "cmpsd"
run_test

set_test_params "${ARCH}" "STOSB" aa "stosb"
run_test

set_test_params "${ARCH}" "STOSD" ab "stosd"
run_test

set_test_params "${ARCH}" "LODSB" ac "lodsb"
run_test

set_test_params "${ARCH}" "LODSD" ad "lodsd"
run_test

set_test_params "${ARCH}" "SCASB" ae "scasb"
run_test

set_test_params "${ARCH}" "SCASD" af "scasd"
run_test

set_test_params "${ARCH}" "PREFETCH [EAX]" 0f0d00 "prefetch [eax]"
run_test

set_test_params "${ARCH}" "PREFETCHNTA [EAX]" 0f1800 "prefetchnta [eax]"
run_test

set_test_params "${ARCH}" "PREFETCHT0 [EAX]" 0f1808 "prefetcht0 [eax]"
run_test

set_test_params "${ARCH}" "PREFETCHT1 [EAX]" 0f1810 "prefetcht1 [eax]"
run_test

set_test_params "${ARCH}" "PREFETCHT2 [EAX]" 0f1818 "prefetcht2 [eax]"
run_test

set_test_params "${ARCH}" "SYSCALL" 0f05 "syscall"
run_test

set_test_params "${ARCH}" "WRMSR" 0f30 "wrmsr"
run_test

set_test_params "${ARCH}" "RDTSC" 0f31 "rdtsc"
run_test

set_test_params "${ARCH}" "RDMSR" 0f32 "rdmsr"
run_test

set_test_params "${ARCH}" "RDPMC" 0f33 "rdpmc"
run_test

set_test_params "${ARCH}" "SYSENTER" 0f34 "sysenter"
run_test

set_test_params "${ARCH}" "SYSEXIT" 0f35 "sysexit"
run_test

set_test_params "${ARCH}" "CRC32 EAX, BYTE [EAX]" f20f38f0 "crc32 eax, byte [eax]"
run_test

set_test_params "${ARCH}" "CRC32 EAX, [EAX]" f20f38f1 "crc32 eax, [eax]"
run_test

set_test_params "${ARCH}" "BT [EAX], EAX" 0fa300 "bt [eax], eax"
run_test

set_test_params "${ARCH}" "BTS [EAX], EAX" 0fab00 "bts [eax], eax"
run_test

set_test_params "${ARCH}" "BTR [EAX], EAX" 0fb300 "btr [eax], eax"
run_test

set_test_params "${ARCH}" "SHLD [EAX], EAX, 0X0" 0fa40000 "shld [eax], eax, 0x0"
run_test

set_test_params "${ARCH}" "SHLD [EAX], EAX, CL" 0fa500 "shld [eax], eax, cl"
run_test

set_test_params "${ARCH}" "SHRD [EAX], EAX, 0X0" 0fac0000 "shrd [eax], eax, 0x0"
run_test

set_test_params "${ARCH}" "SHRD [EAX], EAX, CL" 0fad00 "shrd [eax], eax, cl"
run_test

set_test_params "${ARCH}" "BSWAP EAX" 0fc8 "bswap eax"
run_test

set_test_params "${ARCH}" "BSWAP ECX" 0fc9 "bswap ecx"
run_test

set_test_params "${ARCH}" "BSWAP EDX" 0fca "bswap edx"
run_test

set_test_params "${ARCH}" "BSWAP EBX" 0fcb "bswap ebx"
run_test

set_test_params "${ARCH}" "BSWAP ESP" 0fcc "bswap esp"
run_test

set_test_params "${ARCH}" "BSWAP EBP" 0fcd "bswap ebp"
run_test

set_test_params "${ARCH}" "BSWAP ESI" 0fce "bswap esi"
run_test

set_test_params "${ARCH}" "BSWAP EDI" 0fcf "bswap edi"
run_test

set_test_params "${ARCH}" "INSB" 6c "insb"
run_test

set_test_params "${ARCH}" "INSD" 6d "insd"
run_test

set_test_params "${ARCH}" "OUTSB" 6e "outsb"
run_test

set_test_params "${ARCH}" "OUTSD" 6f "outsd"
run_test

set_test_params "${ARCH}" "MFENCE" 0faef0 "mfence"
run_test

set_test_params "${ARCH}" "LFENCE" 0faee8 "lfence"
run_test

set_test_params "${ARCH}" "SFENCE" 0faef8 "sfence"
run_test

set_test_params "${ARCH}" "SMSW AX" 660f01e0 "smsw ax"
run_test

set_test_params "${ARCH}" "SMSW EAX" 0f01e0 "smsw eax"
run_test

set_test_params "${ARCH}" "LMSW AX" 0f01f0 "lmsw ax"
run_test

set_test_params "${ARCH}" "FXSAVE [EAX]" 0fae00 "fxsave [eax]"
run_test

set_test_params "${ARCH}" "FXRSTOR [EAX]" 0fae08 "fxrstor [eax]"
run_test

set_test_params "${ARCH}" "LDMXCSR [EAX]" 0fae10 "ldmxcsr dword [eax]"
run_test

set_test_params "${ARCH}" "STMXCSR [EAX]" 0fae18 "stmxcsr dword [eax]"
run_test

set_test_params "${ARCH}" "XSAVE [EAX]" 0fae20 "xsave [eax]"
run_test

set_test_params "${ARCH}" "XRSTOR [EAX]" 0fae28 "xrstor [eax]"
run_test

set_test_params "${ARCH}" "CLFLUSH [EAX]" 0fae38 "clflush [eax]"
run_test

set_test_params "${ARCH}" "TEST BYTE [EAX], 0" f60000 "test byte [eax], 0x0"
run_test

set_test_params "${ARCH}" "TEST BYTE [EAX], 0" f60800 "test byte [eax], 0x0"
run_test

set_test_params "${ARCH}" "NOT BYTE [EAX]" f610 "not byte [eax]"
run_test

set_test_params "${ARCH}" "NEG BYTE [EAX]" f618 "neg byte [eax]"
run_test

set_test_params "${ARCH}" "MUL BYTE [EAX]" f620 "mul byte [eax]"
run_test

set_test_params "${ARCH}" "IMUL BYTE [EAX]" f628 "imul byte [eax]"
run_test

set_test_params "${ARCH}" "DIV BYTE [EAX]" f630 "div byte [eax]"
run_test

set_test_params "${ARCH}" "IDIV BYTE [EAX]" f638 "idiv byte [eax]"
run_test

set_test_params "${ARCH}" "TEST DWORD [EAX], 0" f70000 "test dword [eax], 0x0"
run_test

set_test_params "${ARCH}" "TEST DWORD [EAX], 0" f70800 "test dword [eax], 0x0"
run_test

set_test_params "${ARCH}" "VZEROALL" c5fc77 "vzeroall"
run_test

set_test_params "${ARCH}" "VZEROUPPER" c5f877 "vzeroupper"
run_test

set_test_params "${ARCH}" "MOV [ES:EAX], EAX" 268900 "mov [es:eax], eax"
run_test

set_test_params "${ARCH}" "MOV [CS:EAX], EAX" 2e8900 "mov [cs:eax], eax"
run_test

set_test_params "${ARCH}" "MOV [SS:EAX], EAX" 368900 "mov [ss:eax], eax"
run_test

set_test_params "${ARCH}" "MOV [DS:EAX], EAX" 3e8900 "mov [ds:eax], eax"
run_test

set_test_params "${ARCH}" "MOV [FS:EAX], EAX" 648900 "mov [fs:eax], eax"
run_test

set_test_params "${ARCH}" "MOV [GS:EAX], EAX" 658900 "mov [gs:eax], eax"
run_test

set_test_params "${ARCH}" "FXSAVE [EAX]" 0fae00 "fxsave [eax]"
run_test

set_test_params "${ARCH}" "BOUND EAX, [EAX]" 6200 "bound eax, [eax]"
run_test

set_test_params "${ARCH}" "ARPL [EAX], AX" 6300 "arpl [eax], ax"
run_test

set_test_params "${ARCH}" "CMPXCHG [EAX], AL" 0fb000 "cmpxchg [eax], al"
run_test

set_test_params "${ARCH}" "CMPXCHG [EAX], EAX" 0fb100 "cmpxchg [eax], eax"
run_test

set_test_params "${ARCH}" "CMPXCHG8B [EAX]" 0fc7c0 "cmpxchg8b [eax]" 1
run_test

set_test_params "${ARCH}" "LOCK CMPXCHG8B [EAX]" f00fc7c0 "lock cmpxchg8b [eax]" 1
run_test

set_test_params "${ARCH}" "VMPTRLD [EAX]" 0fc730 "vmptrld [eax]" 1
run_test

set_test_params "${ARCH}" "VMCLEAR [EAX]" 660fc730 "vmclear [eax]" 1
run_test

set_test_params "${ARCH}" "VMXON [EAX]" f30fc730 "vmxon [eax]" 1
run_test

set_test_params "${ARCH}" "VMPTRST [EAX]" 0fc738 "vmptrst [eax]" 1
run_test

set_test_params "${ARCH}" "ADC [EAX], AL" 1000 "adc [eax], al"
run_test

set_test_params "${ARCH}" "ADC [EAX], EAX" 1100 "adc [eax], eax"
run_test

set_test_params "${ARCH}" "ADC AL, [EAX]" 1200 "adc al, [eax]"
run_test

set_test_params "${ARCH}" "ADC EAX, [EAX]" 1300 "adc eax, [eax]"
run_test

set_test_params "${ARCH}" "ADC AL, 0" 1400 "adc al, 0x0"
run_test

set_test_params "${ARCH}" "ADD [EAX], AL" 0000 "add [eax], al"
run_test

set_test_params "${ARCH}" "ADD [EAX], EAX" 0100 "add [eax], eax"
run_test

set_test_params "${ARCH}" "ADD AL, [EAX]" 0200 "add al, [eax]"
run_test

set_test_params "${ARCH}" "ADD EAX, [EAX]" 0300 "add eax, [eax]"
run_test

set_test_params "${ARCH}" "ADD AL, 0" 0400 "add al, 0x0"
run_test

set_test_params "${ARCH}" "ADD BYTE [EAX], 0X0" 800000 "add byte [eax], 0x0"
run_test

set_test_params "${ARCH}" "ADD DWORD [EAX], 0X0" 810000000000 "add dword [eax], 0x0"
run_test

set_test_params "${ARCH}" "ADD BYTE [EAX], 0X0" 820000 "add byte [eax], 0x0"
run_test

set_test_params "${ARCH}" "ADD DWORD [EAX], 0X0" 830000 "add dword [eax], 0x0"
run_test

set_test_params "${ARCH}" "AND [EAX], AL" 2000 "and [eax], al"
run_test

set_test_params "${ARCH}" "AND [EAX], EAX" 2100 "and [eax], eax"
run_test

set_test_params "${ARCH}" "AND AL, [EAX]" 2200 "and al, [eax]"
run_test

set_test_params "${ARCH}" "AND EAX, [EAX]" 2300 "and eax, [eax]"
run_test

set_test_params "${ARCH}" "AND AL, 0" 2400 "and al, 0x0"
run_test

set_test_params "${ARCH}" "CMP [EAX], AL" 3800 "cmp [eax], al"
run_test

set_test_params "${ARCH}" "CMP [EAX], EAX" 3900 "cmp [eax], eax"
run_test

set_test_params "${ARCH}" "CMP AL, [EAX]" 3a00 "cmp al, [eax]"
run_test

set_test_params "${ARCH}" "CMP EAX, [EAX]" 3b00 "cmp eax, [eax]"
run_test

set_test_params "${ARCH}" "CMP AL, 0" 3c00 "cmp al, 0x0"
run_test

set_test_params "${ARCH}" "MOV [EAX], AL" 8800 "mov [eax], al"
run_test

set_test_params "${ARCH}" "MOV [EAX], EAX" 8900 "mov [eax], eax"
run_test

set_test_params "${ARCH}" "MOV AL, [EAX]" 8a00 "mov al, [eax]"
run_test

set_test_params "${ARCH}" "MOV AL, [0X0]" a000000000 "mov al, [0x0]"
run_test

set_test_params "${ARCH}" "MOV EAX, [0X0]" a100000000 "mov eax, [0x0]"
run_test

set_test_params "${ARCH}" "MOV [0X0], AL" a200000000 "mov [0x0], al"
run_test

set_test_params "${ARCH}" "MOV [0X0], EAX" a300000000 "mov [0x0], eax"
run_test

set_test_params "${ARCH}" "MOV AL, 0X0" b000 "mov al, 0x0"
run_test

set_test_params "${ARCH}" "MOV CL, 0X0" b100 "mov cl, 0x0"
run_test

set_test_params "${ARCH}" "MOV DL, 0X0" b200 "mov dl, 0x0"
run_test

set_test_params "${ARCH}" "MOV BL, 0X0" b300 "mov bl, 0x0"
run_test

set_test_params "${ARCH}" "MOV AH, 0X0" b400 "mov ah, 0x0"
run_test

set_test_params "${ARCH}" "MOV CH, 0X0" b500 "mov ch, 0x0"
run_test

set_test_params "${ARCH}" "MOV DH, 0X0" b600 "mov dh, 0x0"
run_test

set_test_params "${ARCH}" "MOV BH, 0X0" b700 "mov bh, 0x0"
run_test

set_test_params "${ARCH}" "MOV EAX, 0X0" b800000000 "mov eax, 0x0"
run_test

set_test_params "${ARCH}" "MOV ECX, 0X0" b900000000 "mov ecx, 0x0"
run_test

set_test_params "${ARCH}" "MOV EDX, 0X0" ba00000000 "mov edx, 0x0"
run_test

set_test_params "${ARCH}" "MOV EBX, 0X0" bb00000000 "mov ebx, 0x0"
run_test

set_test_params "${ARCH}" "MOV ESP, 0X0" bc00000000 "mov esp, 0x0"
run_test

set_test_params "${ARCH}" "MOV EBP, 0X0" bd00000000 "mov ebp, 0x0"
run_test

set_test_params "${ARCH}" "MOV ESI, 0X0" be00000000 "mov esi, 0x0"
run_test

set_test_params "${ARCH}" "MOV EDI, 0X0" bf00000000 "mov edi, 0x0"
run_test

set_test_params "${ARCH}" "OR [EAX], AL" 0800 "or [eax], al"
run_test

set_test_params "${ARCH}" "OR [EAX], EAX" 0900 "or [eax], eax"
run_test

set_test_params "${ARCH}" "OR EAX, [EAX]" 0b00 "or eax, [eax]"
run_test

set_test_params "${ARCH}" "OR AL, 0X0" 0c00 "or al, 0x0"
run_test

set_test_params "${ARCH}" "SBB [EAX], AL" 1800 "sbb [eax], al"
run_test

set_test_params "${ARCH}" "SBB [EAX], EAX" 1900 "sbb [eax], eax"
run_test

set_test_params "${ARCH}" "SBB AL, [EAX]" 1a00 "sbb al, [eax]"
run_test

set_test_params "${ARCH}" "SBB EAX, [EAX]" 1b00 "sbb eax, [eax]"
run_test

set_test_params "${ARCH}" "SBB AL, 0X0" 1c00 "sbb al, 0x0"
run_test

set_test_params "${ARCH}" "SUB [EAX], AL" 2800 "sub [eax], al"
run_test

set_test_params "${ARCH}" "SUB [EAX], EAX" 2900 "sub [eax], eax"
run_test

set_test_params "${ARCH}" "SUB AL, [EAX]" 2a00 "sub al, [eax]"
run_test

set_test_params "${ARCH}" "SUB EAX, [EAX]" 2b00 "sub eax, [eax]"
run_test

set_test_params "${ARCH}" "SUB AL, 0X0" 2c00 "sub al, 0x0"
run_test

set_test_params "${ARCH}" "TEST [EAX], AL" 8400 "test [eax], al"
run_test

set_test_params "${ARCH}" "TEST [EAX], EAX" 8500 "test [eax], eax"
run_test

set_test_params "${ARCH}" "TEST AL, 0X0" a800 "test al, 0x0"
run_test

set_test_params "${ARCH}" "TEST EAX, 0X0" a900000000 "test eax, 0x0"
run_test

set_test_params "${ARCH}" "TEST BYTE [EAX], 0X0" f60000 "test byte [eax], 0x0"
run_test

set_test_params "${ARCH}" "TEST DWORD [EAX], 0X0" f70000000000 "test dword [eax], 0x0"
run_test

set_test_params "${ARCH}" "XCHG [EAX], AL" 8600 "xchg [eax], al"
run_test

set_test_params "${ARCH}" "XCHG [EAX], EAX" 8700 "xchg [eax], eax"
run_test

set_test_params "${ARCH}" "XOR [EAX], AL" 3000 "xor [eax], al"
run_test

set_test_params "${ARCH}" "XOR [EAX], EAX" 3100 "xor [eax], eax"
run_test

set_test_params "${ARCH}" "XOR AL, [EAX]" 3200 "xor al, [eax]"
run_test

set_test_params "${ARCH}" "XOR EAX, [EAX]" 3300 "xor eax, [eax]"
run_test

set_test_params "${ARCH}" "XOR AL, 0" 3400 "xor al, 0x0"
run_test

set_test_params "${ARCH}" "BTC [EAX], EAX" 0fbb00 "btc [eax], eax"
run_test

set_test_params "${ARCH}" "BSF EAX, [EAX]" 0fbc00 "bsf eax, [eax]"
run_test

set_test_params "${ARCH}" "BSR EAX, [EAX]" 0fbd00 "bsr eax, [eax]"
run_test

set_test_params "${ARCH}" "ROL BYTE [EAX], 0X0" c00000 "rol byte [eax], 0x0"
run_test

set_test_params "${ARCH}" "ROL DWORD [EAX], 0X0" c10000 "rol dword [eax], 0x0"
run_test

set_test_params "${ARCH}" "LES EAX, [EAX]" c400 "les eax, [eax]"
run_test

set_test_params "${ARCH}" "LDS EAX, [EAX]" c500 "lds eax, [eax]"
run_test

set_test_params "${ARCH}" "MOV BYTE [EAX], 0X0" c60000 "mov byte [eax], 0x0"
run_test

set_test_params "${ARCH}" "MOV DWORD [EAX], 0X0" c70000000000 "mov dword [eax], 0x0"
run_test

set_test_params "${ARCH}" "ROL BYTE [EAX], CL" d200 "rol byte [eax], cl"
run_test

set_test_params "${ARCH}" "ROL DWORD [EAX], CL" d300 "rol dword [eax], cl"
run_test

set_test_params "${ARCH}" "SHUFPS XMM0, [EAX], 0X0" 0fc60000 "shufps xmm0, [eax], 0x0"
run_test

set_test_params "${ARCH}" "PSUBUSB MM0, [EAX]" 0fd800 "psubusb mm0, [eax]"
run_test

set_test_params "${ARCH}" "PSUBUSW MM0, [EAX]" 0fd900 "psubusw mm0, [eax]"
run_test

set_test_params "${ARCH}" "PAND MM0, [EAX]" 0fdb00 "pand mm0, [eax]"
run_test

set_test_params "${ARCH}" "PANDN MM0, [EAX]" 0fdf00 "pandn mm0, [eax]"
run_test

set_test_params "${ARCH}" "POR MM0, [EAX]" 0feb00 "por mm0, [eax]"
run_test

set_test_params "${ARCH}" "PXOR MM0, [EAX]" 0fef00 "pxor mm0, [eax]"
run_test

set_test_params "${ARCH}" "PADDUSB MM0, [EAX]" 0fdc00 "paddusb mm0, [eax]"
run_test

set_test_params "${ARCH}" "PADDUSW MM0, [EAX]" 0fdd00 "paddusw mm0, [eax]"
run_test

set_test_params "${ARCH}" "PMAXUB MM0, [EAX]" 0fde00 "pmaxub mm0, [eax]"
run_test

set_test_params "${ARCH}" "PMINUB MM0, [EAX]" 0fda00 "pminub mm0, [eax]"
run_test

set_test_params "${ARCH}" "PAVGB MM0, [EAX]" 0fe000 "pavgb mm0, [eax]"
run_test

set_test_params "${ARCH}" "PAVGW MM0, [EAX]" 0fe300 "pavgw mm0, [eax]"
run_test

set_test_params "${ARCH}" "MOVNTQ [EAX], MM0" 0fe700 "movntq [eax], mm0"
run_test

set_test_params "${ARCH}" "MOVNTDQ [EAX], XMM0" 660fe700 "movntdq [eax], xmm0"
run_test

set_test_params "${ARCH}" "PSUBSB MM0, [EAX]" 0fe800 "psubsb mm0, [eax]"
run_test

set_test_params "${ARCH}" "PSUBSW MM0, [EAX]" 0fe900 "psubsw mm0, [eax]"
run_test

set_test_params "${ARCH}" "PMINSW MM0, [EAX]" 0fea00 "pminsw mm0, [eax]"
run_test

set_test_params "${ARCH}" "PMAXSW MM0, [EAX]" 0fee00 "pmaxsw mm0, [eax]"
run_test

set_test_params "${ARCH}" "PADDSB MM0, [EAX]" 0fec00 "paddsb mm0, [eax]"
run_test

set_test_params "${ARCH}" "PADDSW MM0, [EAX]" 0fed00 "paddsw mm0, [eax]"
run_test

set_test_params "${ARCH}" "PSRAW MM0, [EAX]" 0fe100 "psraw mm0, [eax]"
run_test

set_test_params "${ARCH}" "PSRAD MM0, [EAX]" 0fe200 "psrad mm0, [eax]"
run_test

set_test_params "${ARCH}" "PSRAW XMM0, [EAX]" 660fe100 "psraw xmm0, [eax]"
run_test

set_test_params "${ARCH}" "PSRAD XMM0, [EAX]" 660fe200 "psrad xmm0, [eax]"
run_test

done
