#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done
for ARCH in x86 x86.olly x86.cs; do


# -------------------------------
# VPMADCSSWD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMADCSSWD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878a6c000
pi 1
"
EXPECT="vpmadcsswd xmm0, xmm0, xmm0, xmm0
"
run_test

# -------------------------------
# VFRCZPD XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VFRCZPD XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97881c0
pi 1
"
EXPECT="vfrczpd xmm0, xmm0
"
run_test

# -------------------------------
# VCVTPH2PS XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VCVTPH2PS XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878a0c000
pi 1
"
EXPECT="vcvtph2ps xmm0, xmm0, 0
"
run_test


# -------------------------------
# VCVTPS2PH XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VCVTPS2PH XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878a1c000
pi 1
"
EXPECT="vcvtps2ph xmm0, xmm0, 0
"
run_test


# -------------------------------
# VFRCZPS XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VFRCZPS XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97880c0
pi 1
"
EXPECT="vfrczps xmm0, xmm0
"
run_test


# -------------------------------
# VFRCZSD XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VFRCZSD XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97883c0
pi 1
"
EXPECT="vfrczsd xmm0, xmm0
"
run_test


# -------------------------------
# VFRCZSS XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VFRCZSS XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97882c0
pi 1
"
EXPECT="vfrczss xmm0, xmm0
"
run_test


# -------------------------------
# VPHADDBDXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHADDBDXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978c2c0
pi 1
"
EXPECT="vphaddbdxmm0, xmm0
"
run_test


# -------------------------------
# VPHADDBQXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHADDBQXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978c3c0
pi 1
"
EXPECT="vphaddbqxmm0, xmm0
"
run_test


# -------------------------------
# VPHADDBWXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHADDBWXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978c1c0
pi 1
"
EXPECT="vphaddbwxmm0, xmm0
"
run_test


# -------------------------------
# VPHADDDQXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHADDDQXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978cbc0
pi 1
"
EXPECT="vphadddqxmm0, xmm0
"
run_test


# -------------------------------
# VPHADDWDXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHADDWDXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978c6c0
pi 1
"
EXPECT="vphaddwdxmm0, xmm0
"
run_test


# -------------------------------
# VPHADDWQXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHADDWQXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978c7c0
pi 1
"
EXPECT="vphaddwqxmm0, xmm0
"
run_test


# -------------------------------
# VPHSUBBWXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHSUBBWXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978e1c0
pi 1
"
EXPECT="vphsubbwxmm0, xmm0
"
run_test


# -------------------------------
# VPHSUBDQXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHSUBDQXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978e3c0
pi 1
"
EXPECT="vphsubdqxmm0, xmm0
"
run_test


# -------------------------------
# VPHSUBWDXMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP [VPHSUBWDXMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978e2c0
pi 1
"
EXPECT="vphsubwdxmm0, xmm0
"
run_test


# -------------------------------
# VFMADDPD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDPD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37969c000
pi 1
"
EXPECT="vfmaddpd xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMADDPS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDPS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37968c000
pi 1
"
EXPECT="vfmaddps xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMADDSD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDSD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e3796bc000
pi 1
"
EXPECT="vfmaddsd xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMADDSS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDSS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e3796ac000
pi 1
"
EXPECT="vfmaddss xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMADDPD YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDPD YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d69c000
pi 1
"
EXPECT="vfmaddpd ymm0, ymm0, ymm0, ymm0
"
run_test


# -------------------------------
# VFMADDPS YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDPS YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d68c000
pi 1
"
EXPECT="vfmaddps ymm0, ymm0, ymm0, ymm0
"
run_test


# -------------------------------
# VFMSUBPD YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMSUBPD YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d6dc000
pi 1
"
EXPECT="vfmsubpd ymm0, ymm0, ymm0, ymm0
"
run_test


# -------------------------------
# VFMSUBPS YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMSUBPS YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d6cc000
pi 1
"
EXPECT="vfmsubps ymm0, ymm0, ymm0, ymm0
"
run_test


# -------------------------------
# VFMADDSUBPD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDSUBPD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e3795dc000
pi 1
"
EXPECT="vfmaddsubpd xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMADDSUBPS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDSUBPS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e3795cc000
pi 1
"
EXPECT="vfmaddsubps xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMSUBADDPD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMSUBADDPD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e3795fc000
pi 1
"
EXPECT="vfmsubaddpd xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMSUBADDPS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMSUBADDPS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e3795ec000
pi 1
"
EXPECT="vfmsubaddps xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VFMADDSUBPD YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDSUBPD YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d5dc000
pi 1
"
EXPECT="vfmaddsubpd ymm0, ymm0, ymm0, ymm0
"
run_test


# -------------------------------
# VFMADDSUBPS YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMADDSUBPS YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d5cc000
pi 1
"
EXPECT="vfmaddsubps ymm0, ymm0, ymm0, ymm0
"
run_test


# -------------------------------
# VFMSUBADDPS YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMSUBADDPS YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d5ec000
pi 1
"
EXPECT="vfmsubaddps ymm0, ymm0, ymm0, ymm0
"
run_test


# -------------------------------
# VFMSUBADDPD YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 XOP: [VFMSUBADDPD YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx c4e37d5fc000
pi 1
"
EXPECT="vfmsubaddpd ymm0, ymm0, ymm0, ymm0
"
run_test

# -------------------------------
# VPCMOV XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPCMOV XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878a2c000
pi 1
"
EXPECT="vpcmov xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPCOMB XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMB XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878ccc000
pi 1
"
EXPECT="vpcomb xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPCOMD XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMD XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878cec000
pi 1
"
EXPECT="vpcomd xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPCOMQ XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMQ XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878cfc000
pi 1
"
EXPECT="vpcomq xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPCOMUB XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMUB XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878ecc000
pi 1
"
EXPECT="vpcomub xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPCOMUD XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMUD XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878eec000
pi 1
"
EXPECT="vpcomud xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPCOMUQ XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMUQ XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878efc000
pi 1
"
EXPECT="vpcomuq xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPCOMUW XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMUW XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878edc000
pi 1
"
EXPECT="vpcomuw xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPCOMW XMM0, XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 XOP: [VPCOMW XMM0, XMM0, XMM0, 0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878cdc000
pi 1
"
EXPECT="vpcomw xmm0, xmm0, xmm0, 0
"
run_test


# -------------------------------
# VPMACSDDXMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSDDXMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe8789ec000
pi 1
"
EXPECT="vpmacsddxmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSDQH XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSDQH XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe8789fc000
pi 1
"
EXPECT="vpmacsdqh xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSDQL XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSDQL XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe87897c000
pi 1
"
EXPECT="vpmacsdql xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSSDD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSSDD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe8788ec000
pi 1
"
EXPECT="vpmacssdd xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSSDQH XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSSDQH XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe8788fc000
pi 1
"
EXPECT="vpmacssdqh xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSSDQL XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSSDQL XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe87887c000
pi 1
"
EXPECT="vpmacssdql xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSSWD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSSWD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe87886c000
pi 1
"
EXPECT="vpmacsswd xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSSWW XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSSWW XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe87885c000
pi 1
"
EXPECT="vpmacssww xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSWDXMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSWDXMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe87896c000
pi 1
"
EXPECT="vpmacswdxmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPMACSWWXMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMACSWWXMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe87895c000
pi 1
"
EXPECT="vpmacswwxmm0, xmm0, xmm0, xmm0
"
run_test





# -------------------------------
# VPMADCSWD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMADCSWD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878b6c000
pi 1
"
EXPECT="vpmadcswd xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPPERM XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPPERM XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878a3c000
pi 1
"
EXPECT="vpperm xmm0, xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPROTB XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPROTB XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97890c0
pi 1
"
EXPECT="vprotb xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPROTD XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPROTD XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97892c0
pi 1
"
EXPECT="vprotd xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPROTQ XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPROTQ XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97893c0
pi 1
"
EXPECT="vprotq xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPROTW XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPROTW XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97891c0
pi 1
"
EXPECT="vprotw xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHAB XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHAB XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97898c0
pi 1
"
EXPECT="vpshab xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHAD XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHAD XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe9789ac0
pi 1
"
EXPECT="vpshad xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHAQ XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHAQ XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe9789bc0
pi 1
"
EXPECT="vpshaq xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHAW XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHAW XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97899c0
pi 1
"
EXPECT="vpshaw xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHLB XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHLB XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97894c0
pi 1
"
EXPECT="vpshlb xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHLD XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHLD XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97896c0
pi 1
"
EXPECT="vpshld xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHLQ XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHLQ XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97897c0
pi 1
"
EXPECT="vpshlq xmm0, xmm0, xmm0
"
run_test


# -------------------------------
# VPSHLW XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPSHLW XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe97895c0
pi 1
"
EXPECT="vpshlw xmm0, xmm0, xmm0
"
run_test

# -------------------------------
# VPHADDUBD XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPHADDUBD XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978d2c0
pi 1
"
EXPECT="vphaddubd xmm0, xmm0
"
run_test


# -------------------------------
# VPHADDUBQ XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPHADDUBQ XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978d3c0
pi 1
"
EXPECT="vphaddubq xmm0, xmm0
"
run_test


# -------------------------------
# VPHADDUBW XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPHADDUBW XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978d1c0
pi 1
"
EXPECT="vphaddubw xmm0, xmm0
"
run_test


# -------------------------------
# VPHADDUDQ XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPHADDUDQ XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978dbc0
pi 1
"
EXPECT="vphaddudq xmm0, xmm0
"
run_test


# -------------------------------
# VPHADDUWD XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPHADDUWD XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978d6c0
pi 1
"
EXPECT="vphadduwd xmm0, xmm0
"
run_test


# -------------------------------
# VPHADDUWQ XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPHADDUWQ XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe978d7c0
pi 1
"
EXPECT="vphadduwq xmm0, xmm0
"
run_test


# -------------------------------
# VPMADCSSWD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 XOP: [VPMADCSSWD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS="
e asm.arch=${ARCH}
e asm.bits=32
wx 8fe878a6c000
pi 1
"
EXPECT="vpmadcsswd xmm0, xmm0, xmm0, xmm0
"
run_test

done
