#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# -------------------------------
# MULSD instruction
NAME="x86 SSE: [MULSD]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 66f3f20f59ff
pi 1
'
EXPECT='o16 mulsd xmm7, xmm7
'
run_test

# -------------------------------
# MULSS instruction
NAME="x86 SSE: [MULSS]"
BROKEN=1
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 66f2f0f59ff
pi 1
'
EXPECT='mulss xmm7, xmm7
'
run_test

# -------------------------------
# MULPD instruction
NAME="x86 SSE: [MULPD]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 660f59ff
pi 1
'
EXPECT='mulpd xmm7, xmm7
'
run_test

# -------------------------------
# MULSD instruction
NAME="x86 SSE: [MULSD]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx f2660f59ff
pi 1
'
EXPECT='o16 mulsd xmm7, xmm7
'
run_test

# -------------------------------
# MULPS instruction
NAME="x86 SSE: [MULPS]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=64
wx 0f59ff
pi 1
'
EXPECT='mulps xmm7, xmm7
'
run_test

# -------------------------------
# MPSADBW XMM0, XMM0, 0 instruction
NAME="x86 SSE: [MPSADBW XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a42c000
pi 1
'
EXPECT='mpsadbw xmm0, xmm0, 0x0
'
run_test

# -------------------------------
# PCMPESTRM XMM0, XMM0, 0 instruction
NAME="x86 SSE: [PCMPESTRM XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a60c000
pi 1
'
EXPECT='pcmpestrm xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# PCMPESTRI XMM0, XMM0, 0 instruction
NAME="x86 SSE: [PCMPESTRI XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a61c000
pi 1
'
EXPECT='pcmpestri xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# PCMPISTRM XMM0, XMM0, 0 instruction
NAME="x86 SSE: [PCMPISTRM XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a62c000
pi 1
'
EXPECT='pcmpistrm xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# PCMPISTRI XMM0, XMM0, 0 instruction
NAME="x86 SSE: [PCMPISTRI XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a63c000
pi 1
'
EXPECT='pcmpistri xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# ROUNDPS XMM0, XMM0, 0 instruction
NAME="x86 SSE: [ROUNDPS XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a08c000
pi 1
'
EXPECT='roundps xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# ROUNDPD XMM0, XMM0, 0 instruction
NAME="x86 SSE: [ROUNDPD XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a09c000
pi 1
'
EXPECT='roundpd xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# ROUNDSS XMM0, XMM0, 0 instruction
NAME="x86 SSE: [ROUNDSS XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a0ac000
pi 1
'
EXPECT='roundss xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# ROUNDSD XMM0, XMM0, 0 instruction
NAME="x86 SSE: [ROUNDSD XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a0bc000
pi 1
'
EXPECT='roundsd xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# BLENDPS XMM0, XMM0, 0 instruction
NAME="x86 SSE: [BLENDPS XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a0cc000
pi 1
'
EXPECT='blendps xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# BLENDPD XMM0, XMM0, 0 instruction
NAME="x86 SSE: [BLENDPD XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a0dc000
pi 1
'
EXPECT='blendpd xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# PBLENDW XMM0, XMM0, 0 instruction
NAME="x86 SSE: [PBLENDW XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a0ec000
pi 1
'
EXPECT='pblendw xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# PALIGNR XMM0, XMM0, 0 instruction
NAME="x86 SSE: [PALIGNR XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a0fc000
pi 1
'
EXPECT='palignr xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# PALIGNR MM0, MM0, 0 instruction
NAME="x86 SSE: [PALIGNR MM0, MM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f3a0fc000
pi 1
'
EXPECT='palignr mm0, mm0, 0x0
'
run_test

# -------------------------------
# PSRLW MM0, 0X0 instruction
NAME="x86 SSE: [PSRLW MM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f71d000
pi 1
'
EXPECT='psrlw mm0, 0x0
'
run_test


# -------------------------------
# PSRLD MM0, 0X0 instruction
NAME="x86 SSE: [PSRLD MM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f72d000
pi 1
'
EXPECT='psrld mm0, 0x0
'
run_test


# -------------------------------
# PSRLQ MM0, 0X0 instruction
NAME="x86 SSE: [PSRLQ MM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f73d000
pi 1
'
EXPECT='psrlq mm0, 0x0
'
run_test


# -------------------------------
# PSLLW MM0, 0X0 instruction
NAME="x86 SSE: [PSLLW MM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f71f000
pi 1
'
EXPECT='psllw mm0, 0x0
'
run_test


# -------------------------------
# PSLLQ MM0, 0X0 instruction
NAME="x86 SSE: [PSLLQ MM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f73f000
pi 1
'
EXPECT='psllq mm0, 0x0
'
run_test


# -------------------------------
# PSRLW XMM0, 0X0 instruction
NAME="x86 SSE: [PSRLW XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f71d000
pi 1
'
EXPECT='psrlw xmm0, 0x0
'
run_test


# -------------------------------
# PSRLD XMM0, 0X0 instruction
NAME="x86 SSE: [PSRLD XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f72d000
pi 1
'
EXPECT='psrld xmm0, 0x0
'
run_test


# -------------------------------
# PSRLQ XMM0, 0X0 instruction
NAME="x86 SSE: [PSRLQ XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f73d000
pi 1
'
EXPECT='psrlq xmm0, 0x0
'
run_test


# -------------------------------
# PSLLW XMM0, 0X0 instruction
NAME="x86 SSE: [PSLLW XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f71f000
pi 1
'
EXPECT='psllw xmm0, 0x0
'
run_test


# -------------------------------
# PSLLD XMM0, 0X0 instruction
NAME="x86 SSE: [PSLLD XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f72f000
pi 1
'
EXPECT='pslld xmm0, 0x0
'
run_test


# -------------------------------
# PSLLQ XMM0, 0X0 instruction
NAME="x86 SSE: [PSLLQ XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f73f000
pi 1
'
EXPECT='psllq xmm0, 0x0
'
run_test


# -------------------------------
# PSRLDQ XMM0, 0X0 instruction
NAME="x86 SSE: [PSRLDQ XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f73d800
pi 1
'
EXPECT='psrldq xmm0, 0x0
'
run_test


# -------------------------------
# PSLLDQ XMM0, 0X0 instruction
NAME="x86 SSE: [PSLLDQ XMM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f73f800
pi 1
'
EXPECT='pslldq xmm0, 0x0
'
run_test


# -------------------------------
# SQRTPS XMM0, [EAX] instruction
NAME="x86 SSE: [SQRTPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5100
pi 1
'
EXPECT='sqrtps xmm0, [eax]
'
run_test


# -------------------------------
# SQRTPD XMM0, [EAX] instruction
NAME="x86 SSE: [SQRTPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5100
pi 1
'
EXPECT='sqrtpd xmm0, [eax]
'
run_test


# -------------------------------
# SQRTSD XMM0, [EAX] instruction
NAME="x86 SSE: [SQRTSD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f5100
pi 1
'
EXPECT='sqrtsd xmm0, [eax]
'
run_test


# -------------------------------
# SQRTSS XMM0, [EAX] instruction
NAME="x86 SSE: [SQRTSS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f5100
pi 1
'
EXPECT='sqrtss xmm0, [eax]
'
run_test


# -------------------------------
# RSQRTPS XMM0, [EAX] instruction
NAME="x86 SSE: [RSQRTPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5200
pi 1
'
EXPECT='rsqrtps xmm0, [eax]
'
run_test


# -------------------------------
# RSQRTSS XMM0, [EAX] instruction
NAME="x86 SSE: [RSQRTSS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f5200
pi 1
'
EXPECT='rsqrtss xmm0, [eax]
'
run_test

# -------------------------------
# RCPPS XMM0, [EAX] instruction
NAME="x86 SSE: [RCPPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5300
pi 1
'
EXPECT='rcpps xmm0, [eax]
'
run_test


# -------------------------------
# RCPSS XMM0, [EAX] instruction
NAME="x86 SSE: [RCPSS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f5300
pi 1
'
EXPECT='rcpss xmm0, [eax]
'
run_test


# -------------------------------
# ANDPS XMM0, [EAX] instruction
NAME="x86 SSE: [ANDPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5400
pi 1
'
EXPECT='andps xmm0, [eax]
'
run_test


# -------------------------------
# ANDNPS XMM0, [EAX] instruction
NAME="x86 SSE: [ANDNPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5500
pi 1
'
EXPECT='andnps xmm0, [eax]
'
run_test


# -------------------------------
# ANDPD XMM0, [EAX] instruction
NAME="x86 SSE: [ANDPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f54
pi 1
'
EXPECT='andpd xmm0, [eax]
'
run_test


# -------------------------------
# ANDNPD XMM0, [EAX] instruction
NAME="x86 SSE: [ANDNPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f55
pi 1
'
EXPECT='andnpd xmm0, [eax]
'
run_test


# -------------------------------
# ORPS XMM0, [EAX] instruction
NAME="x86 SSE: [ORPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5600
pi 1
'
EXPECT='orps xmm0, [eax]
'
run_test


# -------------------------------
# XORPS XMM0, [EAX] instruction
NAME="x86 SSE: [XORPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5700
pi 1
'
EXPECT='xorps xmm0, [eax]
'
run_test


# -------------------------------
# ORPD XMM0, [EAX] instruction
NAME="x86 SSE: [ORPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5600
pi 1
'
EXPECT='orpd xmm0, [eax]
'
run_test


# -------------------------------
# XORPD XMM0, [EAX] instruction
NAME="x86 SSE: [XORPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5700
pi 1
'
EXPECT='xorpd xmm0, [eax]
'
run_test

# -------------------------------
# ADDPS XMM0, [EAX] instruction
NAME="x86 SSE: [ADDPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5800
pi 1
'
EXPECT='addps xmm0, [eax]
'
run_test


# -------------------------------
# SUBPS XMM0, [EAX] instruction
NAME="x86 SSE: [SUBPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5c00
pi 1
'
EXPECT='subps xmm0, [eax]
'
run_test


# -------------------------------
# MULPS XMM0, [EAX] instruction
NAME="x86 SSE: [MULPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5900
pi 1
'
EXPECT='mulps xmm0, [eax]
'
run_test


# -------------------------------
# DIVPS XMM0, [EAX] instruction
NAME="x86 SSE: [DIVPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5e00
pi 1
'
EXPECT='divps xmm0, [eax]
'
run_test


# -------------------------------
# ADDPD XMM0, [EAX] instruction
NAME="x86 SSE: [ADDPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5800
pi 1
'
EXPECT='addpd xmm0, [eax]
'
run_test


# -------------------------------
# SUBPD XMM0, [EAX] instruction
NAME="x86 SSE: [SUBPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5c00
pi 1
'
EXPECT='subpd xmm0, [eax]
'
run_test


# -------------------------------
# MULPD XMM0, [EAX] instruction
NAME="x86 SSE: [MULPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5900
pi 1
'
EXPECT='mulpd xmm0, [eax]
'
run_test


# -------------------------------
# DIVPD XMM0, [EAX] instruction
NAME="x86 SSE: [DIVPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5e00
pi 1
'
EXPECT='divpd xmm0, [eax]
'
run_test


# -------------------------------
# MINPS XMM0, [EAX] instruction
NAME="x86 SSE: [MINPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5d00
pi 1
'
EXPECT='minps xmm0, [eax]
'
run_test


# -------------------------------
# MAXPS XMM0, [EAX] instruction
NAME="x86 SSE: [MAXPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5f00
pi 1
'
EXPECT='maxps xmm0, [eax]
'
run_test


# -------------------------------
# MINPD XMM0, [EAX] instruction
NAME="x86 SSE: [MINPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5d00
pi 1
'
EXPECT='minpd xmm0, [eax]
'
run_test


# -------------------------------
# MAXPD XMM0, [EAX] instruction
NAME="x86 SSE: [MAXPD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5f00
pi 1
'
EXPECT='maxpd xmm0, [eax]
'
run_test


# -------------------------------
# MINSD XMM0, QWORD [EAX] instruction
NAME="x86 SSE: [MINSD XMM0, QWORD [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f5d00
pi 1
'
EXPECT='minsd xmm0, qword [eax]
'
run_test


# -------------------------------
# MAXSD XMM0, [EAX] instruction
NAME="x86 SSE: [MAXSD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f5f00
pi 1
'
EXPECT='maxsd xmm0, [eax]
'
run_test


# -------------------------------
# MINSS XMM0, DWORD [EAX] instruction
NAME="x86 SSE: [MINSS XMM0, DWORD [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f5d00
pi 1
'
EXPECT='minss xmm0, dword [eax]
'
run_test


# -------------------------------
# MAXSS XMM0, [EAX] instruction
NAME="x86 SSE: [MAXSS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f5f00
pi 1
'
EXPECT='maxss xmm0, [eax]
'
run_test


# -------------------------------
# PUNPCKLBW MM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKLBW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6000
pi 1
'
EXPECT='punpcklbw mm0, [eax]
'
run_test


# -------------------------------
# PUNPCKLWD MM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKLWD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6100
pi 1
'
EXPECT='punpcklwd mm0, [eax]
'
run_test


# -------------------------------
# PUNPCKLDQ MM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKLDQ MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6200
pi 1
'
EXPECT='punpckldq mm0, [eax]
'
run_test


# -------------------------------
# PUNPCKLBW XMM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKLBW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6000
pi 1
'
EXPECT='punpcklbw xmm0, [eax]
'
run_test


# -------------------------------
# PUNPCKLWD XMM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKLWD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6100
pi 1
'
EXPECT='punpcklwd xmm0, [eax]
'
run_test


# -------------------------------
# PUNPCKLDQ XMM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKLDQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6200
pi 1
'
EXPECT='punpckldq xmm0, [eax]
'
run_test


# -------------------------------
# PACKSSWB MM0, [EAX] instruction
NAME="x86 SSE: [PACKSSWB MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6300
pi 1
'
EXPECT='packsswb mm0, [eax]
'
run_test


# -------------------------------
# PACKUSWB MM0, [EAX] instruction
NAME="x86 SSE: [PACKUSWB MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6700
pi 1
'
EXPECT='packuswb mm0, [eax]
'
run_test


# -------------------------------
# PACKSSWB XMM0, [EAX] instruction
NAME="x86 SSE: [PACKSSWB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6300
pi 1
'
EXPECT='packsswb xmm0, [eax]
'
run_test


# -------------------------------
# PACKUSWB XMM0, [EAX] instruction
NAME="x86 SSE: [PACKUSWB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6700
pi 1
'
EXPECT='packuswb xmm0, [eax]
'
run_test


# -------------------------------
# PCMPGTB MM0, [EAX] instruction
NAME="x86 SSE: [PCMPGTB MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6400
pi 1
'
EXPECT='pcmpgtb mm0, [eax]
'
run_test


# -------------------------------
# PCMPGTW MM0, [EAX] instruction
NAME="x86 SSE: [PCMPGTW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6500
pi 1
'
EXPECT='pcmpgtw mm0, [eax]
'
run_test


# -------------------------------
# PCMPGTD MM0, [EAX] instruction
NAME="x86 SSE: [PCMPGTD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6600
pi 1
'
EXPECT='pcmpgtd mm0, [eax]
'
run_test


# -------------------------------
# PCMPGTB XMM0, [EAX] instruction
NAME="x86 SSE: [PCMPGTB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6400
pi 1
'
EXPECT='pcmpgtb xmm0, [eax]
'
run_test


# -------------------------------
# PCMPGTW XMM0, [EAX] instruction
NAME="x86 SSE: [PCMPGTW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6500
pi 1
'
EXPECT='pcmpgtw xmm0, [eax]
'
run_test


# -------------------------------
# PCMPGTD XMM0, [EAX] instruction
NAME="x86 SSE: [PCMPGTD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6600
pi 1
'
EXPECT='pcmpgtd xmm0, [eax]
'
run_test


# -------------------------------
# PUNPCKHBW MM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKHBW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6800
pi 1
'
EXPECT='punpckhbw mm0, [eax]
'
run_test


# -------------------------------
# PUNPCKHWD MM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKHWD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6900
pi 1
'
EXPECT='punpckhwd mm0, [eax]
'
run_test


# -------------------------------
# PUNPCKHDQ MM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKHDQ MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6a00
pi 1
'
EXPECT='punpckhdq mm0, [eax]
'
run_test


# -------------------------------
# PUNPCKHBW XMM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKHBW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6800
pi 1
'
EXPECT='punpckhbw xmm0, [eax]
'
run_test


# -------------------------------
# PUNPCKHWD XMM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKHWD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6900
pi 1
'
EXPECT='punpckhwd xmm0, [eax]
'
run_test


# -------------------------------
# PUNPCKHDQ XMM0, [EAX] instruction
NAME="x86 SSE: [PUNPCKHDQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6a00
pi 1
'
EXPECT='punpckhdq xmm0, [eax]
'
run_test


# -------------------------------
# PACKSSDW MM0, [EAX] instruction
NAME="x86 SSE: [PACKSSDW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6b00
pi 1
'
EXPECT='packssdw mm0, [eax]
'
run_test


# -------------------------------
# PACKSSDW XMM0, [EAX] instruction
NAME="x86 SSE: [PACKSSDW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6b00
pi 1
'
EXPECT='packssdw xmm0, [eax]
'
run_test


# -------------------------------
# PSHUFB MM0, [EAX] instruction
NAME="x86 SSE: [PSHUFB MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f380000
pi 1
'
EXPECT='pshufb mm0, [eax]
'
run_test


# -------------------------------
# PSHUFW MM0, [EAX], 0X0 instruction
NAME="x86 SSE: [PSHUFW MM0, [EAX], 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f700000
pi 1
'
EXPECT='pshufw mm0, [eax], 0x0
'
run_test


# -------------------------------
# PSHUFB XMM0, [EAX] instruction
NAME="x86 SSE: [PSHUFB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f380000
pi 1
'
EXPECT='pshufb xmm0, [eax]
'
run_test


# -------------------------------
# PSHUFD XMM0, [EAX], 0X0 instruction
NAME="x86 SSE: [PSHUFD XMM0, [EAX], 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f700000
pi 1
'
EXPECT='pshufd xmm0, [eax], 0x0
'
run_test


# -------------------------------
# PSHUFLW XMM0, [EAX], 0X0 instruction
NAME="x86 SSE: [PSHUFLW XMM0, [EAX], 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f700000
pi 1
'
EXPECT='pshuflw xmm0, [eax], 0x0
'
run_test


# -------------------------------
# PSHUFHW XMM0, [EAX], 0X0 instruction
NAME="x86 SSE: [PSHUFHW XMM0, [EAX], 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f7000 00
pi 1
'
EXPECT='pshufhw xmm0, [eax], 0x0
'
run_test


# -------------------------------
# PCMPEQB MM0, [EAX] instruction
NAME="x86 SSE: [PCMPEQB MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f7400
pi 1
'
EXPECT='pcmpeqb mm0, [eax]
'
run_test


# -------------------------------
# PCMPEQW MM0, [EAX] instruction
NAME="x86 SSE: [PCMPEQW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f7500
pi 1
'
EXPECT='pcmpeqw mm0, [eax]
'
run_test


# -------------------------------
# PCMPEQD MM0, [EAX] instruction
NAME="x86 SSE: [PCMPEQD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f7600
pi 1
'
EXPECT='pcmpeqd mm0, [eax]
'
run_test


# -------------------------------
# PCMPEQB XMM0, [EAX] instruction
NAME="x86 SSE: [PCMPEQB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f7400
pi 1
'
EXPECT='pcmpeqb xmm0, [eax]
'
run_test


# -------------------------------
# PCMPEQW XMM0, [EAX] instruction
NAME="x86 SSE: [PCMPEQW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f7500
pi 1
'
EXPECT='pcmpeqw xmm0, [eax]
'
run_test


# -------------------------------
# PCMPEQD XMM0, [EAX] instruction
NAME="x86 SSE: [PCMPEQD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f7600
pi 1
'
EXPECT='pcmpeqd xmm0, [eax]
'
run_test


# -------------------------------
# MOVD MM0, DWORD [EAX] instruction
NAME="x86 SSE: [MOVD MM0, DWORD [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6e00
pi 1
'
EXPECT='movd mm0, dword [eax]
'
run_test


# -------------------------------
# MOVQ MM0, [EAX] instruction
NAME="x86 SSE: [MOVQ MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f6f00
pi 1
'
EXPECT='movq mm0, [eax]
'
run_test


# -------------------------------
# MOVD DWORD [EAX], MM0 instruction
NAME="x86 SSE: [MOVD DWORD [EAX], MM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f7e00
pi 1
'
EXPECT='movd dword [eax], mm0
'
run_test


# -------------------------------
# MOVQ [EAX], MM0 instruction
NAME="x86 SSE: [MOVQ [EAX], MM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f7f00
pi 1
'
EXPECT='movq [eax], mm0
'
run_test


# -------------------------------
# MOVD XMM0, DWORD [EAX] instruction
NAME="x86 SSE: [MOVD XMM0, DWORD [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6e00
pi 1
'
EXPECT='movd xmm0, dword [eax]
'
run_test


# -------------------------------
# MOVDQA XMM0, [EAX] instruction
NAME="x86 SSE: [MOVDQA XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f6f00
pi 1
'
EXPECT='movdqa xmm0, [eax]
'
run_test


# -------------------------------
# MOVD DWORD [EAX], XMM0 instruction
NAME="x86 SSE: [MOVD DWORD [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f7e00
pi 1
'
EXPECT='movd dword [eax], xmm0
'
run_test


# -------------------------------
# MOVDQA [EAX], XMM0 instruction
NAME="x86 SSE: [MOVDQA [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f7f00
pi 1
'
EXPECT='movdqa [eax], xmm0
'
run_test


# -------------------------------
# MOVDQU XMM0, [EAX] instruction
NAME="x86 SSE: [MOVDQU XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f6f00
pi 1
'
EXPECT='movdqu xmm0, [eax]
'
run_test


# -------------------------------
# MOVQ XMM0, [EAX] instruction
NAME="x86 SSE: [MOVQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f7e00
pi 1
'
EXPECT='movq xmm0, [eax]
'
run_test


# -------------------------------
# MOVDQU [EAX], XMM0 instruction
NAME="x86 SSE: [MOVDQU [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f7f00
pi 1
'
EXPECT='movdqu [eax], xmm0
'
run_test


# -------------------------------
# PMOVSXBW XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVSXBW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3820c0
pi 1
'
EXPECT='pmovsxbw xmm0, xmm0
'
run_test


# -------------------------------
# PMOVSXBD XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVSXBD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3821c0
pi 1
'
EXPECT='pmovsxbd xmm0, xmm0
'
run_test


# -------------------------------
# PMOVSXBQ XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVSXBQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3822c0
pi 1
'
EXPECT='pmovsxbq xmm0, xmm0
'
run_test


# -------------------------------
# PMOVSXWD XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVSXWD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3823c0
pi 1
'
EXPECT='pmovsxwd xmm0, xmm0
'
run_test


# -------------------------------
# PMOVSXWQ XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVSXWQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3824c0
pi 1
'
EXPECT='pmovsxwq xmm0, xmm0
'
run_test


# -------------------------------
# PMOVSXDQ XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVSXDQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3825c0
pi 1
'
EXPECT='pmovsxdq xmm0, xmm0
'
run_test


# -------------------------------
# PMOVZXBW XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVZXBW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3830c0
pi 1
'
EXPECT='pmovzxbw xmm0, xmm0
'
run_test


# -------------------------------
# PMOVZXBD XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVZXBD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3831c0
pi 1
'
EXPECT='pmovzxbd xmm0, xmm0
'
run_test


# -------------------------------
# PMOVZXBQ XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVZXBQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3832c0
pi 1
'
EXPECT='pmovzxbq xmm0, xmm0
'
run_test


# -------------------------------
# PMOVZXWD XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVZXWD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3833c0
pi 1
'
EXPECT='pmovzxwd xmm0, xmm0
'
run_test


# -------------------------------
# PMOVZXWQ XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVZXWQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3834c0
pi 1
'
EXPECT='pmovzxwq xmm0, xmm0
'
run_test


# -------------------------------
# PMOVZXDQ XMM0, XMM0 instruction
NAME="x86 SSE: [PMOVZXDQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3835c0
pi 1
'
EXPECT='pmovzxdq xmm0, xmm0
'
run_test


# -------------------------------
# PMINSB XMM0, XMM0 instruction
NAME="x86 SSE: [PMINSB XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3838c0
pi 1
'
EXPECT='pminsb xmm0, xmm0
'
run_test


# -------------------------------
# PMINSD XMM0, XMM0 instruction
NAME="x86 SSE: [PMINSD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3839c0
pi 1
'
EXPECT='pminsd xmm0, xmm0
'
run_test


# -------------------------------
# PMINUW XMM0, XMM0 instruction
NAME="x86 SSE: [PMINUW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f383ac0
pi 1
'
EXPECT='pminuw xmm0, xmm0
'
run_test


# -------------------------------
# PMINUD XMM0, XMM0 instruction
NAME="x86 SSE: [PMINUD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f383bc0
pi 1
'
EXPECT='pminud xmm0, xmm0
'
run_test


# -------------------------------
# PMAXSB XMM0, XMM0 instruction
NAME="x86 SSE: [PMAXSB XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f383cc0
pi 1
'
EXPECT='pmaxsb xmm0, xmm0
'
run_test


# -------------------------------
# PMAXSD XMM0, XMM0 instruction
NAME="x86 SSE: [PMAXSD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f383dc0
pi 1
'
EXPECT='pmaxsd xmm0, xmm0
'
run_test


# -------------------------------
# PMAXUW XMM0, XMM0 instruction
NAME="x86 SSE: [PMAXUW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f383ec0
pi 1
'
EXPECT='pmaxuw xmm0, xmm0
'
run_test


# -------------------------------
# PMAXUD XMM0, XMM0 instruction
NAME="x86 SSE: [PMAXUD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f383fc0
pi 1
'
EXPECT='pmaxud xmm0, xmm0
'
run_test


# -------------------------------
# PSIGNB XMM0, XMM0 instruction
NAME="x86 SSE: [PSIGNB XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3808c0
pi 1
'
EXPECT='psignb xmm0, xmm0
'
run_test


# -------------------------------
# PSIGNW XMM0, XMM0 instruction
NAME="x86 SSE: [PSIGNW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3809c0
pi 1
'
EXPECT='psignw xmm0, xmm0
'
run_test


# -------------------------------
# PSIGND XMM0, XMM0 instruction
NAME="x86 SSE: [PSIGND XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f380ac0
pi 1
'
EXPECT='psignd xmm0, xmm0
'
run_test


# -------------------------------
# PMULHRSW XMM0, XMM0 instruction
NAME="x86 SSE: [PMULHRSW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f380bc0
pi 1
'
EXPECT='pmulhrsw xmm0, xmm0
'
run_test


# -------------------------------
# PABSB XMM0, XMM0 instruction
NAME="x86 SSE: [PABSB XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f381cc0
pi 1
'
EXPECT='pabsb xmm0, xmm0
'
run_test


# -------------------------------
# PABSW XMM0, XMM0 instruction
NAME="x86 SSE: [PABSW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f381dc0
pi 1
'
EXPECT='pabsw xmm0, xmm0
'
run_test


# -------------------------------
# PABSD XMM0, XMM0 instruction
NAME="x86 SSE: [PABSD XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f381ec0
pi 1
'
EXPECT='pabsd xmm0, xmm0
'
run_test


# -------------------------------
# PMULDQ XMM0, XMM0 instruction
NAME="x86 SSE: [PMULDQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3828c0
pi 1
'
EXPECT='pmuldq xmm0, xmm0
'
run_test


# -------------------------------
# PCMPEQQ XMM0, XMM0 instruction
NAME="x86 SSE: [PCMPEQQ XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3829c0
pi 1
'
EXPECT='pcmpeqq xmm0, xmm0
'
run_test


# -------------------------------
# MOVNTDQA XMM0, [EAX] instruction
NAME="x86 SSE: [MOVNTDQA XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f382a00
pi 1
'
EXPECT='movntdqa xmm0, [eax]
'
run_test


# -------------------------------
# PACKUSDW XMM0, XMM0 instruction
NAME="x86 SSE: [PACKUSDW XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f382bc0
pi 1
'
EXPECT='packusdw xmm0, xmm0
'
run_test


# -------------------------------
# EXTRACTPS EAX, XMM0, 0 instruction
NAME="x86 SSE: [EXTRACTPS EAX, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a17c000
pi 1
'
EXPECT='extractps eax, xmm0, 0x0
'
run_test


# -------------------------------
# PINSRB XMM0, EAX, 0 instruction
NAME="x86 SSE: [PINSRB XMM0, EAX, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a20c000
pi 1
'
EXPECT='pinsrb xmm0, eax, 0x0
'
run_test


# -------------------------------
# INSERTPS XMM0, XMM0, 0 instruction
BROKEN=1
NAME="x86 SSE: [INSERTPS XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a21c000
pi 1
'
EXPECT='insertps xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# DPPS XMM0, XMM0, 0 instruction
NAME="x86 SSE: [DPPS XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a40c000
pi 1
'
EXPECT='dpps xmm0, xmm0, 0x0
'
run_test


# -------------------------------
# DPPD XMM0, XMM0, 0 instruction
NAME="x86 SSE: [DPPD XMM0, XMM0, 0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f3a41c000
pi 1
'
EXPECT='dppd xmm0, xmm0, 0x0
'
run_test



# -------------------------------
# PSLLD MM0, 0X0 instruction
NAME="x86 SSE:[PSLLD MM0, 0X0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f72f000
pi 1
'
EXPECT='pslld mm0, 0x0
'
run_test


# -------------------------------
# MOVUPS XMM0, [EAX] instruction
NAME="x86 SSE:[MOVUPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f10
pi 1
'
EXPECT='movups xmm0, [eax]
'
run_test


# -------------------------------
# MOVUPS [EAX], XMM0 instruction
NAME="x86 SSE:[MOVUPS [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f11
pi 1
'
EXPECT='movups [eax], xmm0
'
run_test


# -------------------------------
# UNPCKLPS XMM0, [EAX] instruction
NAME="x86 SSE:[UNPCKLPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f14
pi 1
'
EXPECT='unpcklps xmm0, [eax]
'
run_test


# -------------------------------
# UNPCKHPS XMM0, [EAX] instruction
NAME="x86 SSE:[UNPCKHPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f15
pi 1
'
EXPECT='unpckhps xmm0, [eax]
'
run_test


# -------------------------------
# MOVLPS XMM0, [EAX] instruction
NAME="x86 SSE:[MOVLPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f12
pi 1
'
EXPECT='movlps xmm0, [eax]
'
run_test


# -------------------------------
# MOVLPS [EAX], XMM0 instruction
NAME="x86 SSE:[MOVLPS [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f13
pi 1
'
EXPECT='movlps [eax], xmm0
'
run_test


# -------------------------------
# MOVHLPS XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE:[MOVHLPS XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f12
pi 1
'
EXPECT='movhlps xmm0, xmm0
'
run_test


# -------------------------------
# MOVLHPS XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE:[MOVLHPS XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f16
pi 1
'
EXPECT='movlhps xmm0, xmm0
'
run_test


# -------------------------------
# MOVHPS XMM0, [EAX] instruction
NAME="x86 SSE:[MOVHPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f16
pi 1
'
EXPECT='movhps xmm0, [eax]
'
run_test


# -------------------------------
# MOVHPS [EAX], XMM0 instruction
NAME="x86 SSE:[MOVHPS [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f17
pi 1
'
EXPECT='movhps [eax], xmm0
'
run_test


# -------------------------------
# MOVMSKPS EAX, XMM0 instruction
NAME="x86 SSE:[MOVMSKPS EAX, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f50c0
pi 1
'
EXPECT='movmskps eax, xmm0
'
run_test


# -------------------------------
# MOVMSKPD EAX, XMM0 instruction
NAME="x86 SSE:[MOVMSKPD EAX, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f50c0
pi 1
'
EXPECT='movmskpd eax, xmm0
'
run_test

# -------------------------------
# VFMSUBPD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFMSUBPD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3796dc000
pi 1
'
EXPECT='vfmsubpd xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFMSUBPS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFMSUBPS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3796cc000
pi 1
'
EXPECT='vfmsubps xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFMSUBSD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFMSUBSD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3796fc000
pi 1
'
EXPECT='vfmsubsd xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFMSUBSS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFMSUBSS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3796ec000
pi 1
'
EXPECT='vfmsubss xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMADDPD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMADDPD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e37979c000
pi 1
'
EXPECT='vfnmaddpd xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMADDPS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMADDPS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e37978c000
pi 1
'
EXPECT='vfnmaddps xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMADDSD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMADDSD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797bc000
pi 1
'
EXPECT='vfnmaddsd xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMADDSS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMADDSS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797ac000
pi 1
'
EXPECT='vfnmaddss xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMADDPD YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMADDPD YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e37d79c000
pi 1
'
EXPECT='vfnmaddpd ymm0, ymm0, ymm0, ymm0
'
run_test


# -------------------------------
# VFNMADDPS YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMADDPS YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e37d78c000
pi 1
'
EXPECT='vfnmaddps ymm0, ymm0, ymm0, ymm0
'
run_test


# -------------------------------
# VFNMSUBPD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBPD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797dc000
pi 1
'
EXPECT='vfnmsubpd xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMSUBPS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBPS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797cc000
pi 1
'
EXPECT='vfnmsubps xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMSUBSD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBSD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797fc000
pi 1
'
EXPECT='vfnmsubsd xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMSUBSS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBSS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797ec000
pi 1
'
EXPECT='vfnmsubss xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMSUBPD YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBPD YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e37d7dc000
pi 1
'
EXPECT='vfnmsubpd ymm0, ymm0, ymm0, ymm0
'
run_test


# -------------------------------
# VFNMSUBPS YMM0, YMM0, YMM0, YMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBPS YMM0, YMM0, YMM0, YMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e37d7cc000
pi 1
'
EXPECT='vfnmsubps ymm0, ymm0, ymm0, ymm0
'
run_test


# -------------------------------
# VFNMSUBSS XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBSS XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797ec000
pi 1
'
EXPECT='vfnmsubss xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# VFNMSUBSD XMM0, XMM0, XMM0, XMM0 instruction
BROKEN=1
NAME="x86 SSE: [VFNMSUBSD XMM0, XMM0, XMM0, XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx c4e3797fc000
pi 1
'
EXPECT='vfnmsubsd xmm0, xmm0, xmm0, xmm0
'
run_test


# -------------------------------
# MOVSD XMM0, [EAX] instruction
NAME="x86 SSE: [MOVSD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f1000
pi 1
'
EXPECT='movsd xmm0, qword [eax]
'
run_test


# -------------------------------
# MOVSD [EAX], XMM0 instruction
NAME="x86 SSE: [MOVSD [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f1100
pi 1
'
EXPECT='movsd [eax], xmm0
'
run_test


# -------------------------------
# MOVDDUP XMM0, [EAX] instruction
NAME="x86 SSE: [MOVDDUP XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f1200
pi 1
'
EXPECT='movddup xmm0, [eax]
'
run_test


# -------------------------------
# CVTPS2PD XMM0, [EAX] instruction
NAME="x86 SSE: [CVTPS2PD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5a00
pi 1
'
EXPECT='cvtps2pd xmm0, [eax]
'
run_test


# -------------------------------
# CVTPD2PS XMM0, [EAX] instruction
NAME="x86 SSE: [CVTPD2PS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5a00
pi 1
'
EXPECT='cvtpd2ps xmm0, [eax]
'
run_test


# -------------------------------
# CVTSD2SS XMM0, [EAX] instruction
NAME="x86 SSE: [CVTSD2SS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f5a00
pi 1
'
EXPECT='cvtsd2ss xmm0, [eax]
'
run_test


# -------------------------------
# CVTSS2SD XMM0, [EAX] instruction
NAME="x86 SSE: [CVTSS2SD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f5a00
pi 1
'
EXPECT='cvtss2sd xmm0, [eax]
'
run_test


# -------------------------------
# CVTDQ2PS XMM0, [EAX] instruction
NAME="x86 SSE: [CVTDQ2PS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f5b00
pi 1
'
EXPECT='cvtdq2ps xmm0, [eax]
'
run_test

# -------------------------------
# CVTPS2DQ XMM0, [EAX] instruction
NAME="x86 SSE: [CVTPS2DQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f5b00
pi 1
'
EXPECT='cvtps2dq xmm0, [eax]
'
run_test


# -------------------------------
# CVTTPS2DQ XMM0, [EAX] instruction
NAME="x86 SSE: [CVTTPS2DQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f5b00
pi 1
'
EXPECT='cvttps2dq xmm0, [eax]
'
run_test


# -------------------------------
# CVTTPD2DQ XMM0, [EAX] instruction
NAME="x86 SSE: [CVTTPD2DQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fe600
pi 1
'
EXPECT='cvttpd2dq xmm0, [eax]
'
run_test


# -------------------------------
# CVTPD2DQ XMM0, [EAX] instruction
NAME="x86 SSE: [CVTPD2DQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20fe600
pi 1
'
EXPECT='cvtpd2dq xmm0, [eax]
'
run_test


# -------------------------------
# CVTDQ2PD XMM0, [EAX] instruction
NAME="x86 SSE: [CVTDQ2PD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30fe600
pi 1
'
EXPECT='cvtdq2pd xmm0, [eax]
'
run_test


# -------------------------------
# CVTTPS2PI MM0, oword [EAX] instruction
NAME="x86 SSE: [CVTTPS2PI MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2c00
pi 1
'
EXPECT='cvttps2pi mm0, oword [eax]
'
run_test

# -------------------------------
# CVTTPD2PI MM0, oword [EAX] instruction
NAME="x86 SSE: [CVTTPD2PI MM0, oword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f2c00
pi 1
'
EXPECT='cvttpd2pi mm0, oword [eax]
'
run_test


# -------------------------------
# CVTTSD2SI EAX, qword [EAX] instruction
NAME="x86 SSE: [CVTTSD2SI EAX, qword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f2c00
pi 1
'
EXPECT='cvttsd2si eax, qword [eax]
'
run_test


# -------------------------------
# CVTTSS2SI EAX, [EAX] instruction
NAME="x86 SSE: [CVTTSS2SI EAX, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f2c00
pi 1
'
EXPECT='cvttss2si eax, [eax]
'
run_test


# -------------------------------
# CVTPI2PS XMM0, qword [EAX] instruction
NAME="x86 SSE: [CVTPI2PS XMM0, qword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2a00
pi 1
'
EXPECT='cvtpi2ps xmm0, qword [eax]
'
run_test


# -------------------------------
# CVTPI2PD XMM0, qword [EAX] instruction
NAME="x86 SSE: [CVTPI2PD XMM0, qword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f2a00
pi 1
'
EXPECT='cvtpi2pd xmm0, qword [eax]
'
run_test


# -------------------------------
# CVTSI2SD XMM0, dword [EAX] instruction
NAME="x86 SSE: [CVTSI2SD XMM0, dword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f2a00
pi 1
'
EXPECT='cvtsi2sd xmm0, dword [eax]
'
run_test


# -------------------------------
# CVTSI2SS XMM0, dword [EAX] instruction
NAME="x86 SSE: [CVTSI2SS XMM0, dword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f2a00
pi 1
'
EXPECT='cvtsi2ss xmm0, dword [eax]
'
run_test


# -------------------------------
# CVTPS2PI MM0, [EAX] instruction
NAME="x86 SSE: [CVTPS2PI MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2d00
pi 1
'
EXPECT='cvtps2pi mm0, [eax]
'
run_test


# -------------------------------
# CVTSD2SI EAX, qword [EAX] instruction
NAME="x86 SSE: [CVTSD2SI EAX, qword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f20f2d00
pi 1
'
EXPECT='cvtsd2si eax, qword [eax]
'
run_test


# -------------------------------
# CVTSS2SI EAX, [EAX] instruction
NAME="x86 SSE: [CVTSS2SI EAX, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx f30f2d00
pi 1
'
EXPECT='cvtss2si eax, [eax]
'
run_test


# -------------------------------
# CVTPD2PI MM0, oword [EAX] instruction
NAME="x86 SSE: [CVTPD2PI MM0, oword [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f2d00
pi 1
'
EXPECT='cvtpd2pi mm0, oword [eax]
'
run_test


# -------------------------------
# MOVAPS XMM0, [EAX] instruction
NAME="x86 SSE: [MOVAPS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2800
pi 1
'
EXPECT='movaps xmm0, [eax]
'
run_test


# -------------------------------
# MOVAPS [EAX], XMM0 instruction
NAME="x86 SSE: [MOVAPS [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2900
pi 1
'
EXPECT='movaps [eax], xmm0
'
run_test


# -------------------------------
# MOVNTPS [EAX], XMM0 instruction
NAME="x86 SSE: [MOVNTPS [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2b00
pi 1
'
EXPECT='movntps [eax], xmm0
'
run_test



# -------------------------------
# MOVNTPD [EAX], XMM0 instruction
NAME="x86 SSE: [MOVNTPD [EAX], XMM0]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f2b00
pi 1
'
EXPECT='movntpd [eax], xmm0
'
run_test


# -------------------------------
# UCOMISS XMM0, [EAX] instruction
NAME="x86 SSE: [UCOMISS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2e00
pi 1
'
EXPECT='ucomiss xmm0, [eax]
'
run_test


# -------------------------------
# COMISS XMM0, [EAX] instruction
NAME="x86 SSE: [COMISS XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0f2f00
pi 1
'
EXPECT='comiss xmm0, [eax]
'
run_test


# -------------------------------
# UCOMISD XMM0, [EAX] instruction
NAME="x86 SSE: [UCOMISD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f2e00
pi 1
'
EXPECT='ucomisd xmm0, [eax]
'
run_test


# -------------------------------
# COMISD XMM0, [EAX] instruction
NAME="x86 SSE: [COMISD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660f2f00
pi 1
'
EXPECT='comisd xmm0, [eax]
'
run_test

# -------------------------------
# PSUBB MM0, [EAX] instruction
NAME="x86 SSE: [PSUBB MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff800
pi 1
'
EXPECT='psubb mm0, [eax]
'
run_test


# -------------------------------
# PSUBW MM0, [EAX] instruction
NAME="x86 SSE: [PSUBW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff900
pi 1
'
EXPECT='psubw mm0, [eax]
'
run_test


# -------------------------------
# PSUBD MM0, [EAX] instruction
NAME="x86 SSE: [PSUBD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ffa00
pi 1
'
EXPECT='psubd mm0, [eax]
'
run_test


# -------------------------------
# PSUBQ MM0, [EAX] instruction
NAME="x86 SSE: [PSUBQ MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ffb00
pi 1
'
EXPECT='psubq mm0, [eax]
'
run_test


# -------------------------------
# PADDB MM0, [EAX] instruction
NAME="x86 SSE: [PADDB MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ffc00
pi 1
'
EXPECT='paddb mm0, [eax]
'
run_test


# -------------------------------
# PADDW MM0, [EAX] instruction
NAME="x86 SSE: [PADDW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ffd00
pi 1
'
EXPECT='paddw mm0, [eax]
'
run_test


# -------------------------------
# PADDD MM0, [EAX] instruction
NAME="x86 SSE: [PADDD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ffe00
pi 1
'
EXPECT='paddd mm0, [eax]
'
run_test

# -------------------------------
# PSRLW MM0, [EAX] instruction
NAME="x86 SSE: [PSRLW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0fd100
pi 1
'
EXPECT='psrlw mm0, [eax]
'
run_test


# -------------------------------
# PSRLD MM0, [EAX] instruction
NAME="x86 SSE: [PSRLD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0fd200
pi 1
'
EXPECT='psrld mm0, [eax]
'
run_test


# -------------------------------
# PSRLQ MM0, [EAX] instruction
NAME="x86 SSE: [PSRLQ MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0fd300
pi 1
'
EXPECT='psrlq mm0, [eax]
'
run_test


# -------------------------------
# PSRLW XMM0, [EAX] instruction
NAME="x86 SSE: [PSRLW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fd100
pi 1
'
EXPECT='psrlw xmm0, [eax]
'
run_test


# -------------------------------
# PSRLD XMM0, [EAX] instruction
NAME="x86 SSE: [PSRLD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fd200
pi 1
'
EXPECT='psrld xmm0, [eax]
'
run_test


# -------------------------------
# PSRLQ XMM0, [EAX] instruction
NAME="x86 SSE: [PSRLQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fd300
pi 1
'
EXPECT='psrlq xmm0, [eax]
'
run_test


# -------------------------------
# PSLLW MM0, [EAX] instruction
NAME="x86 SSE: [PSLLW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff100
pi 1
'
EXPECT='psllw mm0, [eax]
'
run_test


# -------------------------------
# PSLLD MM0, [EAX] instruction
NAME="x86 SSE: [PSLLD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff200
pi 1
'
EXPECT='pslld mm0, [eax]
'
run_test


# -------------------------------
# PSLLQ MM0, [EAX] instruction
NAME="x86 SSE: [PSLLQ MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff300
pi 1
'
EXPECT='psllq mm0, [eax]
'
run_test


# -------------------------------
# PSLLW XMM0, [EAX] instruction
NAME="x86 SSE: [PSLLW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff100
pi 1
'
EXPECT='psllw xmm0, [eax]
'
run_test


# -------------------------------
# PSLLD XMM0, [EAX] instruction
NAME="x86 SSE: [PSLLD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff200
pi 1
'
EXPECT='pslld xmm0, [eax]
'
run_test


# -------------------------------
# PSLLQ XMM0, [EAX] instruction
NAME="x86 SSE: [PSLLQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff300
pi 1
'
EXPECT='psllq xmm0, [eax]
'
run_test


# -------------------------------
# PMULLW MM0, [EAX] instruction
NAME="x86 SSE: [PMULLW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0fd500
pi 1
'
EXPECT='pmullw mm0, [eax]
'
run_test


# -------------------------------
# PMULLW XMM0, [EAX] instruction
NAME="x86 SSE: [PMULLW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fd500
pi 1
'
EXPECT='pmullw xmm0, [eax]
'
run_test


# -------------------------------
# PMULHUW MM0, [EAX] instruction
NAME="x86 SSE: [PMULHUW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0fe400
pi 1
'
EXPECT='pmulhuw mm0, [eax]
'
run_test


# -------------------------------
# PMULHUW XMM0, [EAX] instruction
NAME="x86 SSE: [PMULHUW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fe400
pi 1
'
EXPECT='pmulhuw xmm0, [eax]
'
run_test


# -------------------------------
# PMULHW MM0, [EAX] instruction
NAME="x86 SSE: [PMULHW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0fe500
pi 1
'
EXPECT='pmulhw mm0, [eax]
'
run_test


# -------------------------------
# PMULHW XMM0, [EAX] instruction
NAME="x86 SSE: [PMULHW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fe500
pi 1
'
EXPECT='pmulhw xmm0, [eax]
'
run_test


# -------------------------------
# PMULUDQ MM0, [EAX] instruction
NAME="x86 SSE: [PMULUDQ MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff400
pi 1
'
EXPECT='pmuludq mm0, [eax]
'
run_test


# -------------------------------
# PMULUDQ XMM0, [EAX] instruction
NAME="x86 SSE: [PMULUDQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff400
pi 1
'
EXPECT='pmuludq xmm0, [eax]
'
run_test


# -------------------------------
# PMADDWD MM0, [EAX] instruction
NAME="x86 SSE: [PMADDWD MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff500
pi 1
'
EXPECT='pmaddwd mm0, [eax]
'
run_test


# -------------------------------
# PMADDWD XMM0, [EAX] instruction
NAME="x86 SSE: [PMADDWD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff500
pi 1
'
EXPECT='pmaddwd xmm0, [eax]
'
run_test


# -------------------------------
# PSADBW MM0, [EAX] instruction
NAME="x86 SSE: [PSADBW MM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 0ff600
pi 1
'
EXPECT='psadbw mm0, [eax]
'
run_test


# -------------------------------
# PSADBW XMM0, [EAX] instruction
NAME="x86 SSE: [PSADBW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff600
pi 1
'
EXPECT='psadbw xmm0, [eax]
'
run_test


# -------------------------------
# PSUBUSB XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBUSB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fd800
pi 1
'
EXPECT='psubusb xmm0, [eax]
'
run_test


# -------------------------------
# PSUBUSW XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBUSW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fd900
pi 1
'
EXPECT='psubusw xmm0, [eax]
'
run_test


# -------------------------------
# PMINUB XMM0, [EAX] instruction
NAME="x86 SSE: [PMINUB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fda00
pi 1
'
EXPECT='pminub xmm0, [eax]
'
run_test


# -------------------------------
# PMAXUB XMM0, [EAX] instruction
NAME="x86 SSE: [PMAXUB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fde00
pi 1
'
EXPECT='pmaxub xmm0, [eax]
'
run_test


# -------------------------------
# PAND XMM0, [EAX] instruction
NAME="x86 SSE: [PAND XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fdb00
pi 1
'
EXPECT='pand xmm0, [eax]
'
run_test


# -------------------------------
# PANDN XMM0, [EAX] instruction
NAME="x86 SSE: [PANDN XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fdf00
pi 1
'
EXPECT='pandn xmm0, [eax]
'
run_test


# -------------------------------
# PADDUSB XMM0, [EAX] instruction
NAME="x86 SSE: [PADDUSB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fdc00
pi 1
'
EXPECT='paddusb xmm0, [eax]
'
run_test


# -------------------------------
# PADDUSW XMM0, [EAX] instruction
NAME="x86 SSE: [PADDUSW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fdd00
pi 1
'
EXPECT='paddusw xmm0, [eax]
'
run_test


# -------------------------------
# PAVGB XMM0, [EAX] instruction
NAME="x86 SSE: [PAVGB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fe000
pi 1
'
EXPECT='pavgb xmm0, [eax]
'
run_test


# -------------------------------
# PAVGW XMM0, [EAX] instruction
NAME="x86 SSE: [PAVGW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fe300
pi 1
'
EXPECT='pavgw xmm0, [eax]
'
run_test


# -------------------------------
# PSUBSB XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBSB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fe800
pi 1
'
EXPECT='psubsb xmm0, [eax]
'
run_test


# -------------------------------
# PSUBSW XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBSW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fe900
pi 1
'
EXPECT='psubsw xmm0, [eax]
'
run_test


# -------------------------------
# PMINSW XMM0, [EAX] instruction
NAME="x86 SSE: [PMINSW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fea00
pi 1
'
EXPECT='pminsw xmm0, [eax]
'
run_test


# -------------------------------
# PMAXSW XMM0, [EAX] instruction
NAME="x86 SSE: [PMAXSW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fee00
pi 1
'
EXPECT='pmaxsw xmm0, [eax]
'
run_test


# -------------------------------
# POR XMM0, [EAX] instruction
NAME="x86 SSE: [POR XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660feb00
pi 1
'
EXPECT='por xmm0, [eax]
'
run_test


# -------------------------------
# PADDSB XMM0, [EAX] instruction
NAME="x86 SSE: [PADDSB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fec00
pi 1
'
EXPECT='paddsb xmm0, [eax]
'
run_test


# -------------------------------
# PADDSW XMM0, [EAX] instruction
NAME="x86 SSE: [PADDSW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fed00
pi 1
'
EXPECT='paddsw xmm0, [eax]
'
run_test


# -------------------------------
# PXOR XMM0, [EAX] instruction
NAME="x86 SSE: [PXOR XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660fef00
pi 1
'
EXPECT='pxor xmm0, [eax]
'
run_test


# -------------------------------
# PSUBB XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff800
pi 1
'
EXPECT='psubb xmm0, [eax]
'
run_test


# -------------------------------
# PSUBW XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ff900
pi 1
'
EXPECT='psubw xmm0, [eax]
'
run_test


# -------------------------------
# PSUBD XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ffa00
pi 1
'
EXPECT='psubd xmm0, [eax]
'
run_test


# -------------------------------
# PSUBQ XMM0, [EAX] instruction
NAME="x86 SSE: [PSUBQ XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ffb00
pi 1
'
EXPECT='psubq xmm0, [eax]
'
run_test


# -------------------------------
# PADDB XMM0, [EAX] instruction
NAME="x86 SSE: [PADDB XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ffc00
pi 1
'
EXPECT='paddb xmm0, [eax]
'
run_test


# -------------------------------
# PADDW XMM0, [EAX] instruction
NAME="x86 SSE: [PADDW XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ffd00
pi 1
'
EXPECT='paddw xmm0, [eax]
'
run_test


# -------------------------------
# PADDD XMM0, [EAX] instruction
NAME="x86 SSE: [PADDD XMM0, [EAX]]"
FILE=malloc://32
CMDS='
e asm.arch=x86
e asm.bits=32
wx 660ffe00
pi 1
'
EXPECT='paddd xmm0, [eax]
'
run_test

