#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=malloc://1024
IGNORE_ERR=1
CMDS='
w test
w test@333
w test@666
?e
e search.in=block
b 777
/ test
'
EXPECT='
0x00000000 hit0_0 "test"
0x0000014d hit0_1 "test"
0x0000029a hit0_2 "test"
'

run_test
