#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="bug 3788 #1: search in virtual address"
FILE=../../bins/vsf/c64-rambo2-norom.vsf
IGNORE_ERR=1
CMDS='s 0
/x ac6c6c68
'
EXPECT='0x0000008a hit0_0 ac6c6c68
'
run_test

NAME="bug 3788 #2: search with multiple sections"
FILE=../../bins/vsf/c64-rambo2-rom.vsf
IGNORE_ERR=1
CMDS='s 0
/x ac686b6d
'
EXPECT='0x0000008a hit0_0 ac686b6d
'
run_test

