#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=malloc://1024
NAME="issue 3479"
IGNORE_ERR=1
CMDS='w aac
p8 3
/x 616163
f~?
'
EXPECT='616163
0x00000000 hit0_0 616163
1
'
run_test

FILE=malloc://1024
NAME="issue 3479"
BROKEN=1
IGNORE_ERR=1
CMDS='w aac
p8 3
/x 6163
f~?
'
EXPECT='616163
0x0000000l hit0_0 6163
1
'
run_test

