#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../bins/elf/x86-simple
NAME="search count"
IGNORE_ERR=1
CMDS='#crc32 @ $$+10
/#crc32 b3bd20c0'
EXPECT='b3bd20c0
f hash.crc32.b3bd20c0 = 0x804806a
'
run_test

