#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=malloc://1024
IGNORE_ERR=1
CMDS='wx 01020304 @ 0x100
/x 01020304
?v hit0_0'
EXPECT='0x00000100 hit0_0 01020304
0x100
'

run_test
