#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=malloc://1024
NAME="search count"
IGNORE_ERR=1
CMDS='wx 2f @ 0x100
wx 2f @ 0x110
wx 2f @ 0x120
/x 2f > /dev/null
?vi $?'
EXPECT='3
'
run_test

FILE=malloc://1024
IGNORE_ERR=1
CMDS='wx 2f @ 0x101
/ \x00/
?v hit0_0'
EXPECT='0x00000100 hit0_0 "\\u0000/"
0x100
'
run_test

FILE=malloc://1024
IGNORE_ERR=1
CMDS='wx 01020304 @ 0x100
/x 01020304
?v hit0_0'
EXPECT='0x00000100 hit0_0 01020304
0x100
'
run_test

NAME="spaces"
FILE=malloc://1024
IGNORE_ERR=1
CMDS='wx 01020304 @ 0x100
/x 01 02 03 04
?v hit0_0'
EXPECT='0x00000100 hit0_0 01020304
0x100
'
run_test

NAME="binmask"
FILE=malloc://1024
IGNORE_ERR=1
CMDS='wx 01020304 @ 0x100
/x 01020304:ffffffff
?v hit0_0'
EXPECT='0x00000100 hit0_0 01020304
0x100
'
run_test

NAME="binmask spaces"
FILE=malloc://1024
IGNORE_ERR=1
CMDS='wx 01020304 @ 0x100
/x 01 02 03 04
?v hit0_0'
EXPECT='0x00000100 hit0_0 01020304
0x100
'
run_test

NAME='binmask seek search (mips)'
FILE='malloc://1024'
ARGS=
IGNORE_ERR=1
CMDS='
e asm.arch = mips
e scr.color=false
"wx 2080998f00000000d4a22527"
e search.from=0
e search.to=12
s/x 00002027:0000f0ff
?v $$
q
'
EXPECT='0x00000008 hit0_0 d4a22527
0x8
'
run_test

NAME='binmask seek search (mips)'
FILE='malloc://1024'
ARGS=
IGNORE_ERR=1
CMDS='
e asm.arch = mips
e scr.color=false
"wx 2080998f00000000d4a22527"
e search.from=0
e search.to=12
s/x 2027:f0ff
?v $$
q
'
EXPECT='0x0000000a hit0_0 2527
0xa
'
run_test
