#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

FILE=../../bins/elf/x86-simple
IGNORE_ERR=1
CMDS='
e search.in=section
/x 5b
pi 1 @ hit0_0
'
EXPECT='0x08048065 hit0_0 5b
pop ebx
'

run_test
