#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# TODO: maijin: add tests for verify section and symbols offsets
# TODO: verify different baddr

NAME="io.baddr"
BROKEN=
FILE=../bins/elf/hello-linux-x86_64
CMDS='
?v entry0
'
EXPECT='0x400410
'
run_test

NAME="io.baddr"
BROKEN=
ARGS="-B 0xf00000"
FILE=../bins/elf/hello-linux-x86_64
CMDS='
?v entry0
'
EXPECT='0xf00410
'
run_test

NAME="io.baddr"
BROKEN=1
FILE=../bins/elf/hello-linux-x86_64
CMDS='!rabin2 -B 0xf00000 -re ${FILE} | grep 0x'
EXPECT='f entry0 1 @ 0x00f00410
'
run_test

NAME="io.baddr entry0 data"
FILE=../bins/elf/hello-linux-x86_64
CMDS='
ie~paddr[3]
ie~vaddr[1]
p8 10 @ 0x00400410
p8 10 @ 0x00000410
'
EXPECT='0x00000410
0x00400410
31ed4989d15e4889e248
31ed4989d15e4889e248
'
run_test

NAME="io.baddr -x86_32 entry0 data"
FILE=../bins/mach0/fatmach0-3true
ARGS='-a x86 -b 32'
CMDS='
ie~paddr[3]
ie~vaddr[1]
p8 10 @ 0x00001f44
p8 10 @ 0x00005f44
'
EXPECT='0x00005f44
0x00001f44
6a0089e583e4f083ec10
6a0089e583e4f083ec10
'
run_test

NAME="io.baddr"
BROKEN=1
FILE=../bins/elf/hello-linux-x86_64
ARGS='-B 0xf00000'
CMDS='!rabin2 -B 0xf00000 -re ${FILE} | grep 0x
p8 10 @ 0x00f00410'
EXPECT='f entry0 1 @ 0x00f00410
31ed4989d15e4889e248
'
run_test
