#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

# TODO: maijin: add tests for verify section and symbols offsets
# TODO: verify different baddr

NAME="io.baddr"
BROKEN=
FILE=../bins/elf/hello-linux-x86_64
CMDS='
?v entry0
'
EXPECT='0x400410
'
run_test

NAME="io.baddr"
BROKEN=
ARGS="-B 0xf00000"
FILE=../bins/elf/hello-linux-x86_64
CMDS='
?v entry0
'
EXPECT='0xf00410
'
run_test

NAME="io.baddr"
BROKEN=
FILE=../bins/elf/hello-linux-x86_64
CMDS='!rabin2 -B 0xf00000 -re ${FILE} | grep 0x'
EXPECT='f entry0 1 @ 0x00f00410
'
run_test

NAME="io.baddr"
BROKEN=
ARGS="-e bin.laddr=0xf00000"
FILE=../bins/elf/hello-linux-x86_64
CMDS='
?v entry0
'
EXPECT='0xf00410
'
run_test

NAME="io.baddr.ib"
BROKEN=1
FILE=../bins/elf/hello-linux-x86_64
CMDS='
e bin.laddr=0xf00000
ib
ie*~0x[4]
'
EXPECT='0xf00410
'
run_test
