#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="io ff"
BROKEN=
FILE=../bins/elf/hello-linux-x86_64
CMDS='
p8 4 @ 0x999999999
'
EXPECT='ffffffff
'
run_test

NAME="io ff based on seek"
BROKEN=1
FILE=../bins/pe/b.exe
CMDS='
s 0x0040200b
p8 10
s +1
p8 10
'
EXPECT='00000000000000000000
00000000000000000000
'
run_test
