#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='rahash2 -a md5'
CMDS='!rahash2 -a md5 ../../bins/elf/hello-linux-x86_64'
BROKEN=
EXPECT='../../bins/elf/hello-linux-x86_64: 0x00000000-0x00001a35 md5: c957bd5bd6204470256bc15248ccafd4
'

run_test

NAME='rahash2 -a sha1'
CMDS='!rahash2 -a sha1 ../../bins/elf/hello-linux-x86_64'
BROKEN=
EXPECT='../../bins/elf/hello-linux-x86_64: 0x00000000-0x00001a35 sha1: 687c82d13cb27f0600d8e57edc784282c1732f56
'

run_test

NAME='rahash2 -a sha256'
CMDS='!rahash2 -a sha256 ../../bins/elf/hello-linux-x86_64'
BROKEN=
EXPECT='../../bins/elf/hello-linux-x86_64: 0x00000000-0x00001a35 sha256: 7bdbf25324af1946ec0b16dbf928875a588a786f7c279cd115729c5a3a297a55
'

run_test

NAME='rahash2 -a sha384'
CMDS='!rahash2 -a sha384 ../../bins/elf/hello-linux-x86_64'
BROKEN=1
EXPECT='../../bins/elf/hello-linux-x86_64: 0x00000000-0x00001a35 sha384: a6fed224b0b5892ab44839b5ae6a12e54fb3393b5f1e1ca174fb5a0032c994f1c492c5b3a090518d8a60875223977ba4
'

run_test

NAME='rahash2 -a sha512'
CMDS='!rahash2 -a sha512 ../../bins/elf/hello-linux-x86_64'
BROKEN=1
EXPECT='../../bins/elf/hello-linux-x86_64: 0x00000000-0x00001a35 sha512: 2640b1ff96870fb78a3d8ae6b51595ca86c37e25443b2e8c5441e77d11cdb3830ece8d791561c22788d37d7f22c99cdabf8f798826c0ff441901e6157890fee6
'

run_test

NAME='rahash2 -a md5,sha1,sha256 -r'
CMDS='!rahash2 -a md5,sha1,sha256 -r ../../bins/elf/hello-linux-x86_64'
BROKEN=
EXPECT='../../bins/elf/hello-linux-x86_64: e file.md5=c957bd5bd6204470256bc15248ccafd4
../../bins/elf/hello-linux-x86_64: e file.sha1=687c82d13cb27f0600d8e57edc784282c1732f56
../../bins/elf/hello-linux-x86_64: e file.sha256=7bdbf25324af1946ec0b16dbf928875a588a786f7c279cd115729c5a3a297a55
'

run_test

NAME='rahash2 -b10 -a md5,sha1,sha256 -r'
CMDS='!rahash2 -b10 -a md5,sha1,sha256 -r ../../bins/elf/hello-linux-x86_64'
BROKEN=
EXPECT='../../bins/elf/hello-linux-x86_64: e file.md5=c957bd5bd6204470256bc15248ccafd4
../../bins/elf/hello-linux-x86_64: e file.sha1=687c82d13cb27f0600d8e57edc784282c1732f56
../../bins/elf/hello-linux-x86_64: e file.sha256=7bdbf25324af1946ec0b16dbf928875a588a786f7c279cd115729c5a3a297a55
'

run_test


NAME='rahash2 -h'
CMDS='!rahash2~Usage'
BROKEN=
EXPECT='Usage: rahash2 [-rBhLkv] [-b S] [-a A] [-c H] [-s S] [-f O] [-t O] [file] ...
'

run_test

NAME='rahash2 -a md5 -s "admin"'
CMDS='!rahash2 -a md5 -s "admin"'
BROKEN=
EXPECT='0x00000000-0x00000004 md5: 21232f297a57a5a743894a0e4a801fc3
'

run_test

NAME='rahash2 -a md5 -e -s "admin"'
CMDS='!rahash2 -a md5 -e -s "admin"'
BROKEN=
EXPECT='0x00000000-0x00000004 md5: c31f804a0e4a8943a7a5577a292f2321
'

run_test


NAME='rahash2 -a sha1,sha256 -s "admin"'
CMDS='!rahash2 -a sha1,sha256 -s "admin"'
BROKEN=
EXPECT='0x00000000-0x00000004 sha1: d033e22ae348aeb5660fc2140aec35850c4da997
0x00000000-0x00000004 sha256: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
'

run_test


NAME='rahash2 -D -s "YWRtaW4="'
CMDS='!rahash2 -D -s "YWRtaW4="'
BROKEN=
EXPECT='admin'

run_test

NAME='rahash2 -d -s "admin"'
CMDS='!rahash2 -d -s "admin"'
BROKEN=
EXPECT='YWRtaW4=
'

run_test

NAME='rahash2 -d -x "61646d696e"'
CMDS='!rahash2 -d -x "61646d696e"'
BROKEN=
EXPECT='YWRtaW4=
'

run_test

NAME='rahash2 -a md5 -d -x "61646d696e"'
CMDS='!rahash2 -a md5 -x "61646d696e"'
BROKEN=
EXPECT='0x00000000-0x00000004 md5: 21232f297a57a5a743894a0e4a801fc3
'

run_test

NAME='rahash2 -a md5 -x "61646d696e" -s "admin"'
CMDS='!rahash2 -a md5 -x "61646d696e" -s "admin"'
BROKEN=
EXPECT_ERR='Hashstring already defined
'

run_test

NAME='rahash2 -L'
CMDS='!rahash2 -L'
BROKEN=
EXPECT='md5
sha1
sha256
sha384
sha512
crc16
crc32
md4
xor
xorpair
parity
entropy
hamdist
pcprint
mod255
xxhash
adler32
'

run_test

NAME='rahash2 -a md5 -t0x4 -x "61646d696eaa"'
CMDS='!rahash2 -a md5 -t0x4 -x "61646d696eaa"'
BROKEN=
EXPECT='0x00000000-0x00000004 md5: 21232f297a57a5a743894a0e4a801fc3
'

run_test

NAME='rahash2 -q -a md5 -t0x4 -x "61646d696eaa"'
CMDS='!rahash2 -q -a md5 -t0x4 -x "61646d696eaa"'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'

run_test


NAME='rahash2 -q -a md5 -f0x1 -x "aa61646d696e"'
CMDS='!rahash2 -q -a md5 -f0x1 -x "aa61646d696e"'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'

run_test


NAME='rahash2 -q -a md5 -i1 -x "61646d696e"'
CMDS='!rahash2 -q -a md5 -i1 -x "61646d696e"'
BROKEN=
EXPECT='43442676c74ae59f219c2d87fd6bad52
'

run_test

NAME='rahash2 -q -a md5 -i2 -x "61646d696e"'
CMDS='!rahash2 -q -a md5 -i2 -x "61646d696e"'
BROKEN=
EXPECT='9fec80fbcee7632ce78d1586332b299e
'

run_test

NAME='rahash2 -a md5 -t0x4 -s "admina"'
CMDS='!rahash2 -a md5 -t0x4 -s "admina"'
BROKEN=
EXPECT='0x00000000-0x00000004 md5: 21232f297a57a5a743894a0e4a801fc3
'

run_test

NAME='rahash2 -q -a md5 -t0x4 -s "admina"'
CMDS='!rahash2 -q -a md5 -t0x4 -s "admina"'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'

run_test


NAME='rahash2 -q -a md5 -f0x1 -s "aadmin"'
CMDS='!rahash2 -q -a md5 -f0x1 -s "aadmin"'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'

run_test


NAME='rahash2 -q -a md5 -i1 -s "admin"'
CMDS='!rahash2 -q -a md5 -i1 -s "admin"'
BROKEN=
EXPECT='43442676c74ae59f219c2d87fd6bad52
'

run_test

NAME='rahash2 -q -a md5 -i2 -s "admin"'
CMDS='!rahash2 -q -a md5 -i2 -s "admin"'
BROKEN=
EXPECT='9fec80fbcee7632ce78d1586332b299e
'

run_test


NAME='rahash2 -q -a md5 -f0x1 -t0x5 -s "aadmina"'
CMDS='!rahash2 -q -a md5 -f0x1 -t0x5 -s "aadmina"'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'

run_test


NAME='rahash2 -q -a md5 -f0x1 -t0x5 -x "aa61646d696eaa"'
CMDS='!rahash2 -q -a md5 -f0x1 -t0x5 -x "aa61646d696eaa"'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'

run_test

NAME='printf "admin" | rahash2 -q -a md5 -s -'
CMDS='!printf "admin" | rahash2 -q -a md5 -s -'
BROKEN=1
EXPECT='21232f297a57a5a743894a0e4a801fc3
'


NAME='printf "aadmina" | rahash2 -f0x1 -t0x5 -q -a md5 -s -'
CMDS='!printf "aadmina" | rahash2 -f0x1 -t0x5 -q -a md5 -s -'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'

run_test

NAME='printf "aa61646d696eaa" | rahash2 -f0x1 -t0x5 -q -a md5 -x -'
CMDS='!printf "aa61646d696eaa" | rahash2 -f0x1 -t0x5 -q -a md5 -x -'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'
run_test

NAME='rahash2 -f0x1 -t0x5 -q -a md5 admin.txt'
CMDS='!rahash2 -f0x1 -t0x5 -q -a md5 ../../bins/other/admin.txt'
FILE=../../bins/other/admin.txt
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
'
run_test


NAME='rahash2 -v~commit?"'
CMDS='!!rahash2 -v~commit?'
EXPECT='1
'
run_test

NAME='rahash2 -s hello1'
CMDS='!!rahash2 -qa md5 -s hello1'
EXPECT='203ad5ffa1d7c650ad681fdff3965cd2
'
run_test

NAME='rahash2 -s hello\x31'
CMDS='!!rahash2 -qa md5 -s hello\\x31'
EXPECT='203ad5ffa1d7c650ad681fdff3965cd2
'
run_test

NAME='rahash2 zero length hashes md5'
CMDS='!rahash2 -a md5 -s ""'
EXPECT='0x00000000-0x00000000 md5: d41d8cd98f00b204e9800998ecf8427e
'

run_test

NAME='rahash2 zero length hashes sha1'
CMDS='!rahash2 -a sha1 -s ""'
EXPECT='0x00000000-0x00000000 sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
'

run_test

NAME='rahash2 -c with correct expected hash'
CMDS='!rahash2 -a md5 -s "admin" -c 21232f297a57a5a743894a0e4a801fc3'
BROKEN=
EXPECT='0x00000000-0x00000004 md5: 21232f297a57a5a743894a0e4a801fc3
rahash2: Computed hash matches the expected one.
'

run_test

NAME='rahash2 -c with correct expected hash and quiet'
CMDS='!rahash2 -q -a md5 -s "admin" -c 21232f297a57a5a743894a0e4a801fc3'
BROKEN=
EXPECT='21232f297a57a5a743894a0e4a801fc3
rahash2: Computed hash matches the expected one.
'

run_test

NAME='rahash2 -c with missing nibble'
CMDS='!rahash2 -a md5 -s "admin" -c 21232f297a57a5a743894a0e4a801fc'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Invalid -c hex hash
'

run_test

NAME='rahash2 -c with incorrect md5 hash length'
CMDS='!rahash2 -a md5 -s "admin" -c 21232f297a57a5a743894a0e4a801f'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Given -c hash has 15 bytes but the selected algorithm returns 16 bytes.
'

run_test

NAME='rahash2 -c with incorrect sha1 hash length'
CMDS='!rahash2 -a sha1 -s "admin" -c 21232f297a57a5a743894a0e4a801f'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Given -c hash has 15 bytes but the selected algorithm returns 20 bytes.
'

run_test

NAME='rahash2 -c with 2 hash algorithms'
CMDS='!rahash2 -a md5,sha1 -s "admin" -c 21232f297a57a5a743894a0e4a801f'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Option -c incompatible with multiple algorithms in -a.
'

run_test

NAME='rahash2 -c with all hash algorithms'
CMDS='!rahash2 -a all -s "admin" -c 21232f297a57a5a743894a0e4a801f'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Option -c incompatible with multiple algorithms in -a.
'

run_test

NAME='rahash2 -c with custom block size and per-block hash'
CMDS='!rahash2 -b 1 -B -s "admin" -c 21232f297a57a5a743894a0e4a801f'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Option -c incompatible with -b and -B options.
'

run_test

NAME='rahash2 -c with base64 encoding'
CMDS='!rahash2 -d -s "admin" -c 21232f297a57a5a743894a0e4a801f'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Option -c incompatible with -d or -D options.
'

run_test

NAME='rahash2 -c with base64 decoding'
CMDS='!rahash2 -D -s "admin" -c 21232f297a57a5a743894a0e4a801f'
BROKEN=
EXPECT=''
IGNORE_ERR=0
EXPECT_ERR='rahash2: Option -c incompatible with -d or -D options.
'

run_test
