#!/bin/sh
# GPL 3+ - Copyright (C) 2014  Maijin
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='yara scan'
BROKEN=
FILE=../b/files/pe/a.exe
ARGS=
CMDS='yara scan'
EXPECT='/usr/share/radare2/0.9.8.git/yara/packers.rules added
/usr/share/radare2/0.9.8.git/yara/crypto.rules added
MingWin32_GCC_3_x
Microsoft_Windows_Update_CAB_SFX_module
Microsoft_Visual_C___v7_1_DLL
dUP_v2_x_Patcher
MinGW_GCC_2_x
MingWin32
MingWin32_v
'
run_test

