#!/bin/sh
# LGPL - Copyright (C) 2014 Fedor Sakharov

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="pdf dwarf"
BROKEN=
FILE=/tmp/r2-regressions/dwarftest
IGNORE_ERR=1
ARGS=
CMDS='e asm.dwarf=true
aa
pdf@main'
EXPECT='|          ; DATA XREF from 0x0040045d (fcn.00400436)
/ (fcn) sym.main 44
|          0x0040052d    55           push rbp  ; dwarftest.c:4 {  
|          0x0040052e    4889e5       mov rbp, rsp
|          0x00400531    4883ec10     sub rsp, 0x10
|          0x00400535    c745fc00000. mov dword [rbp-0x4], 0x0  ; dwarftest.c:7 	for (i = 0; i < 5; i++) {  
|      ,=< 0x0040053c    eb0e         jmp fcn.0040054c
|      |   ; JMP XREF from 0x00400550 (unk)
|- loc.0040053e 27
|      |   0x0040053e    bfe4054000   mov edi, str.dwarftest  ; dwarftest.c:8 		printf ("dwarftest\n");   ; str.dwarftest
|      |   0x00400543    e8c8feffff   call sym.imp.puts
|      |      sym.imp.puts(unk)
|      |   0x00400548    8345fc01     add dword [rbp-0x4], 0x1  ; dwarftest.c:7 	for (i = 0; i < 5; i++) {  
|      |   ; JMP XREF from 0x0040053c (unk)
|- fcn.0040054c 13
|      `-> 0x0040054c    837dfc04     cmp dword [rbp-0x4], 0x4
|          0x00400550    7eec         jle loc.0040053e
|          0x00400552    b800000000   mov eax, 0x0  ; dwarftest.c:11 	return 0;  
|          0x00400557    c9           leave  ; dwarftest.c:12 }  
\          0x00400558    c3           ret
'

mkdir -p /tmp/r2-regressions/

if [ $? -eq 1 ]; then
	echo "Failed to create directory in /tmp/r2-regressions/dwarf"
	exit 1
fi

cp ../bins/elf/dwarftest /tmp/r2-regressions/dwarftest
cp ../bins/src/dwarftest.c /tmp/r2-regressions/dwarftest.c

run_test
