#!/bin/sh

# LGPL 3+ - Copyright (C) 2015 maijin


[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='aa ; zF libc.sig'
FILE=../bins/elf/pid_stripped
ARGS=
CMDS="aa ; zF ../bins/other/sigs/libc.sig "
EXPECT='Loading: 
Found flirt.__libc_start_main
'
run_test