#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='ASCII Recognition'
FILE=malloc://1024
ARGS=
CMDS='
wx ba3d000000
pd 1
'
EXPECT="           0x00000000    ba3d000000   mov edx, 0x3d ; '='
"
run_test

