#!/bin/sh

# GPL 3+ - Copyright (C) 2012  pancake

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='test pDj missing newline issue'
FILE=-
ARGS=
BROKEN=1
CMDS='
e asm.arch=x86
e asm.bits=64
wx 4883c768
pDj 4
'
EXPECT='[{"offset":0,"size":4,"opcode":"add rdi, 0x68","bytes":"4883c768","type":"add"}]
'
run_test

