#!/bin/sh

# GPL 3+ - Copyright (C) 2014

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='types'
FILE=malloc://1024
ARGS=
CMDS='wx a00f00002a4b9a020000
pf fcbi foo bar fool beer
'
EXPECT=" foo : 0x00000000 = 4000.000000
 bar : 0x00000004 = 42 ; 42 ; '*'
fool : 0x00000005 = 75 ; 0x4b ; 'K'
beer : 0x00000006 = 666
"
run_test

NAME='word types'
FILE=malloc://1024
ARGS=
BROKEN=1
CMDS='wx efbeadde00000000adde
pf qw bigWord beef
'
EXPECT="bigWord : 0x00000000 = (qword) 0x00000000deadbeef
  beef : 0x00000008 = 0xdead
"
run_test

NAME='swap endianess'
FILE=malloc://1024
ARGS=
CMDS='wx deadbeef00000000adde
pf eqew bigWord beef
'
EXPECT="bigWord : 0x00000000 = (qword) 0xdeadbeef00000000
  beef : 0x00000008 = 0xdead
"
run_test

NAME='named obj'
FILE=malloc://1024
ARGS=
CMDS='wx a00f00004b
pf.troll ic lol cat
pf.troll
'
EXPECT="lol : 0x00000000 = 4000
cat : 0x00000004 = 75 ; 75 ; 'K'
"
run_test

NAME='array obj'
FILE=malloc://1024
ARGS=
CMDS='wx a00f00004b2a0000004c
pf.troll 2ic nb plop
pf.troll
'
EXPECT="0x00000000 [0] {
     nb : 0x00000000 = 4000
   plop : 0x00000004 = 75 ; 75 ; 'K'
}
0x00000005 [1] {
     nb : 0x00000005 = 42
   plop : 0x00000009 = 76 ; 76 ; 'L'
}
"
run_test

NAME='write test'
FILE=malloc://1024
ARGS=
CMDS='wx 32000000424c41424c41424c41424c41
pf.troll izi hu swagg plop
.pf.troll.hu=42
.pf.troll.swagg=BWAAAA
.pf.troll.plop=4000
pf.troll
'
EXPECT="   hu : 0x00000000 = 42
swagg : 0x00000004 = BWAAAABLABLA
 plop : 0x00000011 = 4000
"
run_test
