#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='ASCII Recognition'
FILE=malloc://1024
ARGS=
CMDS='
e scr.columns = 90
wx ba3d000000
pd 1
'
EXPECT="           0x00000000    ba3d000000     mov edx, 0x3d                  ; '='
"
run_test

NAME='String capstone'
FILE=../bins/elf/main
ARGS=
CMDS='
e asm.arch = x86
e scr.columns = 90
aa
pd 1 @ 0x0040050a
'
EXPECT='|          0x0040050a    bfc4054000     mov edi, str.Hello_World       ; "Hello World" @ 0x4005c4
'
run_test

NAME='String udis86'
FILE=../bins/elf/main
ARGS=
CMDS='e asm.arch = x86.udis
e scr.columns = 90
aa
pd 1 @ 0x0040050a
'
EXPECT='|          0x0040050a    bfc4054000     mov edi, str.Hello_World       ; "Hello World" @ 0x4005c4
'
run_test

NAME='pD -10'
FILE=malloc://1024
CMDS='
wx 90909090909090909090 ; s 10 ; pD -10
'
EXPECT='           0x00000000    90             nop
           0x00000001    90             nop
           0x00000002    90             nop
           0x00000003    90             nop
           0x00000004    90             nop
           0x00000005    90             nop
           0x00000006    90             nop
           0x00000007    90             nop
           0x00000008    90             nop
           0x00000009    90             nop
'

run_test

NAME='pd -10'
FILE=malloc://1024
BROKEN=1
CMDS='
wx 90909090909090909090 ; s 10 ; pd -10
'
EXPECT='           0x00000000    90           nop
           0x00000001    90           nop
           0x00000002    90           nop
           0x00000003    90           nop
           0x00000004    90           nop
           0x00000005    90           nop
           0x00000006    90           nop
           0x00000007    90           nop
           0x00000008    90           nop
           0x00000009    90           nop
'
run_test
