#!/bin/sh

# GPL 3+ - Copyright (C) 2014  neuschaefer

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## "." - interpret commands from various sources

NAME='.- (edit, source tmp file)'
FILE=-
ARGS=
CMDS='
e cfg.editor=/bin/true
.-
'
EXPECT=''
run_test
