#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh


NAME='pm hello.c'
FILE=../bins/src/hello.c
CMDS='
pm
'
EXPECT='0x00000000 1 C source code
'
run_test

NAME='pm elf/main'
FILE=../bins/elf/main
ARGS=-n
CMDS='
pm
'
EXPECT='0x00000000 1 ELF 64-bit LSB executable, x86-64, version 1
'
run_test

NAME='pm mach0/fatmach0-3true'
FILE=../bins/mach0/fatmach0-3true
ARGS=-n
CMDS='
pm
'
EXPECT='0x00000000 1 Fat-Mach-O
'
run_test

NAME='pm java/Hello.class'
FILE=../bins/java/Hello.class
ARGS=-n
CMDS='
pm
'
EXPECT='0x00000000 1 Java CLASS
'
run_test

NAME='pm pe/a.exe'
FILE=../bins/pe/a.exe
ARGS=-n
CMDS='
pm
'
EXPECT='0x00000000 1 PE  for MS Windows (console) Intel 80386 32-bit
'
run_test
