#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='test pDj missing newline issue'
CMDS='
e asm.arch=x86
e asm.bits=64
wx 4883c768
pDj 4
'
EXPECT='[{"offset":0,"val":104,"esil":"104,rdi,+=,$o,of,=,$s,sf,=,$z,zf,=,$c63,cf,=,$p,pf,=","refptr":false,"fcn_addr":0,"fcn_last":0,"size":4,"opcode":"add rdi, 0x68","bytes":"4883c768","family":"cpu","type":"add","type_num":17,"type2_num":0}]

'
run_test
