#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

#TODO FIX tests

NAME='p= 0xff 0x00'
FILE=-
BROKEN=1
CMDS='
b 2
wx 0xff
p= 2@0
'
EXPECT='         ___________________________________________________
00 00ff | __________________________________________________|
01 0000 ||
'

run_test

NAME='p=b 0xff 0x00'
FILE=-
CMDS='
b 2
wx 0xff
p=b 2 2@0
'
EXPECT="0x00000000 00 00ff |'__________________________________________________|
0x00000001 01 0000 ||
"

run_test

NAME='p=d'
FILE='../bins/elf/arm1.bin'
BROKEN=1
ARGS=-n
CMDS='p=d 10 2560@0'
EXPECT='min:   1  0x1
max:   235  0xeb
dict:  65  0x41
range: 234  0xea
'

run_test

NAME='p=e 5'
FILE='../bins/elf/arm1.bin'
CMDS='p=e 5@0'
EXPECT="0x00000000 00 00c3 |''''''''''''''''''''''''''''''''''''''|
0x0001bec1 01 00c4 |                                       |
0x00037d82 02 00c4 |                                       |
0x00053c43 03 00c4 |                           ____________|
0x0006fb04 04 0084 | __________________________|
"

run_test

NAME='p=e 5 0x100'
FILE='../bins/elf/arm1.bin'
ARGS=-n
CMDS='p=e 5 0x100'
EXPECT="0x00000000 00 0080 |''''''''''''''''''''''___|
0x00000033 01 006c |                     |__
0x00000066 02 007b |                      ___|
0x00000099 03 006a |                   __|
0x000000cc 04 005f | __________________|
"

run_test

NAME='p=e 5 0x100 1'
ARGS=-n
FILE='../bins/elf/arm1.bin'
CMDS='p=e 5 0x100 1'
EXPECT="0x00000000 00 006c |'''''''''''''''''''''|__
0x00000033 01 007b |                      ___|
0x00000066 02 006a |                   __|
0x00000099 03 005f |                  |
0x000000cc 04 005a | _________________|
"

run_test

NAME='p=p 5'
FILE='../bins/elf/arm1.bin'
ARGS=-n
CMDS='p=p 5@0'
EXPECT="0x00000000 00 0032 |''''''''''|
0x0001bec1 01 0031 |         |
0x00037d82 02 0035 |          |__
0x00053c43 03 0040 |            |__________
0x0006fb04 04 0076 | _______________________|
"

run_test

NAME='p=p 5 0x100'
FILE='../bins/elf/arm1.bin'
ARGS=-n
CMDS='p=p 5 0x100'
EXPECT="0x00000000 00 0032 |'''''____|
0x00000033 01 0019 |    |
0x00000066 02 001e |     |
0x00000099 03 001e |     |_
0x000000cc 04 0028 | _______|
"

run_test

NAME='p=p 5 0x100 1'
FILE='../bins/elf/arm1.bin'
ARGS=-n
CMDS='p=p 5 0x100 1'
EXPECT="0x00000000 00 0019 |''''|
0x00000033 01 001e |     |
0x00000066 02 001e |     |_
0x00000099 03 0028 |      _|
0x000000cc 04 001e | _____|
"

run_test
