#!/bin/sh

# LGPL 3+ - Copyright (C) 2015 maijin


[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='aa ; zF libc.sig'
FILE=../bins/elf/pid_stripped
ARGS=
CMDS="aa ; zF ../bins/other/sigs/libc.sig "
EXPECT='Loading: 
Found flirt.__libc_start_main
'
run_test

NAME='zFd libc.sig'
FILE=../bins/elf/pid_stripped
ARGS=
CMDS="zFd ../bins/other/sigs/libc.sig "
EXPECT='Loading: 
41564155B8........4154554D89C4534889CD4D89CD4881EC900000004885C048897C24188974240C48895424100F84340100008B15........31C085D20F94:
  0. 03 2FC0 0298 0000:__libc_start_main
'
run_test