#!/bin/sh
# GPL 3+ - Copyright (C) 2014  Maijin
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='yara scan'
BROKEN=
FILE=../b/files/pe/a.exe
ARGS=
CMDS='yara scan > /dev/null '
EXPECT=''
run_test

NAME='yara add <filedoesnotexist>'
BROKEN=
ARGS=
CMDS='
yara add doesnotexist
'
EXPECT_ERR='Unable to open doesnotexist
'
run_test

NAME='yara add <file>'
CMDS='
yara clear
yara add ../files/test_yara.rules
yara list
'
EXPECT='TEST
'
EXPECT_ERR='Rules cleared
'
run_test
