#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='pD -10 @ 10'
FILE=malloc://512
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pD -10 @ 0xa
'
EXPECT='           0x00000000    b801000000   mov eax, 1
           0x00000005    4839ca       cmp rdx, rcx
           0x00000008    7f00         jg 0xa
'
run_test


NAME='pD -10 @ 0'
FILE=malloc://512
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pD -10 @ 10
'
EXPECT='           0x00000000    b801000000   mov eax, 1
           0x00000005    4839ca       cmp rdx, rcx
           0x00000008    7f00         jg 0xa
'
run_test

NAME='pD 5 @ 0'
FILE=malloc://512
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pD 5
'
EXPECT='           0x00000000    b801000000   mov eax, 1
'
run_test

NAME='pDj 5 @ 0'
FILE=malloc://512
CMDS='e anal.hasnext=0
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pDj 5 @ 0
'
EXPECT='[{"offset":0,"size":5,"opcode":"mov eax, 1","bytes":"b801000000","type":"mov","type_num":9,"type2_num":0}]

'
run_test
