#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='z xref'
FILE=../bins/elf/hello-linux-x86_64
CMDS='
s entry0
zb test fc044000e8b7
fs sign
f~?
.z/ $$ $$+1024
f~?
'
EXPECT='0
1
'
run_test

NAME='zb'
FILE=../bins/elf/go_stripped
CMDS='
zb sym.fmt.Println 653b2530000000724b53b834e7150883ec188b15401c22088d4c24048b5c242083ec08ff742434ff742434ff742434525051e829ffffff8b44242089038b4424248943048b44242889430889d883c4345bc204006a106a1ce85e350700c20400
z
'
EXPECT='Loaded 1 signatures
  1 byte signatures
  0 head signatures
  0 func signatures
Found 0 matches
'
run_test

NAME='z/'
FILE=../bins/elf/go_stripped
CMDS='
zb sym.fmt.Println 653b2530000000724b53b834e7150883ec188b15401c22088d4c24048b5c242083ec08ff742434ff742434ff742434525051e829ffffff8b44242089038b4424248943048b44242889430889d883c4345bc204006a106a1ce85e350700c20400
.z/ section..text section..text+1074039
?v sign.sys.b.sym.fmt.Println
'
EXPECT='0x805b030
'
run_test

NAME='z + aa + axt'
FILE=../bins/elf/zigs_stripped
CMDS='
zb sym.print 5548....48......48......48......48....bf........b8........e8........90c9c3
.z/ section..text section..text+434
e anal.hasnext=0
aa
axt 0x400536
'
EXPECT='call 0x40056f call sign.sys.b.sym.print in main
'
run_test

NAME='zg on mach0'
FILE=../bins/mach0/mach0-i386
BROKEN=1
CMDS='
aaa
zg i386
'
EXPECT='zn i386
zb sym.func._main 5589..83....8b....8b....c7............89....89....8b....89....e8........83....5dc3
zb sym.func._foo 5589..83....8b....89....8b....8b....81..........89....89....e8........8b....01..89..83....5dc3
zb sym.func._bar 5589..83....8b....89....c7............c7............8b....3b....0f..........8b....8b....01..89....8b....05........89....e9........8b....83....5dc3
zn-
'
run_test

NAME='zg on elf'
FILE=../bins/elf/x86-helloworld-gcc
BROKEN=
CMDS='
aaa
zg x86~?main
'
EXPECT='2
'
run_test

NAME='.z on stripped go'
FILE=../bins/elf/zigs_stripped
CMDS='
aa
zb sym.print 5548....48......48......48......48....bf........b8........e8........90c9c3
.z. @@fcn*
?v sign.sys.b.sym.print
'
EXPECT='0x400536
'
run_test

NAME='fs reset'
FILE=../bins/elf/zigs_stripped
CMDS='
fs strings
zb sym.print 5548....48......48......48......48....bf........b8........e8........90c9c3
.z. @@fcn*
fs~* strings
'
EXPECT='0    1 * strings
'
run_test