#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh


NAME='udis pae 0xed31'
FILE=-
CMDS='
e asm.arch = x86.udis
pae 0xed31
'
EXPECT='ebp,ebp,^=
'

run_test


NAME='capstone pae 0xed31'
FILE=-
BROKEN=
CMDS='
pae 0xed31
'
EXPECT='ebp,ebp,^=
'

run_test
