#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh


NAME='p2 hello-linux-x86_64'
FILE=../bins/elf/hello-linux-x86_64
CMDS='
p2 16
'
EXPECT='[44m  [44m  [40m  [41m  [44m  [44m  [47m  [40m  [0m
[44m  [41m  [47m  [47m  [40m  [47m  [47m  [40m  [0m
[41m  [40m  [47m  [40m  [44m  [44m  [44m  [41m  [0m
[44m  [41m  [47m  [47m  [40m  [47m  [47m  [44m  [0m
[41m  [40m  [41m  [47m  [44m  [47m  [41m  [47m  [0m
[40m  [44m  [44m  [47m  [47m  [44m  [41m  [41m  [0m
[41m  [40m  [41m  [40m  [47m  [47m  [47m  [47m  [0m
[47m  [40m  [47m  [41m  [44m  [41m  [47m  [44m  [0m
'

run_test
