#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='pd call sym bug'
FILE=../bins/mach0/hello-objc-arm
BROKEN=
ARGS=
CMDS='
e asm.lines=0
e asm.bytes=0
e asm.comments=0
s sym.__Test_callMeNot_
pd 20~?NSLog
af
pd 20~?NSLog
'
EXPECT="1
1
"
run_test

