#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='pfd.test E (elf_type)var0'
CMDS='"td enum elf_type {ET_HIPROC=0xffff};"
wx 0xffff
pfd.test E (elf_type)var0
pfd.test
'
EXPECT='digraph g { graph [ rank=same; rankdir=LR; ];
root [ rank=1; shape=record
label="test|{0x0|E|var0|<var0>elf_type.ET_HIPROC}"];
}
'
run_test

NAME='pfd.test i var0'
CMDS='wx 0x100
pfd.test i var0
pfd.test
'
EXPECT='digraph g { graph [ rank=same; rankdir=LR; ];
root [ rank=1; shape=record
label="test|{0x0|i|var0|<var0>256}"];
}
'
run_test

NAME='pfd.test w var0'
CMDS='wx 0x1234
pfd.test w var0
pfd.test
'
EXPECT='digraph g { graph [ rank=same; rankdir=LR; ];
root [ rank=1; shape=record
label="test|{0x0|w|var0|<var0>0x1234}"];
}
'
run_test

NAME='pfd.test x var0'
CMDS='wx 0x12345678
pfd.test x var0
pfd.test
'
EXPECT='digraph g { graph [ rank=same; rankdir=LR; ];
root [ rank=1; shape=record
label="test|{0x0|x|var0|<var0>0x12345678}"];
}
'
run_test

NAME='pfd.test z var0'
CMDS='w foobar
pfd.test z var0
pfd.test
'
EXPECT='digraph g { graph [ rank=same; rankdir=LR; ];
root [ rank=1; shape=record
label="test|{0x0|z|var0|<var0>\"foobar\"}"];
}
'
run_test

NAME='pfd.test zz var0 var1'
CMDS='w string1
w string2 @ 0x8
pfd.test zz var0 var1
pfd.test
'
EXPECT='digraph g { graph [ rank=same; rankdir=LR; ];
root [ rank=1; shape=record
label="test|{0x0|z|var0|<var0>\"string1\"}|{0x8|z|var1|<var1>\"string2\"}"];
}
'
run_test
