#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='pi 3'
FILE=malloc://512
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pi 3
'
EXPECT='mov eax, 1
cmp rdx, rcx
jg 0xa
'
run_test

NAME='pij 3'
FILE=malloc://512
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pij 3
'
EXPECT='[{"offset":0,"fcn_addr":0,"fcn_last":0,"size":5,"opcode":"mov eax, 1","bytes":"b801000000","family":"cpu","type":"mov","type_num":9,"type2_num":0},{"offset":5,"fcn_addr":0,"fcn_last":0,"size":3,"opcode":"cmp rdx, rcx","bytes":"4839ca","family":"cpu","type":"cmp","type_num":15,"type2_num":0},{"offset":8,"fcn_addr":0,"fcn_last":0,"size":2,"opcode":"jg 0xa","bytes":"7f00","family":"cpu","type":"cjmp","type_num":2147483649,"type2_num":0,"jump":10,"fail":10}]
'
run_test


NAME='pi 6'
FILE=malloc://512
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00b8010000004839ca7f00
pi 6
'
EXPECT='mov eax, 1
cmp rdx, rcx
jg 0xa
mov eax, 1
cmp rdx, rcx
jg 0x14
'
run_test

NAME='pi -3 @ 3'
FILE=malloc://512
ARGS=
BROKEN=1
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pi -3 @ 10
'
EXPECT='add byte [rax], al
cmp rdx, rcx
jg 0xa
'
run_test

NAME='pij -3 @ 3'
FILE=malloc://512
ARGS=
BROKEN=1
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pij -3 @ 10
'
EXPECT='[{"offset":3,"fcn_addr":0,"fcn_last":0,"size":2,"opcode":"add byte [rax], al","bytes":"0000","type":"add","type_num":17,"type2_num":0},{"offset":5,"fcn_addr":0,"fcn_last":0,"size":3,"opcode":"cmp rdx, rcx","bytes":"4839ca","type":"cmp","type_num":15,"type2_num":0},{"offset":8,"fcn_addr":0,"fcn_last":0,"size":2,"opcode":"jg 0xa","bytes":"7f00","type":"cjmp","type_num":2147483649,"type2_num":0,"jump":10,"fail":10}]
'
run_test



NAME='pi -10'
FILE=malloc://1024
BROKEN=1
CMDS='
wx 90909090909090909090 ; s 10 ; pi -10
'
EXPECT='nop
nop
nop
nop
nop
nop
nop
nop
nop
nop
'

run_test

NAME='pif bsz'
FILE=malloc://1024
CMDS='
e asm.arch=x86
e asm.bits=64
wx 5b415c415d415e415f5dc3
af
b 2
pif
'
EXPECT='pop rbx
pop r12
pop r13
pop r14
pop r15
pop rbp
ret
'
run_test

NAME='pi~?'
FILE=malloc://1024
CMDS='
pi 200~?
pi 200~?
pd 200~?
'
EXPECT='200
200
200
'
run_test

NAME='tmpbits'
CMDS='
e asm.arch=x86
e asm.bits=64
p8 1 @b:32
e asm.bits
'
EXPECT='00
64
'
run_test

NAME='tmpbits'
CMDS='
e asm.arch=x86
e asm.bits=32
p8 1 @b:64
e asm.bits
'
EXPECT='00
32
'
run_test
