#!/bin/sh
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='no flags'
CMDS='f patata
f-*
f~?
'
EXPECT='0
'
run_test

NAME='no flags'
FILE=../bins/elf/elf-relro
BROKEN=
CMDS='f patata
fs *
f-*
f~?
'
EXPECT='0
'
run_test
