#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

#TODO FIX tests
<<COMMENT

NAME='p= 0xff 0x00'
FILE=-
CMDS='
b 2
wx 0xff
p=@0
'
EXPECT='         ___________________________________________________
00 00ff | __________________________________________________|
01 0000 ||
'

run_test

NAME='p=b 0xff 0x00'
FILE=-
CMDS='
b 2
wx 0xff
p=b@0
'
EXPECT='         ___________________________________________________
00 00ff | __________________________________________________|
01 0000 ||
'

run_test

NAME='p=d'
FILE='../bins/elf/arm1.bin'
CMDS='p=d@0'
EXPECT='min:   1  0x1
max:   235  0xeb
dict:  65  0x41
range: 234  0xea
'

run_test

NAME='p=e 5'
FILE='../bins/elf/arm1.bin'
CMDS='p=e 5@0'
EXPECT='         _______________________________________
00 00c3 |                                      |
01 00c4 |                                       |
02 00c4 |                                       |
03 00c4 |                           ____________|
04 0084 | __________________________|
'

run_test

NAME='p=e 5 0x100'
FILE='../bins/elf/arm1.bin'
CMDS='p=e 5 0x100'
EXPECT='         __________________________
00 0080 |                      ___|
01 006c |                     |__
02 007b |                      ___|
03 006a |                   __|
04 005f | __________________|
'

run_test

NAME='p=e 5 0x100 1'
FILE='../bins/elf/arm1.bin'
CMDS='p=e 5 0x100 1'
EXPECT='         ______________________
00 006c |                     |__
01 007b |                      ___|
02 006a |                   __|
03 005f |                  |
04 005a | _________________|
'

run_test

NAME='p=p 5'
FILE='../bins/elf/arm1.bin'
CMDS='p=p 5'
EXPECT='         __________
00 0032 |         |
01 0032 |         |
02 0034 |          |___
03 0047 |              |
04 0045 | _____________|
'

run_test

NAME='p=p 5 0x100'
FILE='../bins/elf/arm1.bin'
ARGS=-n
CMDS='p=p 5 0x100'
EXPECT='0x00000000 00 0000 ||_________
0x00000033 01 0032 |     ____|
0x00000066 02 0019 |    |
0x00000099 03 001e |     |
0x000000cc 04 001e | _____|
'

run_test

NAME='p=p 5 0x100 1'
FILE='../bins/elf/arm1.bin'
ARGS=-n
CMDS='p=p 5 0x100 1'
EXPECT="0x00000000 00 0019 |''''|
0x00000033 01 001e |     |
0x00000066 02 001e |     |_
0x00000099 03 0028 |      _|
0x000000cc 04 001e | _____|
"

run_test

COMMENT
