#!/bin/sh
# GPL 3+ - Copyright (C) 2014  Maijin
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='pxw cfg.bigendian=true'
BROKEN=
FILE=../b/files/elf/hello-linux-x86_64
ARGS=
CMDS='e cfg.bigendian=true
pxw 16'
EXPECT='0x00400410  0x31ed4989 0xd15e4889 0xe24883e4 0xf0505449  1.I..^H..H...PTI
'
run_test

NAME='pxw cfg.bigendian=false'
BROKEN=
FILE=../b/files/elf/hello-linux-x86_64
ARGS=
CMDS='e cfg.bigendian=false
pxw 16'
EXPECT='0x00400410  0x8949ed31 0x89485ed1 0xe48348e2 0x495450f0  1.I..^H..H...PTI
'
run_test
