#!/bin/sh
# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

# "!" - run commands (via system)

NAME='seek far offset'
FILE=-
ARGS=
BROKEN=
CMDS='
s 0x7fffff8000b54000 ; ?v $$
s 0x8fffff8000b54000 ; ?v $$
'
EXPECT='0x7fffff8000b54000
0x8fffff8000b54000
'
run_test

NAME='seek math (symbol addition)'
FILE=../bins/elf/hello-linux-x86_64
ARGS=
CMDS='
s sym._start + 8
s
'
EXPECT='0x400418
'
run_test

NAME='seek opcodes'
FILE=-
ARGS=
BROKEN=
CMDS='
e asm.arch=x86
e asm.bits=64
wx 4883c668
s 0; so   ; ?v $$
s 0; so 1 ; ?v $$
'
EXPECT='0x4
0x4
'
run_test

NAME='seek line'
FILE=../files/projects/resetc64
ARGS=
CMDS='
e lines.from=0x15
e lines.to=0xed
sl 9
sl
sl+1
sl
sl-2
sl
sl 999999999999
sl
sl 0
sl
sl 1; ?v $$
'
EXPECT='9
10
8
8
8
0x16
'
run_test
