#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='struct'
BROKEN=
FILE=-
CMDS='
"td struct a{int a;int b;};"
t~?
'
EXPECT='a=struct
[+]struct.a=a
struct.a.a=int,0,0
a=struct
[+]struct.a=b
struct.a.b=int,4,0
22
'
run_test

NAME='enum32'
BROKEN=
FILE=-
CMDS='
"td enum v { t=0x123, p=0x321 };"
t~?
'
EXPECT='v=enum
v.t=0x123
v.0x123=t
v.p=0x321
v.0x321=p
23
'
run_test

NAME='enum64'
FILE=-
CMDS='
"td enum v { t=0x8000000000000001, p=0x8000000000000008 };"
t~?
'
EXPECT='v=enum
v.t=0x8000000000000001
v.0x8000000000000001=t
v.p=0x8000000000000008
v.0x8000000000000008=p
23
'
run_test
