#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2013  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## "wa" - write opcode

NAME='wa'
FILE=malloc://1024
ARGS='-a x86 -b 32'
CMDS='
"wa nop;mov eax,33"
e asm.profile=simple
pi 2
'
EXPECT='nop
mov eax, 0x21
'
run_test


## "wx" - write hex value

# Writing of bytes.
NAME='wx'
FILE=malloc://1024
ARGS=
CMDS='
wx 010203
p8 3
'
EXPECT='010203
'
run_test


## "wo" - write in block with operation

# Batch adding to bytes works (bug report #59).
NAME='wo'
FILE=malloc://8
ARGS='-w'
CMDS='
wx 0001020304050607
woa 01 @ 0!8
p8 8
woa 01 @ 0!8
p8 8
'
EXPECT='0102030405060708
0203040506070809
'
run_test


## "wt" - write to file

# see bug #503
NAME='wt'
FILE=../b/files/pe/b.exe
ARGS=
CMDS='wt a_piece_of_ls_saved_to_PWD 0x400
ls -l a_piece_of_ls_saved_to_PWD~[3]
'
EXPECT='1024
'
EXPECT_ERR='dumped 0x400 bytes
'
FILTER='sed "s/.*\(\<1024\>\).*\(\<a_piece_of_ls_saved_to_PWD\>\)$/\1 \2/"'

run_test
rm -f a_piece_of_ls_saved_to_PWD


