#!/bin/sh
# GPL 3+ - Copyright (C) 2014  Maijin
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='yara scan'
BROKEN=
FILE=../bins/pe/a.exe
ARGS=
CMDS='yara scan > /dev/null '
EXPECT=''
run_test

NAME='yara add <filedoesnotexist>'
BROKEN=
ARGS=
CMDS='
yara add doesnotexist
'
EXPECT_ERR='Unable to open doesnotexist
'
run_test

NAME='yara add <file>'
CMDS='
yara clear
yara add ../files/test_yara.rules
yara list
'
EXPECT='TEST
elf
'
EXPECT_ERR='Rules cleared
'
run_test

NAME='yara add and scan'
FILE=../bins/elf/hello-linux-x86_64
CMDS='
yara add ../files/test_yara.rules
yara scan
'
EXPECT='elf
'
run_test

NAME='yara tags'
BROKEN=1
CMDS='
yara tags
yara add ../files/test_yara.rules
yara tags
'
EXPECT='crypto
packer
crypto
packer
test_rule
'
run_test

NAME='yara add duplicate then original'
FILE=../bins/elf/hello-linux-x86_64
CMDS='
yara add ../files/test_yara.rules
yara add ../files/test_yara.rules
yara add ../files/test_yara_2.rules
'
EXPECT_ERR='Error: duplicate rule identifier "elf" : ../files/test_yara.rules
'
run_test
