#!/bin/sh

# GPL 3+ - Copyright (C) 2011-2012  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='o-'
FILE=malloc://1024
ARGS=
CMDS='o-`o~[1]`;o'
EXPECT=
run_test

# 3, because one for the adress returned by o -,
# and the two other are the opened files
NAME='o -'
FILE=malloc://1024
ARGS=
CMDS='e file.nowarn=true
e file.loadmethod=append
o -;o~?'
EXPECT='3
'
run_test

NAME='om'
FILE=malloc://1024
ARGS=
CMDS='om `o~[1]` 0x4000
om~?'
EXPECT='2
'
run_test

NAME='om2'
FILE=malloc://1024
ARGS=
CMDS='om `o~[1]` 0x4000
om `o~[1]` 0x4000
om~?'
EXPECT='2
'
run_test

NAME='dbg.oob 10'
FILE=../bins/elf/hello-linux-x86_64
ARGS=
BROKEN=1
CMDS='10oob
pi 1
'
EXPECT='xor ebp, ebp
'
IGNORE_ERR=1
run_test

NAME='dbg.oo+ 10'
FILE=../bins/elf/hello-linux-x86_64
ARGS=
BROKEN=1
CMDS='10oo+
pi 1
'
EXPECT='xor ebp, ebp
'
IGNORE_ERR=1
run_test
