#!/bin/sh
# GPL 3+ - Copyright (C) 2016 crowell
[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='to'
FILE=-
ARGS=
BROKEN=
CMDS='to ../bins/headers/s1.h; to ../bins/headers/s2.h; t S1
'
EXPECT='pf ddd x test z 
'
run_test
