#!/bin/sh
# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='pi 3'
FILE=malloc://512
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pi 3
'
EXPECT='mov eax, 0x1
cmp rdx, rcx
jg 0xa
'
run_test

NAME='pij 3'
FILE=malloc://512
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f
pij 3
'
EXPECT='[{"offset":0,"size":5,"opcode":"mov eax, 0x1","bytes":"b801000000","type":"mov","type_num":9,"type2_num":0},{"offset":5,"size":3,"opcode":"cmp rdx, rcx","bytes":"4839ca","type":"cmp","type_num":15,"type2_num":0},{"offset":8,"size":2,"opcode":"jg 0xa","bytes":"7f00","type":"cjmp","type_num":2147483649,"type2_num":0,"next":10,"fail":10}]
'
run_test


NAME='pi 6'
FILE=malloc://512
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00b8010000004839ca7f00
pi 6
'
EXPECT='mov eax, 0x1
cmp rdx, rcx
jg 0xa
mov eax, 0x1
cmp rdx, rcx
jg 0x14
'
run_test

NAME='pi -3 @ 3'
FILE=malloc://512
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pi -3 @ 10
'
EXPECT='add [rax], al
cmp rdx, rcx
jg 0xa
'
run_test

NAME='pij -3 @ 3'
FILE=malloc://512
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=64
wx b8010000004839ca7f00
pij -3 @ 10
'
EXPECT='[{"offset":3,"size":2,"opcode":"add [rax], al","bytes":"0000","type":"add","type_num":17,"type2_num":0},{"offset":5,"size":3,"opcode":"cmp rdx, rcx","bytes":"4839ca","type":"cmp","type_num":15,"type2_num":0},{"offset":8,"size":2,"opcode":"jg 0xa","bytes":"7f00","type":"cjmp","type_num":2147483649,"type2_num":0,"next":10,"fail":10}]
'
run_test
