#!/bin/sh

# LGPL 3+ - Copyright (C) 2015 maijin


[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='aa ; zF libc.sig'
FILE=../bins/elf/pid_stripped
ARGS=
CMDS="aa ; zF ../bins/other/sigs/libc.sig "
EXPECT='Loading:
Found flirt.__libc_start_main
'
run_test

NAME='zFd libc.sig'
FILE=../bins/elf/pid_stripped
ARGS=
CMDS="zFd ../bins/other/sigs/libc.sig "
EXPECT='Loading:
41564155B8........4154554D89C4534889CD4D89CD4881EC900000004885C0:
  0. 16 D2A2 0298 0000:__libc_start_main
'
run_test

NAME='af ; af ; zF libc.sig'
FILE=../bins/elf/pid_stripped
ARGS=
CMDS="s 0x4e2420 ; af ; s 0x4e25c7 ; af ; zF ../bins/other/sigs/libc.sig ; afl ~4e2420"
EXPECT='0x004e2420   61 664  -> 1022 flirt.__libc_start_main
'
run_test
