#!/bin/sh

# GPL 3+ - Copyright (C) 2012  pancake, Edd Barrett, Simon Ruderich

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

## test visual mode in batch

# XXX this test have several issues
# - local flags doesnt work that way
# - testing the output of 'pd' is a bad idea
# - functions are not flags
# - jumps into the same function doesnt show comments

NAME='Flags comments'
FILE=malloc://512
BROKEN=1
ARGS=
CMDS='
e asm.arch=x86
e asm.bits=16
wx 66b801000000b90f006683fb02e2fa66bb01000000c3
af+ 0000:0000 22 fnc1
f .loop1 @ 0000:0009
pd 1 @ 0000:000d
'
EXPECT='|          0000:000d   e2fa         loop 0x9 ; (fnc1)
'
run_test
