#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="stdin eof"
# Seems broken on some platforms.. strange
BROKEN=1
SHELLCMD='echo | rarun2 timeout=1 program="/usr/bin/r2" arg1=-nq arg2=-'
EXITCODE=0
run_test

NAME="stdin quit"
# fails in jenkins only?
BROKEN=
SHELLCMD='echo q | rarun2 timeout=1 program="/usr/bin/r2" arg1=-nq arg2=-'
EXITCODE=0
run_test

NAME="stdin quit"
# fails in jenkins only?
BROKEN=
SHELLCMD='echo q 2 | rarun2 timeout=1 program="/usr/bin/r2" arg1=-nq arg2=-'
EXITCODE=2
run_test
