#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done


NAME='rax2 =10 0x46'
CMDS='!rax2 =10 0x46'
EXPECT='70
'
run_test

NAME='rax2 10'
CMDS='!rax2 10'
EXPECT='0xa
'
run_test

NAME='rax2 0xa'
CMDS='!rax2 0xa'
EXPECT='10
'
run_test

NAME='rax2 -1'
CMDS='!rax2 -1'
EXPECT='0xffffffffffffffff
'
run_test

NAME='rax2 0xffffffffffffffff'
CMDS='!rax2 0xffffffffffffffff'
EXPECT='-1
'
run_test

NAME='rax2 b30'
CMDS='!rax2 b3'
EXPECT='11b
'
run_test

NAME='rax2 t42'
CMDS='!rax2 t42'
EXPECT='1120t
'
run_test

NAME='rax2 1010d'
CMDS='!rax2 1010d'
EXPECT='10
'
run_test

NAME='rax2 3.33f'
CMDS='!rax2 3.33f'
EXPECT='Fxb81e5540
'
run_test

NAME='rax2 Fx40551ed8'
CMDS='!rax2 Fx40551ed8'
EXPECT='3.33f
'
BROKEN=1
run_test

NAME='rax2 35o'
CMDS='!rax2 35o'
EXPECT='0x1d
'
run_test

NAME='rax2 Ox12'
CMDS='!rax2 Ox12'
EXPECT='22
'
run_test

NAME='rax2 1100011b'
CMDS='!rax2 1100011b'
EXPECT='0x63
'
run_test

NAME='rax2 Bx63'
CMDS='!rax2 Bx63'
EXPECT='1100011b
'
run_test

NAME='rax2 Tx23'
CMDS='!rax2 Tx23'
EXPECT='1022t
'
run_test

NAME='rax2 Tx23'
CMDS='!rax2 Tx23'
EXPECT='1022t
'
run_test

NAME='cat ../../bins/other/admin.txt | rax2 -S'
CMDS='!cat ../../bins/other/admin.txt | rax2 -S'
EXPECT='6161646d696e61
'
run_test

NAME='echo "414141" | rax2 -s '
CMDS='!echo -n "414141" | rax2 -s'
EXPECT='AAA'
run_test

NAME='rax2 -b 01000101 01110110'
CMDS='!rax2 -b 01000101 01110110'
EXPECT='Ev'
run_test

NAME='rax2 -B 33+3'
CMDS='!rax2 -B 33+3'
EXPECT='36
'
run_test

NAME='rax2 -e 0x00000401'
CMDS='!rax2 -e 0x00000401'
EXPECT='17039360
'
run_test

NAME='rax2 -f 6.3+2.1'
CMDS='!rax2 -f 6.3+2.1'
EXPECT='8.4
'
run_test

NAME='rax2 -n 0x1234'
CMDS='!rax2 -n 0x1234'
EXPECT='34120000
'
run_test

NAME='rax2 -N 0x1234'
CMDS='!rax2 -N 0x1234'
EXPECT='\x34\x12\x00\x00
'
run_test



NAME='rax2 -d 3'
CMDS='!rax2 -d 3'
EXPECT='3
'
run_test

NAME='rax2 -u 3000'
CMDS='!rax2 -u 3000'
EXPECT='2.9K
'
run_test

NAME='rax2 -v~commit?"'
CMDS='!!rax2 -v~commit?'
EXPECT='1
'
run_test