#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="esil x86-64"
BROKEN=1
CMDS='
?e
e asm.arch=x86
e asm.bits=64
wx 488d7768
ao~opcode,esil
'
EXPECT='
opcode: lea rsi, [rdi+0x68]
esil: rsi=rdi+104
'

run_test

NAME="esil x86-64"
BROKEN=1
CMDS='
?e
e asm.arch=x86
e asm.bits=64
wx c705dd40000001000000
ao~opcode,esil
'
EXPECT='
opcode: mov dword [rip+0x40dd], 0x1
esil: [rip+0x40dd]=1
'

run_test
