#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='r2 -'
FILE=-
ARGS=
CMDS='e file.path
'
EXPECT='malloc://512
'
run_test

NAME='r2 --'
FILE=--
ARGS=
CMDS='e file.path
'
EXPECT='
'
run_test
