#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

test_vector() {
NAME="${1}: [${2}]"
FILE=malloc://32
if [ "${5}" = "br" ]; then
		BROKEN=1
	fi
CMDS='
e asm.arch='${1}'
e asm.bits=64
wx '${3}'
pi 1
'
EXPECT="${4}
"
run_test
}

PLUGIN=arm

test_vector "${PLUGIN}" "msr sp_el0, x3" 034118d5 "msr sp_el0, x3"
test_vector "${PLUGIN}" "msr SP_EL0, x3" 034118d5 "msr sp_el0, x3"
test_vector "${PLUGIN}" "msr 0xc208, x3" 034118d5 "msr sp_el0, x3"
test_vector "${PLUGIN}" "mrs x3, SP_EL0" 034138d5 "mrs x3, sp_el0"
test_vector "${PLUGIN}" "nop" 1f2003d5 nop
test_vector "${PLUGIN}" "b 0x7fffff8" feffff15 "b 0x7fffff8"
test_vector "${PLUGIN}" "b 0x8" 02000014 "b 8"
test_vector "${PLUGIN}" "b 0xff4" fd030014 "b 0xff4"
test_vector "${PLUGIN}" "b 0x7efd4" f5fb0114 "b 0x7efd4"
test_vector "${PLUGIN}" "bl 0x8" 02000094 "bl 8"
test_vector "${PLUGIN}" "bl 0xfd4" f5030094 "bl 0xfd4"
test_vector "${PLUGIN}" "br x4" 80001fd6 "br x4"
test_vector "${PLUGIN}" "br x0" 00001fd6 "br x0"
test_vector "${PLUGIN}" "br x9" 20011fd6 "br x9"
test_vector "${PLUGIN}" "blr x7" e0003fd6 "blr x7"
test_vector "${PLUGIN}" "blr x12" 80013fd6 "blr x12"
test_vector "${PLUGIN}" "blr x29" a0033fd6 "blr x29"