#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="${PLUGIN}: arm-thumb-mclass"
CMDS='e asm.bits=16
wx eff31080
e asm.arch=arm
pi 1
e asm.arch=arm.cs
pi 1
'
EXPECT='mrs r0, primask
mrs r0, primask
'

run_test
