#!/bin/sh
for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="${PLUGIN}: arm-thumb-mclass"
CMDS='e asm.arch=arm
e asm.bits=16
e asm.features=mclass
wx eff31080
e asm.arch=arm
pi 1
e asm.arch=arm.gnu
pi 1
'
EXPECT='mrs r0, primask
mrs r0, PRIMASK
'

run_test

NAME="${PLUGIN}: arm-thumb-bad-branch"
FILE=malloc://32
CMDS='!rasm2 -a arm -b 16 "b gh"
'
EXPECT_ERR="Cannot assemble 'b gh' at line 3
invalid
"
run_test

