#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME="ao cjmp"
BROKEN=
FILE=-
IGNORE_ERR=1
ARGS=
CMDS='e asm.arch=x86
e asm.bits=32
wx 761b
ao~jump,fail,size
'
EXPECT='size: 2
jump: 0x0000001d
fail: 0x00000002
'
run_test

